// Copyright (C) 2026 Texas Instruments Incorporated
//
// SPDX-License-Identifier: Apache-2.0

#include "AUDIOLIB_inputAggregator_idat.h"
/*This file is autogenerated*/
/*Please do not edit*/

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
#include "test_data/staticRefCase1.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
#include "test_data/staticRefCase2.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
#include "test_data/staticRefCase3.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
#include "test_data/staticRefCase4.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
#include "test_data/staticRefCase5.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
#include "test_data/staticRefCase6.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
#include "test_data/staticRefCase7.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
#include "test_data/staticRefCase8.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
#include "test_data/staticRefCase9.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
#include "test_data/staticRefCase10.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
#include "test_data/staticRefCase11.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
#include "test_data/staticRefCase12.h"
#endif

/* ====================================================================== */
/* Static Input Pointer and Channel Count Arrays                        */
/* ====================================================================== */

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
static void *staticRefInCase1[2] = {
    (void *) staticRefInput0Case1,
    (void *) staticRefInput1Case1,
};
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
static void *staticRefInCase2[6] = {
    (void *) staticRefInput0Case2, (void *) staticRefInput1Case2, (void *) staticRefInput2Case2,
    (void *) staticRefInput3Case2, (void *) staticRefInput4Case2, (void *) staticRefInput5Case2,
};
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
static void *staticRefInCase3[5] = {
    (void *) staticRefInput0Case3, (void *) staticRefInput1Case3, (void *) staticRefInput2Case3,
    (void *) staticRefInput3Case3, (void *) staticRefInput4Case3,
};
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
static void *staticRefInCase4[2] = {
    (void *) staticRefInput0Case4,
    (void *) staticRefInput1Case4,
};
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
static void *staticRefInCase5[3] = {
    (void *) staticRefInput0Case5,
    (void *) staticRefInput1Case5,
    (void *) staticRefInput2Case5,
};
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
static void *staticRefInCase6[3] = {
    (void *) staticRefInput0Case6,
    (void *) staticRefInput1Case6,
    (void *) staticRefInput2Case6,
};
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
static void *staticRefInCase7[4] = {
    (void *) staticRefInput0Case7,
    (void *) staticRefInput1Case7,
    (void *) staticRefInput2Case7,
    (void *) staticRefInput3Case7,
};
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
static void *staticRefInCase8[6] = {
    (void *) staticRefInput0Case8, (void *) staticRefInput1Case8, (void *) staticRefInput2Case8,
    (void *) staticRefInput3Case8, (void *) staticRefInput4Case8, (void *) staticRefInput5Case8,
};
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
static void *staticRefInCase9[5] = {
    (void *) staticRefInput0Case9, (void *) staticRefInput1Case9, (void *) staticRefInput2Case9,
    (void *) staticRefInput3Case9, (void *) staticRefInput4Case9,
};
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
static void *staticRefInCase10[3] = {
    (void *) staticRefInput0Case10,
    (void *) staticRefInput1Case10,
    (void *) staticRefInput2Case10,
};
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
static void *staticRefInCase11[4] = {
    (void *) staticRefInput0Case11,
    (void *) staticRefInput1Case11,
    (void *) staticRefInput2Case11,
    (void *) staticRefInput3Case11,
};
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
static void *staticRefInCase12[3] = {
    (void *) staticRefInput0Case12,
    (void *) staticRefInput1Case12,
    (void *) staticRefInput2Case12,
};
#endif

static AUDIOLIB_inputAggregator_testParams_t testParams[] = {
#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
    {
        STATIC,                     // Test pattern
        (void **) staticRefInCase1, // pInputs (pointer to array of input pointers)
        staticRefOutCase1,          // Output buffer
        512,                        // inSamples
        6,                          // totalInChannels
        inChannelsCase1,            // Pointer to array of channel counts
        0,                          // isInputInterleave
        0,                          // isOutputInterleave
        2,                          // numInputs
        AUDIOLIB_CALC_STRIDE(512 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(512 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT32,                                                        // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        1,                                                                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
    {
        STATIC,                     // Test pattern
        (void **) staticRefInCase2, // pInputs (pointer to array of input pointers)
        staticRefOutCase2,          // Output buffer
        17,                         // inSamples
        26,                         // totalInChannels
        inChannelsCase2,            // Pointer to array of channel counts
        1,                          // isInputInterleave
        0,                          // isOutputInterleave
        6,                          // numInputs
        AUDIOLIB_CALC_STRIDE(17 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(17 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT32,                                                       // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                              // Output data location
        1,                                                                      // number of reps.
        2,                                                                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
    {
        STATIC,                     // Test pattern
        (void **) staticRefInCase3, // pInputs (pointer to array of input pointers)
        staticRefOutCase3,          // Output buffer
        128,                        // inSamples
        24,                         // totalInChannels
        inChannelsCase3,            // Pointer to array of channel counts
        1,                          // isInputInterleave
        1,                          // isOutputInterleave
        5,                          // numInputs
        AUDIOLIB_CALC_STRIDE(128 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(128 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT32,                                                        // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        3,                                                                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
    {
        STATIC,                     // Test pattern
        (void **) staticRefInCase4, // pInputs (pointer to array of input pointers)
        staticRefOutCase4,          // Output buffer
        256,                        // inSamples
        6,                          // totalInChannels
        inChannelsCase4,            // Pointer to array of channel counts
        0,                          // isInputInterleave
        1,                          // isOutputInterleave
        2,                          // numInputs
        AUDIOLIB_CALC_STRIDE(256 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(256 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT32,                                                        // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        4,                                                                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
    {
        STATIC,                     // Test pattern
        (void **) staticRefInCase5, // pInputs (pointer to array of input pointers)
        staticRefOutCase5,          // Output buffer
        3,                          // inSamples
        14,                         // totalInChannels
        inChannelsCase5,            // Pointer to array of channel counts
        0,                          // isInputInterleave
        0,                          // isOutputInterleave
        3,                          // numInputs
        AUDIOLIB_CALC_STRIDE(3 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(3 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT32,                                                      // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                             // Output data location
        1,                                                                     // number of reps.
        5,                                                                     // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
    {
        STATIC,                     // Test pattern
        (void **) staticRefInCase6, // pInputs (pointer to array of input pointers)
        staticRefOutCase6,          // Output buffer
        256,                        // inSamples
        15,                         // totalInChannels
        inChannelsCase6,            // Pointer to array of channel counts
        1,                          // isInputInterleave
        1,                          // isOutputInterleave
        3,                          // numInputs
        AUDIOLIB_CALC_STRIDE(256 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(256 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT32,                                                        // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        6,                                                                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
    {
        STATIC,                     // Test pattern
        (void **) staticRefInCase7, // pInputs (pointer to array of input pointers)
        staticRefOutCase7,          // Output buffer
        128,                        // inSamples
        18,                         // totalInChannels
        inChannelsCase7,            // Pointer to array of channel counts
        0,                          // isInputInterleave
        0,                          // isOutputInterleave
        4,                          // numInputs
        AUDIOLIB_CALC_STRIDE(128 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(128 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT64,                                                         // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                // Output data location
        1,                                                                        // number of reps.
        7,                                                                        // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
    {
        STATIC,                     // Test pattern
        (void **) staticRefInCase8, // pInputs (pointer to array of input pointers)
        staticRefOutCase8,          // Output buffer
        32,                         // inSamples
        26,                         // totalInChannels
        inChannelsCase8,            // Pointer to array of channel counts
        1,                          // isInputInterleave
        0,                          // isOutputInterleave
        6,                          // numInputs
        AUDIOLIB_CALC_STRIDE(32 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(32 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT64,                                                        // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        8,                                                                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
    {
        STATIC,                     // Test pattern
        (void **) staticRefInCase9, // pInputs (pointer to array of input pointers)
        staticRefOutCase9,          // Output buffer
        128,                        // inSamples
        24,                         // totalInChannels
        inChannelsCase9,            // Pointer to array of channel counts
        1,                          // isInputInterleave
        1,                          // isOutputInterleave
        5,                          // numInputs
        AUDIOLIB_CALC_STRIDE(64 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(64 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT64,                                                        // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        9,                                                                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
    {
        STATIC,                      // Test pattern
        (void **) staticRefInCase10, // pInputs (pointer to array of input pointers)
        staticRefOutCase10,          // Output buffer
        64,                          // inSamples
        9,                           // totalInChannels
        inChannelsCase10,            // Pointer to array of channel counts
        0,                           // isInputInterleave
        1,                           // isOutputInterleave
        3,                           // numInputs
        AUDIOLIB_CALC_STRIDE(64 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(64 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT64,                                                        // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        10,                                                                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
    {
        STATIC,                      // Test pattern
        (void **) staticRefInCase11, // pInputs (pointer to array of input pointers)
        staticRefOutCase11,          // Output buffer
        256,                         // inSamples
        20,                          // totalInChannels
        inChannelsCase11,            // Pointer to array of channel counts
        0,                           // isInputInterleave
        0,                           // isOutputInterleave
        4,                           // numInputs
        AUDIOLIB_CALC_STRIDE(256 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(256 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT64,                                                         // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                // Output data location
        1,                                                                        // number of reps.
        11,                                                                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
    {
        STATIC,                      // Test pattern
        (void **) staticRefInCase12, // pInputs (pointer to array of input pointers)
        staticRefOutCase12,          // Output buffer
        128,                         // inSamples
        12,                          // totalInChannels
        inChannelsCase12,            // Pointer to array of channel counts
        1,                           // isInputInterleave
        0,                           // isOutputInterleave
        3,                           // numInputs
        AUDIOLIB_CALC_STRIDE(128 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(128 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT64,                                                         // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                // Output data location
        1,                                                                        // number of reps.
        12,                                                                       // test ID
    },
#endif

};

/*
 *  Sends the test parameter structure and number of tests
 */
void AUDIOLIB_inputAggregator_getTestParams(AUDIOLIB_inputAggregator_testParams_t **params, int32_t *numTests)
{
   *params   = testParams;
   *numTests = sizeof(testParams) / sizeof(AUDIOLIB_inputAggregator_testParams_t);
}
