// Copyright (C) 2026 Texas Instruments Incorporated
//
// SPDX-License-Identifier: Apache-2.0

#include "AUDIOLIB_undB10_idat.h"
/*This file is autogenerated*/
/*Please do not edit*/

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
#include "test_data/staticRefCase1.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
#include "test_data/staticRefCase2.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
#include "test_data/staticRefCase3.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
#include "test_data/staticRefCase4.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
#include "test_data/staticRefCase5.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
#include "test_data/staticRefCase6.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
#include "test_data/staticRefCase7.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
#include "test_data/staticRefCase8.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
#include "test_data/staticRefCase9.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
#include "test_data/staticRefCase10.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
#include "test_data/staticRefCase11.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
#include "test_data/staticRefCase12.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13))
#include "test_data/staticRefCase13.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 14))
#include "test_data/staticRefCase14.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 15))
#include "test_data/staticRefCase15.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 16))
#include "test_data/staticRefCase16.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 17))
#include "test_data/staticRefCase17.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 18))
#include "test_data/staticRefCase18.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 19))
#include "test_data/staticRefCase19.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 20))
#include "test_data/staticRefCase20.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 21))
#include "test_data/staticRefCase21.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 22))
#include "test_data/staticRefCase22.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 23))
#include "test_data/staticRefCase23.h"
#endif

static AUDIOLIB_undB10_testParams_t testParams[] = {
#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
    {
        STATIC,                                                                  // Test pattern
        staticRefInCase1,                                                        // Input vector
        staticRefOutCase1,                                                       // Output vector
        AUDIOLIB_FLOAT32,                                                        // DataType
        25,                                                                      // No of Channels
        512,                                                                     // No of Samples
        AUDIOLIB_CALC_STRIDE(512 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn
        AUDIOLIB_CALC_STRIDE(512 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        1,                                                                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
    {
        STATIC,                                                                   // Test pattern
        staticRefInCase2,                                                         // Input vector
        staticRefOutCase2,                                                        // Output vector
        AUDIOLIB_FLOAT32,                                                         // DataType
        27,                                                                       // No of Channels
        1024,                                                                     // No of Samples
        AUDIOLIB_CALC_STRIDE(1024 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn
        AUDIOLIB_CALC_STRIDE(1024 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                // Output data location
        1,                                                                        // number of reps.
        2,                                                                        // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
    {
        STATIC,                                                                   // Test pattern
        staticRefInCase3,                                                         // Input vector
        staticRefOutCase3,                                                        // Output vector
        AUDIOLIB_FLOAT32,                                                         // DataType
        7,                                                                        // No of Channels
        2048,                                                                     // No of Samples
        AUDIOLIB_CALC_STRIDE(2048 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn
        AUDIOLIB_CALC_STRIDE(2048 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                // Output data location
        1,                                                                        // number of reps.
        3,                                                                        // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
    {
        STATIC,                                                                  // Test pattern
        staticRefInCase4,                                                        // Input vector
        staticRefOutCase4,                                                       // Output vector
        AUDIOLIB_FLOAT32,                                                        // DataType
        40,                                                                      // No of Channels
        192,                                                                     // No of Samples
        AUDIOLIB_CALC_STRIDE(192 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn
        AUDIOLIB_CALC_STRIDE(192 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        4,                                                                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
    {
        STATIC,                                                                  // Test pattern
        staticRefInCase5,                                                        // Input vector
        staticRefOutCase5,                                                       // Output vector
        AUDIOLIB_FLOAT32,                                                        // DataType
        24,                                                                      // No of Channels
        256,                                                                     // No of Samples
        AUDIOLIB_CALC_STRIDE(256 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn
        AUDIOLIB_CALC_STRIDE(512 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        5,                                                                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
    {
        STATIC,                                                                 // Test pattern
        staticRefInCase6,                                                       // Input vector
        staticRefOutCase6,                                                      // Output vector
        AUDIOLIB_FLOAT32,                                                       // DataType
        62,                                                                     // No of Channels
        32,                                                                     // No of Samples
        AUDIOLIB_CALC_STRIDE(32 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn
        AUDIOLIB_CALC_STRIDE(32 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_TEST_OUTPUT_MSMC,                                              // Output data location
        1,                                                                      // number of reps.
        6,                                                                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
    {
        STATIC,                                                                 // Test pattern
        staticRefInCase7,                                                       // Input vector
        staticRefOutCase7,                                                      // Output vector
        AUDIOLIB_FLOAT32,                                                       // DataType
        45,                                                                     // No of Channels
        1,                                                                      // No of Samples
        AUDIOLIB_CALC_STRIDE(64 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn
        AUDIOLIB_CALC_STRIDE(64 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_TEST_OUTPUT_MSMC,                                              // Output data location
        1,                                                                      // number of reps.
        7,                                                                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
    {
        STATIC,                                                                  // Test pattern
        staticRefInCase8,                                                        // Input vector
        staticRefOutCase8,                                                       // Output vector
        AUDIOLIB_FLOAT32,                                                        // DataType
        18,                                                                      // No of Channels
        256,                                                                     // No of Samples
        AUDIOLIB_CALC_STRIDE(256 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn
        AUDIOLIB_CALC_STRIDE(256 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        8,                                                                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
    {
        STATIC,                                                                // Test pattern
        staticRefInCase9,                                                      // Input vector
        staticRefOutCase9,                                                     // Output vector
        AUDIOLIB_FLOAT32,                                                      // DataType
        1,                                                                     // No of Channels
        1,                                                                     // No of Samples
        AUDIOLIB_CALC_STRIDE(1 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn
        AUDIOLIB_CALC_STRIDE(1 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_TEST_OUTPUT_MSMC,                                             // Output data location
        1,                                                                     // number of reps.
        9,                                                                     // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
    {
        STATIC,                                                                  // Test pattern
        staticRefInCase10,                                                       // Input vector
        staticRefOutCase10,                                                      // Output vector
        AUDIOLIB_FLOAT32,                                                        // DataType
        20,                                                                      // No of Channels
        128,                                                                     // No of Samples
        AUDIOLIB_CALC_STRIDE(256 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn
        AUDIOLIB_CALC_STRIDE(128 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        10,                                                                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
    {
        STATIC,                                                                  // Test pattern
        staticRefInCase11,                                                       // Input vector
        staticRefOutCase11,                                                      // Output vector
        AUDIOLIB_FLOAT32,                                                        // DataType
        45,                                                                      // No of Channels
        192,                                                                     // No of Samples
        AUDIOLIB_CALC_STRIDE(256 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn
        AUDIOLIB_CALC_STRIDE(192 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        11,                                                                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
    {
        STATIC,                                                                   // Test pattern
        staticRefInCase12,                                                        // Input vector
        staticRefOutCase12,                                                       // Output vector
        AUDIOLIB_FLOAT32,                                                         // DataType
        1,                                                                        // No of Channels
        1024,                                                                     // No of Samples
        AUDIOLIB_CALC_STRIDE(1024 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn
        AUDIOLIB_CALC_STRIDE(1024 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                // Output data location
        1,                                                                        // number of reps.
        12,                                                                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13))
    {
        STATIC,                                                                  // Test pattern
        staticRefInCase13,                                                       // Input vector
        staticRefOutCase13,                                                      // Output vector
        AUDIOLIB_FLOAT32,                                                        // DataType
        20,                                                                      // No of Channels
        512,                                                                     // No of Samples
        AUDIOLIB_CALC_STRIDE(512 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn
        AUDIOLIB_CALC_STRIDE(512 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        13,                                                                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 14))
    {
        STATIC,                                                                  // Test pattern
        staticRefInCase14,                                                       // Input vector
        staticRefOutCase14,                                                      // Output vector
        AUDIOLIB_FLOAT32,                                                        // DataType
        60,                                                                      // No of Channels
        195,                                                                     // No of Samples
        AUDIOLIB_CALC_STRIDE(195 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn
        AUDIOLIB_CALC_STRIDE(195 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        14,                                                                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 15))
    {
        STATIC,                                                                  // Test pattern
        staticRefInCase15,                                                       // Input vector
        staticRefOutCase15,                                                      // Output vector
        AUDIOLIB_FLOAT32,                                                        // DataType
        32,                                                                      // No of Channels
        128,                                                                     // No of Samples
        AUDIOLIB_CALC_STRIDE(128 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn
        AUDIOLIB_CALC_STRIDE(256 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        15,                                                                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 16))
    {
        STATIC,                                                                  // Test pattern
        staticRefInCase16,                                                       // Input vector
        staticRefOutCase16,                                                      // Output vector
        AUDIOLIB_FLOAT32,                                                        // DataType
        35,                                                                      // No of Channels
        192,                                                                     // No of Samples
        AUDIOLIB_CALC_STRIDE(192 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn
        AUDIOLIB_CALC_STRIDE(192 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        16,                                                                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 17))
    {
        STATIC,                                                                   // Test pattern
        staticRefInCase17,                                                        // Input vector
        staticRefOutCase17,                                                       // Output vector
        AUDIOLIB_FLOAT32,                                                         // DataType
        18,                                                                       // No of Channels
        1024,                                                                     // No of Samples
        AUDIOLIB_CALC_STRIDE(1024 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn
        AUDIOLIB_CALC_STRIDE(1024 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                // Output data location
        1,                                                                        // number of reps.
        17,                                                                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 18))
    {
        STATIC,                                                                   // Test pattern
        staticRefInCase18,                                                        // Input vector
        staticRefOutCase18,                                                       // Output vector
        AUDIOLIB_FLOAT32,                                                         // DataType
        34,                                                                       // No of Channels
        512,                                                                      // No of Samples
        AUDIOLIB_CALC_STRIDE(512 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideIn
        AUDIOLIB_CALC_STRIDE(1024 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                // Output data location
        1,                                                                        // number of reps.
        18,                                                                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 19))
    {
        STATIC,                                                                  // Test pattern
        staticRefInCase19,                                                       // Input vector
        staticRefOutCase19,                                                      // Output vector
        AUDIOLIB_FLOAT32,                                                        // DataType
        64,                                                                      // No of Channels
        256,                                                                     // No of Samples
        AUDIOLIB_CALC_STRIDE(256 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn
        AUDIOLIB_CALC_STRIDE(256 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        19,                                                                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 20))
    {
        STATIC,                                                                // Test pattern
        staticRefInCase20,                                                     // Input vector
        staticRefOutCase20,                                                    // Output vector
        AUDIOLIB_FLOAT32,                                                      // DataType
        64,                                                                    // No of Channels
        1,                                                                     // No of Samples
        AUDIOLIB_CALC_STRIDE(1 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn
        AUDIOLIB_CALC_STRIDE(1 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_TEST_OUTPUT_MSMC,                                             // Output data location
        1,                                                                     // number of reps.
        20,                                                                    // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 21))
    {
        STATIC,                                                                  // Test pattern
        staticRefInCase21,                                                       // Input vector
        staticRefOutCase21,                                                      // Output vector
        AUDIOLIB_FLOAT32,                                                        // DataType
        1,                                                                       // No of Channels
        512,                                                                     // No of Samples
        AUDIOLIB_CALC_STRIDE(512 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn
        AUDIOLIB_CALC_STRIDE(512 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        21,                                                                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 22))
    {
        STATIC,                                                                   // Test pattern
        staticRefInCase22,                                                        // Input vector
        staticRefOutCase22,                                                       // Output vector
        AUDIOLIB_FLOAT32,                                                         // DataType
        1,                                                                        // No of Channels
        1024,                                                                     // No of Samples
        AUDIOLIB_CALC_STRIDE(1024 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn
        AUDIOLIB_CALC_STRIDE(1024 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                // Output data location
        1,                                                                        // number of reps.
        22,                                                                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 23))
    {
        STATIC,                                                                   // Test pattern
        staticRefInCase23,                                                        // Input vector
        staticRefOutCase23,                                                       // Output vector
        AUDIOLIB_FLOAT32,                                                         // DataType
        1,                                                                        // No of Channels
        2048,                                                                     // No of Samples
        AUDIOLIB_CALC_STRIDE(2048 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn
        AUDIOLIB_CALC_STRIDE(2048 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                // Output data location
        1,                                                                        // number of reps.
        23,                                                                       // test ID
    },
#endif

};

/*
 *  Sends the test parameter structure and number of tests
 */
void AUDIOLIB_undB10_getTestParams(AUDIOLIB_undB10_testParams_t** params, int32_t* numTests)
{
   *params   = testParams;
   *numTests = sizeof(testParams) / sizeof(AUDIOLIB_undB10_testParams_t);
}
