// Copyright (C) 2026 Texas Instruments Incorporated
//
// SPDX-License-Identifier: Apache-2.0

#ifndef AUDIOLIB_TABLELOOKUP_IXX_IXX_OXX_H_
#define AUDIOLIB_TABLELOOKUP_IXX_IXX_OXX_H_

#include "../common/AUDIOLIB_types.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @defgroup AUDIOLIB_tableLookup AUDIOLIB_tableLookup
 * @brief Kernel for multichannel tableLookup apply
 *
 * @details
 * This kernel applies a common lookup table to multiple audio channels.
 * Each input sample from the source buffer is mapped to a lookup table entry
 * based on its normalized position between the minimum and maximum values
 * found in the source data (`minVal`, `maxVal`). The output is generated by
 * fetching the corresponding value from the lookup table with boundary handling.
 *
 * ---
 * **Mathematical Formulation**
 *
 * \f[
 * \begin{aligned}
 * \textbf{Given:} \quad
 * & \mathbf{x} = [x_0, x_1, \dots, x_{N-1}] \quad \text{(source samples)} \\
 * & \mathbf{T} = [T_0, T_1, \dots, T_{M-1}] \quad \text{(lookup table)} \\
 * & \text{Parameters: }
 *   \text{minVal} = \min(\mathbf{x}), \;
 *   \text{maxVal} = \max(\mathbf{x}), \;
 *   \text{tableSamples} = M \\[6pt]
 * %
 * \textbf{Divisor calculation:} \quad
 * & \text{divisor} = \frac{M - 1}{\text{maxVal} - \text{minVal}} \\[6pt]
 * %
 * \textbf{Normalization and scaling:} \quad
 * & \mathbf{s} = (\mathbf{x} - \text{minVal}) \cdot \text{divisor} + 0.5 \\[6pt]
 * %
 * \textbf{Index computation:} \quad
 * & \mathbf{i} = \lfloor \mathbf{s} \rfloor \\[6pt]
 * %
 * \textbf{Lookup with boundary handling:} \quad
 * y_n =
 * \begin{cases}
 * T_0, & \text{if } s_n \le 0 \\[4pt]
 * T_{M-1}, & \text{if } s_n \ge M - 1 \\[4pt]
 * T_{i_n}, & \text{otherwise}
 * \end{cases}
 * \quad \forall n \in [0, N-1]
 * \end{aligned}
 * \f]
 *
 * ---
 * **Parameter Roles**
 * - `minVal`: Minimum value found in the source data. Samples ≤ `minVal` map to `T_0`.
 * - `maxVal`: Maximum value found in the source data. Samples ≥ `maxVal` map to `T_{M-1}`.
 * - `divisor`: Scaling factor computed as
 *   \f$\frac{M - 1}{\text{maxVal} - \text{minVal}}\f$,
 *   used to linearly map the source range \f$[\text{minVal}, \text{maxVal}]\f$
 *   to the lookup table index range \f$[0, M-1]\f$.
 *
 * ---
 * **Initialization and Table Size Configuration**
 * - During initialization (`AUDIOLIB_tableLookup_InitArgs`), the user can specify
 *   a custom lookup table size using the `tableLookupSize` parameter.
 * - The **default lookup table size** is **8 KB**.
 * - Users can modify this size in the **linker script** by adjusting the memory
 *   allocation for the lookup table section.
 * - At runtime, the kernel compares the configured `tableLookupSize` with the
 *   number of provided table samples (`tableSamples`) and selects the optimal
 *   execution path accordingly.
 *
 * ---
 * **Execution Path Selection**
 * - **Platform-specific behavior:**
 *   - **AM275:**
 *     - Default execution function: `AUDIOLIB_tableLookup_exec_ci`
 *     - If the given table size (`tableSamples`) **exceeds** the configured
 *       `tableLookupSize` (default = 8 KB), the kernel automatically switches to
 *       `AUDIOLIB_tableLookup_unroll_exec_ci` for optimized processing of larger tables.
 *   - **AM62D:**
 *     - Always uses `AUDIOLIB_tableLookup_unroll_exec_ci` as the default
 *       execution function.
 * - This mechanism allows the library to balance between memory efficiency
 *   and throughput depending on the platform and table size.
 *
 * ---
 * **Notes**
 * - The `+0.5` term in scaling implements rounding to the nearest index.
 * - Values outside the input range are clamped to the nearest valid table entry.
 * - The kernel supports multi-channel (vectorized) lookup operations using a shared table.
 * - The kernel supports only FLOAT dataType.
 *
 * @ingroup AUDIOLIB
 */
/**@{*/

/**
 * @brief Structure containing the parameters to initialize the kernel
 */
typedef struct {
   /** @brief Variant of the function refer to @ref AUDIOLIB_FUNCTION_STYLE     */
   int8_t   funcStyle;
   float    minVal;
   float    maxVal;
   uint32_t tableLookupSize;

} AUDIOLIB_tableLookup_InitArgs;

/**
 *  @brief        This is a query function to calculate the size of internal
 *                handle
 *  @param [in]   pKerInitArgs  : Pointer to structure holding init parameters
 *  @return       Size of the buffer in bytes
 *  @remarks      Application is expected to allocate buffer of the requested
 *                size and provide it as input to other functions requiring it.
 */
int32_t AUDIOLIB_tableLookup_getHandleSize(AUDIOLIB_tableLookup_InitArgs *pKerInitArgs);

/**
 *  @brief       This function should be called before the
 *               @ref AUDIOLIB_tableLookup_exec function is called. This
 *               function takes care of any one-time operations such as setting
 *               up the configuration of required hardware resources such as
 *               the streaming engine.  The results of these
 *               operations are stored in the handle.
 *
 *  @param [in]  handle        :  Active handle to the kernel
 *  @param [in]  bufParamsIn0  :  Pointer to the structure containing dimensional
                                  information of src buffer
 *  @param [in]  bufParamsIn1  :  Pointer to the structure containing dimensional
 *                                information of table buffer
 *  @param [out] bufParamsOut  :  Pointer to the structure containing dimensional
 *                                information of ouput buffer
 *  @param [in]  pKerInitArgs  :  Pointer to the structure holding init
 * parameters
 *
 *  @return      Status value indicating success or failure. Refer to @ref
 * AUDIOLIB_STATUS.
 *
 *  @remarks     Application is expected to provide a valid handle.
 */

AUDIOLIB_STATUS AUDIOLIB_tableLookup_init(AUDIOLIB_kernelHandle                handle,
                                          const AUDIOLIB_bufParams1D_t        *bufParamsIn0,
                                          const AUDIOLIB_bufParams1D_t        *bufParamsIn1,
                                          const AUDIOLIB_bufParams1D_t        *bufParamsOut,
                                          const AUDIOLIB_tableLookup_InitArgs *pKerInitArgs);

/**
 *  @brief       This function checks the validity of the parameters passed to
 *               @ref AUDIOLIB_tableLookup_init function. This function
 *               is called with the same parameters as the
 *               @ref AUDIOLIB_tableLookup_init, and this function
 *               must be called before the
 *               @ref AUDIOLIB_tableLookup_init is called.
 *
 *  @param [in]  handle        :  Active handle to the kernel
 *  @param [in]  bufParamsIn0  :  Pointer to the structure containing dimensional
                                  information of src buffer
 *  @param [in]  bufParamsIn1  :  Pointer to the structure containing dimensional
 *                                information of table buffer
 *  @param [out] bufParamsOut  :  Pointer to the structure containing dimensional
 *                                information of ouput buffer
 *  @param [in]  pKerInitArgs  :  Pointer to the structure holding init
 * parameters
 *
 *  @return      Status value indicating success or failure. Refer to @ref
 * AUDIOLIB_STATUS.
 *
 *  @remarks     None
 */
AUDIOLIB_STATUS
AUDIOLIB_tableLookup_init_checkParams(AUDIOLIB_kernelHandle                handle,
                                      const AUDIOLIB_bufParams1D_t        *bufParamsIn0,
                                      const AUDIOLIB_bufParams1D_t        *bufParamsIn1,
                                      const AUDIOLIB_bufParams1D_t        *bufParamsOut,
                                      const AUDIOLIB_tableLookup_InitArgs *pKerInitArgs);

/**
 *  @brief       This function checks the validity of the parameters passed to
 *               @ref AUDIOLIB_tableLookup_exec function. This function
 *               is called with the same parameters as the
 *               @ref AUDIOLIB_tableLookup_init, and this function
 *               must be called before the
 *               @ref AUDIOLIB_tableLookup_init is called.
 *
 *  @param [in]  handle      : Active handle to the kernel
 *  @param [in]  pIn0        : Pointer to buffer holding the src buffer
 *  @param [in]  pIn1        : Pointer to buffer holding the table buffer
 *  @param [out] pOut        : Pointer to buffer holding the output buffer
 *
 *  @return      Status value indicating success or failure. Refer to @ref
 * AUDIOLIB_STATUS.
 *
 *  @remarks     None
 * */
AUDIOLIB_STATUS AUDIOLIB_tableLookup_exec_checkParams(AUDIOLIB_kernelHandle handle,
                                                      const void *restrict pIn0,
                                                      const void *restrict pIn1,
                                                      const void *restrict pOut);

void AUDIOLIB_tableLookup_set_ci(AUDIOLIB_kernelHandle handle, void *restrict pIn1);

/**
 *  @brief       This function is the main kernel compute function.
 *
 *  @details     Please refer to details under
 *               @ref AUDIOLIB_tableLookup_exec
 *
 *  @param [in]  handle      : Active handle to the kernel
 *  @param [in]  pIn0        : Pointer to buffer holding the src buffer
 *  @param [in]  pIn1        : Pointer to buffer holding the table buffer
 *  @param [out] pOut        : Pointer to buffer holding the output buffer
 *
 *  @return      Status value indicating success or failure. Refer to @ref
 * AUDIOLIB_STATUS.
 *
 *  @par Assumptions:
 *    - None
 *
 *  @par Performance Considerations:
 *    For best performance,
 *    - the input and output data buffers are expected to be in L2 memory
 *    - the buffer pointers are assumed to be 64-byte aligned
 *
 *  @remarks     Before calling this function, application is expected to call
 *               @ref AUDIOLIB_tableLookup_init and
 *               This ensures resource configuration and error checks are done
 *               only once for several invocations of this function.
 */

AUDIOLIB_STATUS
AUDIOLIB_tableLookup_exec(AUDIOLIB_kernelHandle handle, void *restrict pIn0, void *restrict pIn1, void *restrict pOut);

/** * @brief Estimates the performance of the tableLookup kernel.
 *
 *  @param [in]  handle           : Active handle to the kernel
 *  @param [out] archCycles       : Pointer to store the estimated architecture cycles
 *  @param [out] estCycles        : Pointer to store the estimated cycles for execution
 *  @param [in]  data_type        : Data type of the processing input
 *  @param [in]  tableLookupSize  : Table lookup size set by the user
 *  @param [in]  pKerInitArgs     :  Pointer to the structure holding init
 *
 * *  @details This function provides an estimation of the performance characteristics
 *           of the tableLookup kernel
 * */
void AUDIOLIB_tableLookup_perfEst(AUDIOLIB_kernelHandle                handle,
                                  uint64_t                            *archCycles,
                                  uint64_t                            *estCycles,
                                  uint32_t                             data_type,
                                  uint32_t                             tableLookupSize,
                                  const AUDIOLIB_tableLookup_InitArgs *pKerInitArgs);
/** @} */

#ifdef __cplusplus
}
#endif

#endif /* AUDIOLIB_TABLELOOKUP_IXX_IXX_OXX_H_ */
