// Copyright (C) 2026 Texas Instruments Incorporated
//
// SPDX-License-Identifier: Apache-2.0

#include "AUDIOLIB_softClip_idat.h"
/*This file is autogenerated*/
/*Please do not edit*/

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
#include "test_data/staticRefCase1.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
#include "test_data/staticRefCase2.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
#include "test_data/staticRefCase3.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
#include "test_data/staticRefCase4.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
#include "test_data/staticRefCase5.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
#include "test_data/staticRefCase6.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
#include "test_data/staticRefCase7.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
#include "test_data/staticRefCase8.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
#include "test_data/staticRefCase9.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
#include "test_data/staticRefCase10.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
#include "test_data/staticRefCase11.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
#include "test_data/staticRefCase12.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13))
#include "test_data/staticRefCase13.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 14))
#include "test_data/staticRefCase14.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 15))
#include "test_data/staticRefCase15.h"
#endif

static AUDIOLIB_softClip_testParams_t testParams[] = {
#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
    {
        STATIC,                                                                 // Test pattern
        staticRefIn0Case1,                                                      // Input buffer
        staticRefOutCase1,                                                      // Output buffer
        35,                                                                     // inSamples
        1,                                                                      // inChannels
        AUDIOLIB_CALC_STRIDE(35 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(35 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        0.5,                                                                    // threshold
        1.0,                                                                    // endKnee
        AUDIOLIB_FLOAT32,                                                       // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                              // Output data location
        1,                                                                      // number of reps.
        1,                                                                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
    {
        STATIC,                                                                 // Test pattern
        staticRefIn0Case2,                                                      // Input buffer
        staticRefOutCase2,                                                      // Output buffer
        40,                                                                     // inSamples
        1,                                                                      // inChannels
        AUDIOLIB_CALC_STRIDE(40 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(40 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        0.5,                                                                    // threshold
        1.0,                                                                    // endKnee
        AUDIOLIB_FLOAT32,                                                       // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                              // Output data location
        1,                                                                      // number of reps.
        2,                                                                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
    {
        STATIC,                                                                  // Test pattern
        staticRefIn0Case3,                                                       // Input buffer
        staticRefOutCase3,                                                       // Output buffer
        100,                                                                     // inSamples
        30,                                                                      // inChannels
        AUDIOLIB_CALC_STRIDE(100 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(100 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        0.5,                                                                     // threshold
        1.0,                                                                     // endKnee
        AUDIOLIB_FLOAT32,                                                        // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        3,                                                                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
    {
        STATIC,                                                                 // Test pattern
        staticRefIn0Case4,                                                      // Input buffer
        staticRefOutCase4,                                                      // Output buffer
        16,                                                                     // inSamples
        1,                                                                      // inChannels
        AUDIOLIB_CALC_STRIDE(16 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(16 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        0.5,                                                                    // threshold
        1.0,                                                                    // endKnee
        AUDIOLIB_FLOAT32,                                                       // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                              // Output data location
        1,                                                                      // number of reps.
        4,                                                                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
    {
        STATIC,                                                                 // Test pattern
        staticRefIn0Case5,                                                      // Input buffer
        staticRefOutCase5,                                                      // Output buffer
        15,                                                                     // inSamples
        10,                                                                     // inChannels
        AUDIOLIB_CALC_STRIDE(17 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(19 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        0.25,                                                                   // threshold
        1.0,                                                                    // endKnee
        AUDIOLIB_FLOAT32,                                                       // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                              // Output data location
        1,                                                                      // number of reps.
        5,                                                                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
    {
        STATIC,                                                                  // Test pattern
        staticRefIn0Case6,                                                       // Input buffer
        staticRefOutCase6,                                                       // Output buffer
        100,                                                                     // inSamples
        18,                                                                      // inChannels
        AUDIOLIB_CALC_STRIDE(100 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(105 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        1.5,                                                                     // threshold
        2.0,                                                                     // endKnee
        AUDIOLIB_FLOAT32,                                                        // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        6,                                                                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
    {
        STATIC,                                                                  // Test pattern
        staticRefIn0Case7,                                                       // Input buffer
        staticRefOutCase7,                                                       // Output buffer
        256,                                                                     // inSamples
        34,                                                                      // inChannels
        AUDIOLIB_CALC_STRIDE(257 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(256 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        0.6,                                                                     // threshold
        1.0,                                                                     // endKnee
        AUDIOLIB_FLOAT32,                                                        // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        7,                                                                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
    {
        STATIC,                                                                  // Test pattern
        staticRefIn0Case8,                                                       // Input buffer
        staticRefOutCase8,                                                       // Output buffer
        512,                                                                     // inSamples
        56,                                                                      // inChannels
        AUDIOLIB_CALC_STRIDE(512 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(512 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        0.1,                                                                     // threshold
        1.0,                                                                     // endKnee
        AUDIOLIB_FLOAT32,                                                        // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        8,                                                                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
    {
        STATIC,                                                                   // Test pattern
        staticRefIn0Case9,                                                        // Input buffer
        staticRefOutCase9,                                                        // Output buffer
        1024,                                                                     // inSamples
        64,                                                                       // inChannels
        AUDIOLIB_CALC_STRIDE(1024 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(1024 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        0.3,                                                                      // threshold
        1.0,                                                                      // endKnee
        AUDIOLIB_FLOAT32,                                                         // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                // Output data location
        1,                                                                        // number of reps.
        9,                                                                        // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
    {
        STATIC,                                                                 // Test pattern
        staticRefIn0Case10,                                                     // Input buffer
        staticRefOutCase10,                                                     // Output buffer
        50,                                                                     // inSamples
        12,                                                                     // inChannels
        AUDIOLIB_CALC_STRIDE(50 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(50 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        2.0,                                                                    // threshold
        2.5,                                                                    // endKnee
        AUDIOLIB_FLOAT32,                                                       // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                              // Output data location
        1,                                                                      // number of reps.
        10,                                                                     // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
    {
        STATIC,                                                                 // Test pattern
        staticRefIn0Case11,                                                     // Input buffer
        staticRefOutCase11,                                                     // Output buffer
        87,                                                                     // inSamples
        18,                                                                     // inChannels
        AUDIOLIB_CALC_STRIDE(87 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(87 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        1.25,                                                                   // threshold
        2.0,                                                                    // endKnee
        AUDIOLIB_FLOAT32,                                                       // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                              // Output data location
        1,                                                                      // number of reps.
        11,                                                                     // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
    {
        STATIC,                                                                  // Test pattern
        staticRefIn0Case12,                                                      // Input buffer
        staticRefOutCase12,                                                      // Output buffer
        290,                                                                     // inSamples
        20,                                                                      // inChannels
        AUDIOLIB_CALC_STRIDE(290 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(290 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        0.9,                                                                     // threshold
        1.0,                                                                     // endKnee
        AUDIOLIB_FLOAT32,                                                        // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        12,                                                                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13))
    {
        STATIC,                                                                  // Test pattern
        staticRefIn0Case13,                                                      // Input buffer
        staticRefOutCase13,                                                      // Output buffer
        400,                                                                     // inSamples
        32,                                                                      // inChannels
        AUDIOLIB_CALC_STRIDE(400 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(410 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        0.8,                                                                     // threshold
        1.0,                                                                     // endKnee
        AUDIOLIB_FLOAT32,                                                        // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        13,                                                                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 14))
    {
        STATIC,                                                                  // Test pattern
        staticRefIn0Case14,                                                      // Input buffer
        staticRefOutCase14,                                                      // Output buffer
        777,                                                                     // inSamples
        45,                                                                      // inChannels
        AUDIOLIB_CALC_STRIDE(777 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(777 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        3.0,                                                                     // threshold
        4.0,                                                                     // endKnee
        AUDIOLIB_FLOAT32,                                                        // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        14,                                                                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 15))
    {
        STATIC,                                                                 // Test pattern
        staticRefIn0Case15,                                                     // Input buffer
        staticRefOutCase15,                                                     // Output buffer
        17,                                                                     // inSamples
        55,                                                                     // inChannels
        AUDIOLIB_CALC_STRIDE(17 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(17 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        0.4,                                                                    // threshold
        1.0,                                                                    // endKnee
        AUDIOLIB_FLOAT32,                                                       // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                              // Output data location
        1,                                                                      // number of reps.
        15,                                                                     // test ID
    },
#endif

};

/*
 *  Sends the test parameter structure and number of tests
 */
void AUDIOLIB_softClip_getTestParams(AUDIOLIB_softClip_testParams_t** params, int32_t* numTests)
{
   *params   = testParams;
   *numTests = sizeof(testParams) / sizeof(AUDIOLIB_softClip_testParams_t);
}
