// Copyright (C) 2026 Texas Instruments Incorporated
//
// SPDX-License-Identifier: Apache-2.0

#include "AUDIOLIB_whiteNoiseGenerator_idat.h"
/* This file is autogenerated */
/* Please do not edit */

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
#include "test_data/staticRefCase1.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
#include "test_data/staticRefCase2.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
#include "test_data/staticRefCase3.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
#include "test_data/staticRefCase4.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
#include "test_data/staticRefCase5.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
#include "test_data/staticRefCase6.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
#include "test_data/staticRefCase7.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
#include "test_data/staticRefCase8.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
#include "test_data/staticRefCase9.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
#include "test_data/staticRefCase10.h"
#endif

static AUDIOLIB_whiteNoiseGenerator_testParams_t testParams[] = {
#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
    {
        STATIC,                    // Test pattern
        staticRefOutCase1,         // Output buffer
        1024,                      // numSamples
        42,                        // seed
        1.0,                       // range
        AUDIOLIB_FLOAT32,          // precision
        AUDIOLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                         // number of reps.
        1,                         // test ID
        10,                        // numExecReps (frames)
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
    {
        STATIC,                    // Test pattern
        staticRefOutCase2,         // Output buffer
        1016,                      // numSamples
        12345,                     // seed
        0.5,                       // range
        AUDIOLIB_FLOAT32,          // precision
        AUDIOLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                         // number of reps.
        2,                         // test ID
        21,                        // numExecReps (frames)
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
    {
        STATIC,                    // Test pattern
        staticRefOutCase3,         // Output buffer
        49,                        // numSamples
        99,                        // seed
        0.75,                      // range
        AUDIOLIB_FLOAT32,          // precision
        AUDIOLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                         // number of reps.
        3,                         // test ID
        10,                        // numExecReps (frames)
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
    {
        STATIC,                    // Test pattern
        staticRefOutCase4,         // Output buffer
        1536,                      // numSamples
        2024,                      // seed
        1.0,                       // range
        AUDIOLIB_FLOAT32,          // precision
        AUDIOLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                         // number of reps.
        4,                         // test ID
        12,                        // numExecReps (frames)
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
    {
        STATIC,                    // Test pattern
        staticRefOutCase5,         // Output buffer
        1152,                      // numSamples
        2024,                      // seed
        1.0,                       // range
        AUDIOLIB_FLOAT32,          // precision
        AUDIOLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                         // number of reps.
        5,                         // test ID
        12,                        // numExecReps (frames)
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
    {
        STATIC,                    // Test pattern
        staticRefOutCase6,         // Output buffer
        666,                       // numSamples
        777,                       // seed
        0.25,                      // range
        AUDIOLIB_FLOAT32,          // precision
        AUDIOLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                         // number of reps.
        6,                         // test ID
        12,                        // numExecReps (frames)
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
    {
        STATIC,                    // Test pattern
        staticRefOutCase7,         // Output buffer
        85,                        // numSamples
        101,                       // seed
        1.0,                       // range
        AUDIOLIB_FLOAT32,          // precision
        AUDIOLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                         // number of reps.
        7,                         // test ID
        12,                        // numExecReps (frames)
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
    {
        STATIC,                    // Test pattern
        staticRefOutCase8,         // Output buffer
        2561,                      // numSamples
        8675309,                   // seed
        0.8,                       // range
        AUDIOLIB_FLOAT32,          // precision
        AUDIOLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                         // number of reps.
        8,                         // test ID
        21,                        // numExecReps (frames)
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
    {
        STATIC,                    // Test pattern
        staticRefOutCase9,         // Output buffer
        4,                         // numSamples
        101,                       // seed
        1.0,                       // range
        AUDIOLIB_FLOAT32,          // precision
        AUDIOLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                         // number of reps.
        9,                         // test ID
        12,                        // numExecReps (frames)
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
    {
        STATIC,                    // Test pattern
        staticRefOutCase10,        // Output buffer
        19,                        // numSamples
        101,                       // seed
        1.0,                       // range
        AUDIOLIB_FLOAT32,          // precision
        AUDIOLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                         // number of reps.
        10,                        // test ID
        12,                        // numExecReps (frames)
    },
#endif

};

/*
 *  Sends the test parameter structure and number of tests
 */
void AUDIOLIB_whiteNoiseGenerator_getTestParams(AUDIOLIB_whiteNoiseGenerator_testParams_t** params, int32_t* numTests)
{
   *params   = testParams;
   *numTests = sizeof(testParams) / sizeof(AUDIOLIB_whiteNoiseGenerator_testParams_t);
}
