# Copyright (C) 2026 Texas Instruments Incorporated
#
# SPDX-License-Identifier: Apache-2.0

from __future__ import print_function

from subprocess import call
from sys import platform

import sys
import os
import numpy as np
import csv

sys.path.append("../common")
import AUDIOLIB_utils
import file_io
import nlms

# dtype mapping for CSV dType values
DTYPE_MAP = {
    "float": np.float32,
    "FLOAT": np.float32,
}


def generate_sine(
    num_samples, sampling_rate, num_frames, channel, frequency, amplitude
):
    """Generate a continuous sine wave for all frames of a given channel."""
    total_samples = int(num_samples) * int(num_frames)
    # exact spacing
    t = np.arange(total_samples, dtype=np.float64) / float(sampling_rate)
    sine_wave = amplitude * np.sin(2.0 * np.pi * frequency * t + channel * np.pi / 4.0)
    return sine_wave


def gen_testCaseParams(idatFile, currPrm):
    """Generate and write test case parameters to idat file."""
    testId = currPrm["ID"]
    dType = currPrm["dType"]
    numSamples = currPrm["numSamples"]
    numChannels = currPrm["numChannels"]
    samplingRate = currPrm["samplingRate"]
    filterLength = currPrm["filterLength"]
    stepSize = currPrm["stepSize"]
    strideIn0 = currPrm["strideInElements"]
    strideOut = currPrm["strideOutElements"]
    testType = currPrm["testType"]
    numExecReps = currPrm["numExecReps"]
    plotSignals = currPrm["plotSignals"]
    waveFiles = currPrm["waveFiles"]
    amplitude = currPrm["amplitude"]
    frequency = currPrm["frequency"]
    outputDataLocation = currPrm["outputDataLocation"]
    numReps = currPrm["numReps"]

    AUDIOLIB_dType = AUDIOLIB_utils.resolve_dType(dType)

    if testType in ["STATIC", "SINE"]:
        testTypeOut = "STATIC"
        in_signal = f"staticRefInCase{testId}"
        desired_signal = f"staticRefDesiredCase{testId}"
        out_signal = f"staticRefOutCase{testId}"
        coefficients = f"staticRefCoeffCase{testId}"
    else:
        testTypeOut = testType
        in_signal = "NULL"
        desired_signal = "NULL"
        out_signal = "NULL"
        coefficients = "NULL"

    idatFile.write("#if (defined(ALL_TEST_CASES) || (TEST_CASE == %d))\n" % int(testId))
    idatFile.write("{\n")
    idatFile.write("%s, // Test Pattern\n" % testTypeOut)
    idatFile.write("%s, // Input Signal\n" % in_signal)
    idatFile.write("%s, // Desired Signal\n" % desired_signal)
    idatFile.write("%s, // Output Signal\n" % out_signal)
    idatFile.write("%s, // Filter Coefficients\n" % coefficients)
    idatFile.write("%s, // Sample Data Type\n" % AUDIOLIB_dType)
    idatFile.write("%d, // Samples per channel\n" % int(numSamples))
    idatFile.write("%d, // Number of Channels\n" % int(numChannels))
    idatFile.write(
        "AUDIOLIB_CALC_STRIDE(%s * sizeof(%s), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0 \n"
        % (strideIn0, dType)
    )
    idatFile.write(
        "AUDIOLIB_CALC_STRIDE(%s * sizeof(%s), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut \n"
        % (strideOut, dType)
    )
    idatFile.write("%d, // Filter Length\n" % int(filterLength))
    idatFile.write("%f, // Step Size\n" % float(stepSize))
    idatFile.write("%s, // Output data location \n" % (outputDataLocation))
    idatFile.write("%d, // number of reps. \n" % (int(numReps)))
    idatFile.write("%d, // Test ID\n" % int(testId))
    idatFile.write("%d, // Number of Executions\n" % int(numExecReps))
    idatFile.write("},\n")
    idatFile.write("#endif\n\n")


def gen_idat_file(idatFile, testCases):
    """Generate the idat file."""
    header_path = os.path.join("..", "common", "ti_lice_header_idat.txt")
    if os.path.exists(header_path):
        with open(header_path, "r") as fIn:
            lines = fIn.readlines()
        idatFile.writelines(lines)
    else:
        idatFile.write(
            "/* autogenerated idat header - original header file missing */\n"
        )

    includeString = '#include "AUDIOLIB_nlms_idat.h"\n'
    idatFile.writelines(includeString)
    idatFile.write("\n")
    idatFile.write("/*This file is autogenerated*/\n")
    idatFile.write("/*Please do not edit*/\n")
    idatFile.write("\n\n")
    for testCase in testCases:
        if testCase["testType"] in ["STATIC", "SINE"]:
            AUDIOLIB_utils.gen_ifdefs(idatFile, testCase)
    idatFile.write("static AUDIOLIB_nlms_testParams_t testParams[] =  ")
    idatFile.write("{\n")
    for testCase in testCases:
        gen_testCaseParams(idatFile, testCase)
    idatFile.write("};\n\n")
    func_path = "test_param_function.txt"
    if os.path.exists(func_path):
        with open(func_path, "r") as fIn:
            lines = fIn.readlines()
        idatFile.writelines(lines)


def process_test_case(testCase):
    """Convert string parameters to appropriate types and add derived fields."""
    # canonicalize fields and types
    testCase["ID"] = testCase.get("ID", testCase.get("testId", "0"))
    testCase["testId"] = int(testCase["ID"])
    testCase["numSamples"] = int(testCase.get("numSamples", 0))
    testCase["numChannels"] = int(testCase.get("numChannels", 1))
    testCase["samplingRate"] = int(testCase.get("samplingRate", 48000))
    testCase["filterLength"] = int(testCase.get("filterLength", 16))
    testCase["stepSize"] = float(testCase.get("stepSize", 0.1))

    # strides (support alternate column names)
    if "strideInElements" in testCase:
        testCase["strideInElements"] = int(testCase["strideInElements"])
    else:
        testCase["strideInElements"] = int(
            testCase.get("strideIn0", testCase["numSamples"])
        )

    if "strideOutElements" in testCase:
        testCase["strideOutElements"] = int(testCase["strideOutElements"])
    else:
        testCase["strideOutElements"] = int(
            testCase.get("strideOut", testCase["numSamples"])
        )

    testCase["numExecReps"] = int(testCase.get("numExecReps", 1))
    testCase["plotSignals"] = (
        str(testCase.get("plotSignals", "FALSE")).upper() == "TRUE"
    )
    testCase["waveFiles"] = str(testCase.get("waveFiles", "FALSE")).upper() == "TRUE"
    testCase["amplitude"] = float(testCase.get("amplitude", 1.0))
    testCase["frequency"] = float(testCase.get("frequency", 2000.0))
    testCase["dType"] = str(testCase.get("dType", "float")).lower()
    if testCase["dType"] not in ("float", "double"):
        testCase["dType"] = "float"
    testCase["dtype_np"] = DTYPE_MAP[testCase["dType"]]
    testCase["outputDataLocation"] = testCase.get("outputDataLocation", "INTERNAL")
    testCase["numReps"] = int(testCase.get("numReps", testCase["numExecReps"]))
    testCase["testType"] = str(testCase.get("testType", "STATIC")).upper()
    return testCase


def gen_test_case_header_file(testCase):
    testId = testCase["ID"]
    numSamples = testCase["numSamples"]
    numChannels = testCase["numChannels"]
    samplingRate = testCase["samplingRate"]
    filterLength = testCase["filterLength"]
    stepSize = testCase["stepSize"]
    testType = testCase["testType"]
    numExecReps = testCase["numExecReps"]
    plotSignals = testCase["plotSignals"]
    waveFiles = testCase["waveFiles"]
    amplitude = testCase["amplitude"]
    frequency = testCase["frequency"]
    dtype_np = testCase["dtype_np"]

    frames = int(numExecReps)
    samplesPerFrame = int(numSamples) * int(numChannels)

    # Always use 2D shape: (frames, samplesPerFrame)
    pInSignal = np.zeros((frames, samplesPerFrame), dtype=dtype_np)
    pDesiredSignal = np.zeros((frames, samplesPerFrame), dtype=dtype_np)
    pOutSignal = np.zeros((frames, samplesPerFrame), dtype=dtype_np)
    pCoefficients = np.zeros((numChannels, filterLength), dtype=dtype_np)

    # Generate input and desired signals
    for frame in range(frames):
        for sample_idx in range(numSamples):
            for ch in range(numChannels):
                idx = ch * numSamples + sample_idx

                if testType == "STATIC":
                    clean_val = np.random.uniform(-1.0, 1.0)
                elif testType == "SINE":
                    full_sine = generate_sine(
                        numSamples, samplingRate, frames, ch, frequency, amplitude
                    )
                    clean_val = full_sine[frame * numSamples + sample_idx]
                else:
                    clean_val = 0.0

                pDesiredSignal[frame, idx] = dtype_np(clean_val)
                noise = np.random.normal(0.0, 0.3)
                pInSignal[frame, idx] = dtype_np(clean_val + noise)

    for ch in range(numChannels):
        startIdx = ch * numSamples
        endIdx = (ch + 1) * numSamples
        in_ch = pInSignal[:, startIdx:endIdx].flatten()
        desired_ch = pDesiredSignal[:, startIdx:endIdx].flatten()
        out_ch, final_coeffs = nlms.nlms_filter(
            in_ch, desired_ch, filterLength, stepSize, numSamples
        )
        pOutSignal[:, startIdx:endIdx] = out_ch.reshape(frames, numSamples)
        pCoefficients[ch, :] = final_coeffs

    # Plot and write files
    if plotSignals:
        file_io.plot_signal_pair(
            pInSignal,
            pDesiredSignal,
            numSamples,
            numChannels,
            numExecReps,
            testId,
            "input_desired",
            channel=0,
            test_type=testType,
        )
        file_io.plot_signal_pair(
            pOutSignal,
            pDesiredSignal,
            numSamples,
            numChannels,
            numExecReps,
            testId,
            "output_desired",
            channel=0,
            test_type=testType,
        )

    if waveFiles:
        file_io.write_wav_files(
            pInSignal,
            pDesiredSignal,
            pOutSignal,
            pOutSignal,
            np.zeros_like(pInSignal),
            np.zeros_like(pInSignal),
            testCase,
            numExecReps,
        )

    # Flatten for header file
    in_list = pInSignal.flatten().tolist()
    desired_list = pDesiredSignal.flatten().tolist()
    out_list = pOutSignal.flatten().tolist()
    coeff_list = pCoefficients.flatten().tolist()

    headerFileName = f"staticRefCase{testId}.h"
    file_io.write_header_file(
        in_list,
        desired_list,
        out_list,
        coeff_list,
        testCase,
        headerFileName,
        numExecReps,
    )

    return [float(np.min(out_list)), float(np.max(out_list))]


# CSV file with parameters for all test cases
testCasesCsvFile = "../AUDIOLIB_nlms/test_cases_list.csv"
testIdList = list(range(0, 100))

myArgs = AUDIOLIB_utils.getCmdLineArgs()


def gen_test_case(testCase):
    if testCase["testType"] in ["STATIC", "SINE"]:
        [minY, maxY] = gen_test_case_header_file(testCase)
        print(
            f"Test case generation completed for test ID {testCase['ID']} w/ min: {minY} and max {maxY}"
        )
    else:
        print(
            f"Skipping test case generation for test ID {testCase['ID']} as testType is not supported"
        )


# --- main flow ---
if not os.path.exists(testCasesCsvFile):
    raise FileNotFoundError(f"Test cases CSV not found: {testCasesCsvFile}")

with open(testCasesCsvFile, encoding="utf-8-sig") as csv_file:
    testCaseReader = csv.DictReader(csv_file)
    testCases = list(testCaseReader)
    # preprocess list entries
    for i, testCase in enumerate(testCases):
        testCases[i] = process_test_case(testCase)
    for testCase in testCases:
        if myArgs.allCases or int(testCase["ID"]) in testIdList:
            gen_test_case(testCase)

idatFileName = "../../AUDIOLIB_nlms/AUDIOLIB_nlms_idat.c"
with open(idatFileName, "w") as idatFile:
    gen_idat_file(idatFile, testCases)

if platform == "linux" or platform == "linux2":
    try:
        call(["clang-format", "-style=file", "-i", idatFileName])
    except Exception:
        pass
    try:
        call(["indent", "-nut", "-i3", "-c55", "-l200", idatFileName])
        call(["rm", idatFileName + "~"])
    except Exception:
        pass

print("\nIdat file generation completed")
