// Copyright (C) 2026 Texas Instruments Incorporated
//
// SPDX-License-Identifier: Apache-2.0
#include "AUDIOLIB_mute_idat.h"
/*This file is autogenerated*/
/*Please do not edit*/

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
#include "test_data/staticRefCase1.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
#include "test_data/staticRefCase2.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
#include "test_data/staticRefCase3.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
#include "test_data/staticRefCase4.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
#include "test_data/staticRefCase5.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
#include "test_data/staticRefCase6.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
#include "test_data/staticRefCase7.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
#include "test_data/staticRefCase8.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
#include "test_data/staticRefCase9.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
#include "test_data/staticRefCase10.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
#include "test_data/staticRefCase11.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
#include "test_data/staticRefCase12.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13))
#include "test_data/staticRefCase13.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 14))
#include "test_data/staticRefCase14.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 15))
#include "test_data/staticRefCase15.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 16))
#include "test_data/staticRefCase16.h"
#endif

static AUDIOLIB_mute_testParams_t testParams[] = {
#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
    {
        STATIC,            // Test Pattern
        staticRefInCase1,  // staticIn
        staticRefOutCase1, // staticOut
        AUDIOLIB_FLOAT32,  // Sample Data Type
        20,                // Samples per channel
        256,               // Number of Channels
        1,                 // isMuted
        48000,             // Sampling Rate
        10.0,              // fadeTime
        1,                 // isInterleaved
        0,                 // fadeType (0=LINEAR, 1=SMOOTH, 2=HARD)
        AUDIOLIB_CALC_STRIDE(256 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideInElements
        AUDIOLIB_CALC_STRIDE(256 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOutElements
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                          // Output data location
        1,                                                                                  // number of reps.
        1,                                                                                  // test ID
        4,                                                                                  // numExecReps
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
    {
        STATIC,            // Test Pattern
        staticRefInCase2,  // staticIn
        staticRefOutCase2, // staticOut
        AUDIOLIB_FLOAT32,  // Sample Data Type
        128,               // Samples per channel
        63,                // Number of Channels
        0,                 // isMuted
        48000,             // Sampling Rate
        2.0,               // fadeTime
        0,                 // isInterleaved
        0,                 // fadeType (0=LINEAR, 1=SMOOTH, 2=HARD)
        AUDIOLIB_CALC_STRIDE(128 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideInElements
        AUDIOLIB_CALC_STRIDE(128 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOutElements
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                          // Output data location
        1,                                                                                  // number of reps.
        2,                                                                                  // test ID
        4,                                                                                  // numExecReps
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
    {
        STATIC,            // Test Pattern
        staticRefInCase3,  // staticIn
        staticRefOutCase3, // staticOut
        AUDIOLIB_FLOAT32,  // Sample Data Type
        24,                // Samples per channel
        137,               // Number of Channels
        0,                 // isMuted
        48000,             // Sampling Rate
        0.0,               // fadeTime
        1,                 // isInterleaved
        1,                 // fadeType (0=LINEAR, 1=SMOOTH, 2=HARD)
        AUDIOLIB_CALC_STRIDE(256 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideInElements
        AUDIOLIB_CALC_STRIDE(256 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOutElements
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                          // Output data location
        1,                                                                                  // number of reps.
        3,                                                                                  // test ID
        4,                                                                                  // numExecReps
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
    {
        STATIC,            // Test Pattern
        staticRefInCase4,  // staticIn
        staticRefOutCase4, // staticOut
        AUDIOLIB_FLOAT32,  // Sample Data Type
        128,               // Samples per channel
        1,                 // Number of Channels
        0,                 // isMuted
        48000,             // Sampling Rate
        1.0,               // fadeTime
        1,                 // isInterleaved
        0,                 // fadeType (0=LINEAR, 1=SMOOTH, 2=HARD)
        AUDIOLIB_CALC_STRIDE(1 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideInElements
        AUDIOLIB_CALC_STRIDE(1 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOutElements
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                        // Output data location
        1,                                                                                // number of reps.
        4,                                                                                // test ID
        12,                                                                               // numExecReps
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
    {
        STATIC,            // Test Pattern
        staticRefInCase5,  // staticIn
        staticRefOutCase5, // staticOut
        AUDIOLIB_FLOAT32,  // Sample Data Type
        64,                // Samples per channel
        64,                // Number of Channels
        1,                 // isMuted
        48000,             // Sampling Rate
        5.5,               // fadeTime
        0,                 // isInterleaved
        0,                 // fadeType (0=LINEAR, 1=SMOOTH, 2=HARD)
        AUDIOLIB_CALC_STRIDE(64 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideInElements
        AUDIOLIB_CALC_STRIDE(64 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOutElements
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                         // Output data location
        1,                                                                                 // number of reps.
        5,                                                                                 // test ID
        4,                                                                                 // numExecReps
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
    {
        STATIC,            // Test Pattern
        staticRefInCase6,  // staticIn
        staticRefOutCase6, // staticOut
        AUDIOLIB_FLOAT32,  // Sample Data Type
        64,                // Samples per channel
        64,                // Number of Channels
        1,                 // isMuted
        48000,             // Sampling Rate
        0.0,               // fadeTime
        1,                 // isInterleaved
        2,                 // fadeType (0=LINEAR, 1=SMOOTH, 2=HARD)
        AUDIOLIB_CALC_STRIDE(64 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideInElements
        AUDIOLIB_CALC_STRIDE(64 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOutElements
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                         // Output data location
        1,                                                                                 // number of reps.
        6,                                                                                 // test ID
        4,                                                                                 // numExecReps
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
    {
        STATIC,            // Test Pattern
        staticRefInCase7,  // staticIn
        staticRefOutCase7, // staticOut
        AUDIOLIB_FLOAT32,  // Sample Data Type
        128,               // Samples per channel
        16,                // Number of Channels
        0,                 // isMuted
        48000,             // Sampling Rate
        0.0,               // fadeTime
        0,                 // isInterleaved
        2,                 // fadeType (0=LINEAR, 1=SMOOTH, 2=HARD)
        AUDIOLIB_CALC_STRIDE(128 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideInElements
        AUDIOLIB_CALC_STRIDE(128 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOutElements
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                          // Output data location
        1,                                                                                  // number of reps.
        7,                                                                                  // test ID
        7,                                                                                  // numExecReps
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
    {
        STATIC,            // Test Pattern
        staticRefInCase8,  // staticIn
        staticRefOutCase8, // staticOut
        AUDIOLIB_FLOAT32,  // Sample Data Type
        128,               // Samples per channel
        32,                // Number of Channels
        0,                 // isMuted
        48000,             // Sampling Rate
        0.0,               // fadeTime
        1,                 // isInterleaved
        2,                 // fadeType (0=LINEAR, 1=SMOOTH, 2=HARD)
        AUDIOLIB_CALC_STRIDE(128 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideInElements
        AUDIOLIB_CALC_STRIDE(128 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOutElements
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                          // Output data location
        1,                                                                                  // number of reps.
        8,                                                                                  // test ID
        4,                                                                                  // numExecReps
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
    {
        STATIC,            // Test Pattern
        staticRefInCase9,  // staticIn
        staticRefOutCase9, // staticOut
        AUDIOLIB_FLOAT32,  // Sample Data Type
        128,               // Samples per channel
        20,                // Number of Channels
        1,                 // isMuted
        48000,             // Sampling Rate
        0.0,               // fadeTime
        0,                 // isInterleaved
        0,                 // fadeType (0=LINEAR, 1=SMOOTH, 2=HARD)
        AUDIOLIB_CALC_STRIDE(128 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideInElements
        AUDIOLIB_CALC_STRIDE(128 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOutElements
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                          // Output data location
        1,                                                                                  // number of reps.
        9,                                                                                  // test ID
        7,                                                                                  // numExecReps
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
    {
        STATIC,             // Test Pattern
        staticRefInCase10,  // staticIn
        staticRefOutCase10, // staticOut
        AUDIOLIB_FLOAT32,   // Sample Data Type
        128,                // Samples per channel
        128,                // Number of Channels
        0,                  // isMuted
        48000,              // Sampling Rate
        0.0,                // fadeTime
        0,                  // isInterleaved
        0,                  // fadeType (0=LINEAR, 1=SMOOTH, 2=HARD)
        AUDIOLIB_CALC_STRIDE(128 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideInElements
        AUDIOLIB_CALC_STRIDE(128 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOutElements
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                          // Output data location
        1,                                                                                  // number of reps.
        10,                                                                                 // test ID
        4,                                                                                  // numExecReps
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
    {
        STATIC,             // Test Pattern
        staticRefInCase11,  // staticIn
        staticRefOutCase11, // staticOut
        AUDIOLIB_FLOAT32,   // Sample Data Type
        256,                // Samples per channel
        64,                 // Number of Channels
        0,                  // isMuted
        48000,              // Sampling Rate
        10.0,               // fadeTime
        0,                  // isInterleaved
        1,                  // fadeType (0=LINEAR, 1=SMOOTH, 2=HARD)
        AUDIOLIB_CALC_STRIDE(256 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideInElements
        AUDIOLIB_CALC_STRIDE(256 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOutElements
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                          // Output data location
        1,                                                                                  // number of reps.
        11,                                                                                 // test ID
        4,                                                                                  // numExecReps
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
    {
        STATIC,             // Test Pattern
        staticRefInCase12,  // staticIn
        staticRefOutCase12, // staticOut
        AUDIOLIB_FLOAT32,   // Sample Data Type
        256,                // Samples per channel
        10,                 // Number of Channels
        1,                  // isMuted
        48000,              // Sampling Rate
        0.0,                // fadeTime
        0,                  // isInterleaved
        1,                  // fadeType (0=LINEAR, 1=SMOOTH, 2=HARD)
        AUDIOLIB_CALC_STRIDE(256 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideInElements
        AUDIOLIB_CALC_STRIDE(256 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOutElements
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                          // Output data location
        1,                                                                                  // number of reps.
        12,                                                                                 // test ID
        7,                                                                                  // numExecReps
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13))
    {
        STATIC,             // Test Pattern
        staticRefInCase13,  // staticIn
        staticRefOutCase13, // staticOut
        AUDIOLIB_FLOAT32,   // Sample Data Type
        64,                 // Samples per channel
        64,                 // Number of Channels
        0,                  // isMuted
        48000,              // Sampling Rate
        2.0,                // fadeTime
        1,                  // isInterleaved
        2,                  // fadeType (0=LINEAR, 1=SMOOTH, 2=HARD)
        AUDIOLIB_CALC_STRIDE(64 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideInElements
        AUDIOLIB_CALC_STRIDE(64 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOutElements
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                         // Output data location
        1,                                                                                 // number of reps.
        13,                                                                                // test ID
        4,                                                                                 // numExecReps
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 14))
    {
        STATIC,             // Test Pattern
        staticRefInCase14,  // staticIn
        staticRefOutCase14, // staticOut
        AUDIOLIB_FLOAT32,   // Sample Data Type
        27,                 // Samples per channel
        128,                // Number of Channels
        1,                  // isMuted
        48000,              // Sampling Rate
        5.5,                // fadeTime
        0,                  // isInterleaved
        0,                  // fadeType (0=LINEAR, 1=SMOOTH, 2=HARD)
        AUDIOLIB_CALC_STRIDE(27 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideInElements
        AUDIOLIB_CALC_STRIDE(27 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOutElements
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                         // Output data location
        1,                                                                                 // number of reps.
        14,                                                                                // test ID
        6,                                                                                 // numExecReps
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 15))
    {
        STATIC,             // Test Pattern
        staticRefInCase15,  // staticIn
        staticRefOutCase15, // staticOut
        AUDIOLIB_FLOAT32,   // Sample Data Type
        17,                 // Samples per channel
        128,                // Number of Channels
        1,                  // isMuted
        48000,              // Sampling Rate
        5.5,                // fadeTime
        0,                  // isInterleaved
        1,                  // fadeType (0=LINEAR, 1=SMOOTH, 2=HARD)
        AUDIOLIB_CALC_STRIDE(17 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideInElements
        AUDIOLIB_CALC_STRIDE(17 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOutElements
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                         // Output data location
        1,                                                                                 // number of reps.
        15,                                                                                // test ID
        6,                                                                                 // numExecReps
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 16))
    {
        STATIC,             // Test Pattern
        staticRefInCase16,  // staticIn
        staticRefOutCase16, // staticOut
        AUDIOLIB_FLOAT32,   // Sample Data Type
        24,                 // Samples per channel
        137,                // Number of Channels
        0,                  // isMuted
        48000,              // Sampling Rate
        0.5,                // fadeTime
        1,                  // isInterleaved
        1,                  // fadeType (0=LINEAR, 1=SMOOTH, 2=HARD)
        AUDIOLIB_CALC_STRIDE(256 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideInElements
        AUDIOLIB_CALC_STRIDE(256 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOutElements
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                          // Output data location
        1,                                                                                  // number of reps.
        16,                                                                                 // test ID
        4,                                                                                  // numExecReps
    },
#endif

};

/*
 *  Sends the test parameter structure and number of tests
 */
void AUDIOLIB_mute_getTestParams(AUDIOLIB_mute_testParams_t** params, int32_t* numTests)
{
   *params   = testParams;
   *numTests = sizeof(testParams) / sizeof(AUDIOLIB_mute_testParams_t);
}
