# Copyright (C) 2026 Texas Instruments Incorporated
#
# SPDX-License-Identifier: Apache-2.0

from __future__ import print_function
from subprocess import call
from sys import platform

import sys
import numpy as np
import csv
import re

sys.path.append("../common")
import AUDIOLIB_utils
import file_io
import os
import matplotlib.pyplot as plt

from process import fader


def gen_testCaseParams(testParamsFile, currPrm):
    """Generate and write test case parameters to idat file

    Args:
        param1 (file object): Input file object to idat.c file
        param2 (dict object): Dict object with test case parameter

    """

    testId = currPrm["ID"]
    dType = currPrm["dType"]
    numSamples = currPrm["numSamples"]
    numChannels = currPrm["numChannels"]
    strideInElements = currPrm["strideInElements"]
    strideOutElements = currPrm["strideOutElements"]
    testType = currPrm["testType"]
    demoCase = currPrm["demoCase"]
    outputDataLocation = currPrm["outputDataLocation"]
    numReps = currPrm["numReps"]
    C7100 = currPrm["C7100"]
    isInterleave = currPrm["isInterleave"]
    AUDIOLIB_dType = AUDIOLIB_utils.resolve_dType(dType)

    if testType in ["STATIC"]:
        in0 = "staticRefIn0Case" + testId
        in1 = "staticRefIn1Case" + testId
        in2 = "staticRefIn2Case" + testId
        in3 = "staticRefIn3Case" + testId
        out = "staticRefOutCase" + testId
        testType = "STATIC"

    if C7100 == "FALSE":
        testParamsFile.write("#if !defined(__C7100__)\n")

    if demoCase == "true":
        testParamsFile.write(
            "#if (defined(ALL_TEST_CASES) || (TEST_CASE == %d) || defined(DEMO_CASE))\n"
            % (int(testId))
        )
    else:
        testParamsFile.write(
            "#if (defined(ALL_TEST_CASES) || (TEST_CASE == %d))\n" % (int(testId))
        )

    idatFile.write("{\n")
    idatFile.write("%s, // Test Pattern \n" % (testType))
    idatFile.write("%s, // in0 \n" % (in0))
    idatFile.write("%s, // in1 \n" % (in1))
    idatFile.write("%s, // in2 \n" % (in2))
    idatFile.write("%s, // in3 \n" % (in3))
    idatFile.write("%s, // out \n" % (out))
    idatFile.write("%s, // Sample Data Type \n" % (AUDIOLIB_dType))
    idatFile.write("%d, // Samples per channel \n" % (numSamples))
    idatFile.write("%d, // Number of Channels \n" % (numChannels))
    idatFile.write("%s, // isInterleave \n" % (isInterleave))
    idatFile.write("%s , // strideInElements \n" % ((strideInElements)))
    idatFile.write("%s , // strideOutElements \n" % ((strideOutElements)))
    idatFile.write("%s, // Output data location \n" % (outputDataLocation))
    idatFile.write("%d, // number of reps. \n" % (int(numReps)))
    idatFile.write("%d, // test ID\n" % int(testId))
    idatFile.write("},\n")
    idatFile.write("#endif\n")

    if C7100 == "FALSE":
        testParamsFile.write("#endif // if !defined(__C7100__)\n")

    idatFile.write("\n\n")


def gen_idat_file(idatFile, testCases):
    """Generate the idat file

    Args:
        param1 (file object): Input file object to idat.c file
        param2 (dict object): Dict object with test case parameter

    """

    fIn = open("../common/ti_lice_header_idat.txt", "r")
    lines = fIn.readlines()
    fIn.close()
    idatFile.writelines(lines)
    includeString = '#include "AUDIOLIB_crossfade_idat.h"'
    idatFile.writelines(includeString)
    idatFile.write("\n")
    idatFile.write("/*This file is autogenerated*/\n")
    idatFile.write("/*Please do not edit*/\n")
    idatFile.write("\n\n")
    # generate ifdefs for header files
    for testCase in testCases:
        if testCase["testType"] in ["STATIC", "SINE"]:
            AUDIOLIB_utils.gen_ifdefs(idatFile, testCase)

    # generate parameters for test cases
    idatFile.write("static AUDIOLIB_crossfade_testParams_t testParams[] =  ")
    idatFile.write("{\n")

    for testCase in testCases:
        gen_testCaseParams(idatFile, testCase)

    idatFile.write("};\n\n")
    fIn = open("test_param_function.txt", "r")
    lines = fIn.readlines()

    idatFile.writelines(lines)


def process_test_case(testCase):
    """Convert str to int for necessary parameters

    Args:
        Param1(:obj: dict) : Dictionary object with test case parameters

    Returns:
        Obj: Dictionary object with necessary parameters converted to int

    """

    # print(testCase.keys())
    testCase["testId"] = int(testCase["ID"])
    testCase["numSamples"] = int(testCase["numSamples"])
    testCase["numChannels"] = int(testCase["numChannels"])
    testCase["strideInElements"] = int(testCase["strideInElements"])
    testCase["strideOutElements"] = int(testCase["strideOutElements"])
    testCase["isInterleave"] = int(testCase["isInterleave"])

    # convert str to int for necessary parameters

    return testCase


def gen_test_case_header_file(testCase):
    """Generate test case and write out input, filter, and output tensor
    into a header file usable in C/C++ code.

    Args:
        param1 (:obj: dict): A dict object with all the test case
        parameters

    Returns:
        [int int]: Minimum and maximum value in output feature tensor

    """

    ##############################
    # Get test parameter of case #
    ##############################

    testId = testCase["ID"]
    numSamples = testCase["numSamples"]
    numChannels = testCase["numChannels"]
    isInteleave = testCase["isInterleave"]
    totalSamplesPerChannel = numSamples

    [minVal, maxVal] = [-10, 10]

    i = np.arange(totalSamplesPerChannel)

    if totalSamplesPerChannel == 1:
        fade_out = np.array([1.0])
        fade_in = np.array([0.0])
    else:
        i = np.arange(totalSamplesPerChannel)
        fade_out = np.cos(i * np.pi / (2 * (totalSamplesPerChannel - 1)))
        fade_in = np.sin(i * np.pi / (2 * (totalSamplesPerChannel - 1)))

    if isInteleave:
        in0 = np.random.uniform(low=minVal, high=maxVal, size=(numSamples, numChannels))
        in1 = np.random.uniform(low=minVal, high=maxVal, size=(numSamples, numChannels))

        fade_out_3d = fade_out[:, None]  # shape: (numSamples, 1)
        fade_in_3d = fade_in[:, None]  # shape: (numSamples, 1)

    else:
        in0 = np.random.uniform(low=minVal, high=maxVal, size=(numChannels, numSamples))
        in1 = np.random.uniform(low=minVal, high=maxVal, size=(numChannels, numSamples))

        fade_out_3d = fade_out[None, :]  # shape becomes ( 1, numSamples)
        fade_in_3d = fade_in[None, :]  # shape becomes ( 1, numSamples)

    out = fader(in0=in0, in1=in1, fadeIn=fade_in_3d, fadeOut=fade_out_3d)

    headerFileName = "staticRefCase" + str(testId) + ".h"
    file_io.write_header_file(
        in0=in0,
        in1=in1,
        in2=fade_out,
        in3=fade_in,
        out=out,
        testCase=testCase,
        headerFileName=headerFileName,
    )

    min_output = np.min(out)
    max_output = np.max(out)
    return [min_output, max_output]


testCasesCsvFile = "../AUDIOLIB_crossfade/test_cases_list.csv"
testIdList = []  # list of test IDs that we want to generate test data
testIdList += range(0, 100)
# testIdList = [18]

myArgs = AUDIOLIB_utils.getCmdLineArgs()


def gen_test_case(testCase):
    if testCase["testType"] in ["STATIC", "SINE"]:
        [minY, maxY] = gen_test_case_header_file(testCase)
        print(
            "Test case generation completed for test ID",
            testCase["ID"],
            "w/ min:",
            minY,
            "and max",
            maxY,
        )
    else:
        print(
            "Skipping test case generation for test ID",
            testCase["ID"],
            "as tesType is RANDOM",
        )


#############################################################################
# Open CSV file with test cases and generate header file with test data for #
# test cases of interest; based on testIdList                               #
#############################################################################

with open(testCasesCsvFile, encoding="utf-8-sig") as csv_file:
    testCaseReader = csv.DictReader(csv_file)
    testCases = list(testCaseReader)

    for testCase in testCases:
        testCase = process_test_case(testCase)

    for testCase in testCases:
        if myArgs.allCases == True:
            gen_test_case(testCase)
        elif int(testCase["ID"]) in testIdList:
            gen_test_case(testCase)


idatFileName = "../../AUDIOLIB_crossfade/AUDIOLIB_crossfade_idat.c"


##########################################################################
# Generate idat.cpp file by parsing all the test cases in the CSV file # #
##########################################################################


with open(idatFileName, "w") as idatFile:
    gen_idat_file(idatFile, testCases)


if platform == "linux" or platform == "linux2":
    call(["clang-format", "-style=file", "-i", idatFileName])
    call(["indent", "-nut", "-i3", "-c55", "-l200", idatFileName])
    call(["rm", idatFileName + "~"])  # remove backup file


print("Idat file generation completed")
