# Copyright (C) 2026 Texas Instruments Incorporated
#
# SPDX-License-Identifier: Apache-2.0

from __future__ import print_function
from subprocess import call
from sys import platform

import sys
import numpy as np
import csv
import os

sys.path.append("../common")
import file_io
import AUDIOLIB_utils
from subBlockStatistics import AUDIOLIB_subBlockStatistics


def gen_testCaseParams(testParamsFile, currPrm):
    """Generate and write test case parameters to idat file

    Args:
        param1 (file object): Input file object to idat.c file
        param2 (dict object): Dict object with test case parameter

    """

    testId = currPrm["ID"]
    dType = currPrm["sampleDataType"]
    inChannels = currPrm["numChannels"]
    inSamples = currPrm["inputBlockSize"]
    subBlockSize = currPrm["subBlockSize"]
    strideIn = currPrm["strideIn"]
    strideOut = currPrm["strideOut"]
    statisticsType = currPrm["statisticsType"]
    flagPerChanStats = currPrm["flagPerChanStats"]
    testType = currPrm["testType"]
    demoCase = currPrm["demoCase"]
    outputDataLocation = currPrm["outputDataLocation"]
    numReps = currPrm["numReps"]
    C7100 = currPrm["C7100"]

    if testType == "STATIC":
        in0 = "staticRefInCase" + testId
        out = "staticRefOutCase" + testId
    else:
        in0 = "NULL"
        out = "NULL"

    if C7100 == "FALSE":
        testParamsFile.write("#if !defined(__C7100__)\n")

    if demoCase == "true":
        testParamsFile.write(
            "#if (defined(ALL_TEST_CASES) || (TEST_CASE == %d) || defined(DEMO_CASE))\n"
            % (int(testId))
        )
    else:
        testParamsFile.write(
            "#if (defined(ALL_TEST_CASES) || (TEST_CASE == %d))\n" % (int(testId))
        )

    idatFile.write("{\n")
    idatFile.write("%s, // Test pattern \n" % ((testType)))
    idatFile.write("%s, // Input buffer\n" % ((in0)))
    idatFile.write("%s, // Output buffer \n" % ((out)))
    idatFile.write("%s, // inputBlockSize \n" % ((inSamples)))
    idatFile.write("%s, // subBlockSize \n" % ((subBlockSize)))
    idatFile.write("%s, // numChannels \n" % ((inChannels)))
    idatFile.write("%s, // statisticsType \n" % ((statisticsType)))
    idatFile.write("%d, // flagPerChanStats \n" % (1 if flagPerChanStats else 0))
    idatFile.write(
        "AUDIOLIB_CALC_STRIDE(%s * sizeof(%s), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn \n"
        % ((strideIn), (dType))
    )
    idatFile.write(
        "AUDIOLIB_CALC_STRIDE(%s * sizeof(%s), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut \n"
        % ((strideOut), (dType))
    )
    idatFile.write("%s, // precision \n" % ((AUDIOLIB_utils.resolve_dType(dType))))
    idatFile.write("%s, // Output data location \n" % (outputDataLocation))
    idatFile.write("%d, // number of reps. \n" % (int(numReps)))
    idatFile.write("%d, // test ID\n" % int(testId))
    idatFile.write("},\n")
    idatFile.write("#endif\n")

    if C7100 == "FALSE":
        testParamsFile.write("#endif // if !defined(__C7100__)\n")

    idatFile.write("\n\n")


def gen_idat_file(idatFile, testCases):
    """Generate the idat file

    Args:
        param1 (file object): Input file object to idat.c file
        param2 (dict object): Dict object with test case parameter

    """

    fIn = open("../common/ti_lice_header_idat.txt", "r")
    lines = fIn.readlines()
    fIn.close()
    idatFile.writelines(lines)
    includeString = '#include "AUDIOLIB_subBlockStatistics_idat.h"'
    idatFile.writelines(includeString)
    idatFile.write("\n")
    idatFile.write("/*This file is autogenerated*/\n")
    idatFile.write("/*Please do not edit*/\n")
    idatFile.write("\n\n")
    # generate ifdefs for header files
    for testCase in testCases:
        if testCase["testType"] == "STATIC":
            AUDIOLIB_utils.gen_ifdefs(idatFile, testCase)

    # generate parameters for test cases
    idatFile.write("static AUDIOLIB_subBlockStatistics_testParams_t testParams[] =  ")
    idatFile.write("{\n")

    for testCase in testCases:
        gen_testCaseParams(idatFile, testCase)

    idatFile.write("};\n\n")
    fIn = open("test_param_function.txt", "r")
    lines = fIn.readlines()

    idatFile.writelines(lines)


def process_test_case(testCase):
    """Convert string parameters to appropriate types.

    Args:
        testCase (dict): Dictionary with test case parameters.

    Returns:
        dict: Updated dictionary with converted parameters.
    """
    testCase["testId"] = int(testCase["ID"])
    testCase["sampleDataType"] = testCase["sampleDataType"]
    testCase["inputBlockSize"] = int(testCase["inputBlockSize"])
    testCase["subBlockSize"] = int(testCase["subBlockSize"])
    testCase["numChannels"] = int(testCase["numChannels"])
    testCase["strideIn"] = int(testCase["strideIn"])
    testCase["statisticsType"] = int(testCase["statisticsType"])
    testCase["testType"] = testCase["testType"]
    testCase["flagPerChanStats"] = testCase["flagPerChanStats"].upper() == "TRUE"
    return testCase


def gen_test_case_header_file(testCase):
    """Generate input/output data and write to a header file.

    Args:
        testCase (dict): Dictionary with test case parameters.

    Returns:
        list: [min_output, max_output] of the output signal.
    """
    testId = testCase["testId"]
    inputBlockSize = testCase["inputBlockSize"]
    subBlockSize = testCase["subBlockSize"]
    numChannels = testCase["numChannels"]
    statisticsType = testCase["statisticsType"]
    testType = testCase["testType"]
    flagPerChanStats = testCase["flagPerChanStats"]
    dataType = testCase["sampleDataType"]

    # Create an instance of AUDIOLIB_subBlockStatistics
    subBlockStats_processor = AUDIOLIB_subBlockStatistics(
        sampleDataType=dataType,
        numChannels=numChannels,
        inputBlockSize=inputBlockSize,
        subBlockSize=subBlockSize,
        statisticsType=statisticsType,
        flagPerChanStats=flagPerChanStats,
    )

    # Calculate output block size and output channels
    outputBlockSize = inputBlockSize // subBlockSize
    outputNumChannels = numChannels if flagPerChanStats else 1
    totalInputSamples = inputBlockSize * numChannels
    totalOutputSamples = outputBlockSize * outputNumChannels

    # Generate input signal in planar format [ch0_samples, ch1_samples, ...]
    if dataType == "double":
        inputSignal = np.zeros(totalInputSamples, dtype=np.float64)
    else:
        inputSignal = np.zeros(totalInputSamples, dtype=np.float32)

    for ch in range(numChannels):
        startIdx = ch * inputBlockSize
        if dataType == "double":
            inputSignal[startIdx : startIdx + inputBlockSize] = np.random.uniform(
                low=-1.0, high=1.0, size=inputBlockSize
            ).astype(np.float64)
        else:
            inputSignal[startIdx : startIdx + inputBlockSize] = np.random.uniform(
                low=-1.0, high=1.0, size=inputBlockSize
            ).astype(np.float32)

    inputSignalFlat = inputSignal  # Already flat

    # Execute the subBlockStatistics algorithm using the class
    outputSignal = subBlockStats_processor.exec(inputSignalFlat)

    # Write header file
    headerFileName = f"staticRefCase{testId}.h"
    file_io.write_header_file(
        inputSignalFlat.tolist(),
        outputSignal.tolist(),
        testCase,
        headerFileName,
        outputBlockSize,
        outputNumChannels,
    )

    # Return min and max of output
    min_output = np.min(outputSignal) if outputSignal.size > 0 else 0.0
    max_output = np.max(outputSignal) if outputSignal.size > 0 else 0.0
    return [min_output, max_output]


# Main processing
testCasesCsvFile = "../AUDIOLIB_subBlockStatistics/test_cases_list.csv"
testIdList = list(range(1, 200))


def gen_test_case(testCase):
    if testCase["testType"] == "STATIC":
        [min_output, max_output] = gen_test_case_header_file(testCase)
        print(
            f"Test case generation completed for test ID {testCase['testId']}, "
            f"min: {min_output}, max: {max_output}"
        )
    else:
        print(
            f"Skipping test case generation for test ID {testCase['testId']}, "
            f"testType is not supported"
        )


with open(testCasesCsvFile, encoding="utf-8-sig") as csv_file:
    testCaseReader = csv.DictReader(csv_file)
    testCases = list(testCaseReader)

    for testCase in testCases:
        testCase = process_test_case(testCase)

    for testCase in testCases:
        if testCase["testId"] in testIdList:
            gen_test_case(testCase)

print("Test data generation completed")

idatFileName = "../../AUDIOLIB_subBlockStatistics/AUDIOLIB_subBlockStatistics_idat.c"

##########################################################################
# Generate idat.cpp file by parsing all the test cases in the CSV file # #
##########################################################################


with open(idatFileName, "w") as idatFile:
    gen_idat_file(idatFile, testCases)


if platform == "linux" or platform == "linux2":
    call(["clang-format", "-style=file", "-i", idatFileName])
    call(["indent", "-nut", "-i3", "-c55", "-l200", idatFileName])
    call(["rm", idatFileName + "~"])  # remove backup file


print("Idat file generation completed")
