// Copyright (C) 2026 Texas Instruments Incorporated
//
// SPDX-License-Identifier: Apache-2.0

#include "AUDIOLIB_gain_idat.h"
/*This file is autogenerated*/
/*Please do not edit*/

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
#include "test_data/staticRefCase1.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
#include "test_data/staticRefCase2.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
#include "test_data/staticRefCase3.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
#include "test_data/staticRefCase4.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
#include "test_data/staticRefCase5.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
#include "test_data/staticRefCase6.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
#include "test_data/staticRefCase7.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
#include "test_data/staticRefCase8.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
#include "test_data/staticRefCase9.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
#include "test_data/staticRefCase10.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
#include "test_data/staticRefCase11.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
#include "test_data/staticRefCase12.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13))
#include "test_data/staticRefCase13.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 14))
#include "test_data/staticRefCase14.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 15))
#include "test_data/staticRefCase15.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 16))
#include "test_data/staticRefCase16.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 17))
#include "test_data/staticRefCase17.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 18))
#include "test_data/staticRefCase18.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 19))
#include "test_data/staticRefCase19.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 20))
#include "test_data/staticRefCase20.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 21))
#include "test_data/staticRefCase21.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 22))
#include "test_data/staticRefCase22.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 23))
#include "test_data/staticRefCase23.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 24))
#include "test_data/staticRefCase24.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 25))
#include "test_data/staticRefCase25.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 26))
#include "test_data/staticRefCase26.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 27))
#include "test_data/staticRefCase27.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 28))
#include "test_data/staticRefCase28.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 29))
#include "test_data/staticRefCase29.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 30))
#include "test_data/staticRefCase30.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 31))
#include "test_data/staticRefCase31.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 32))
#include "test_data/staticRefCase32.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 33))
#include "test_data/staticRefCase33.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 34))
#include "test_data/staticRefCase34.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 35))
#include "test_data/staticRefCase35.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 36))
#include "test_data/staticRefCase36.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 37))
#include "test_data/staticRefCase37.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 38))
#include "test_data/staticRefCase38.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 39))
#include "test_data/staticRefCase39.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 40))
#include "test_data/staticRefCase40.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 41))
#include "test_data/staticRefCase41.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 42))
#include "test_data/staticRefCase42.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 43))
#include "test_data/staticRefCase43.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 44))
#include "test_data/staticRefCase44.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 45))
#include "test_data/staticRefCase45.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 46))
#include "test_data/staticRefCase46.h"
#endif

static AUDIOLIB_gain_testParams_t testParams[] = {
#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
    {
        STATIC,                                                                 // Test pattern
        staticRefIn0Case1,                                                      // Input buffer
        staticRefIn1Case1,                                                      // Input gain
        staticRefOutCase1,                                                      // Output buffer
        16,                                                                     // inSamples
        1,                                                                      // inChannels
        AUDIOLIB_CALC_STRIDE(16 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(16 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT32,                                                       // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                              // Output data location
        1,                                                                      // number of reps.
        1,                                                                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
    {
        STATIC,                                                                  // Test pattern
        staticRefIn0Case2,                                                       // Input buffer
        staticRefIn1Case2,                                                       // Input gain
        staticRefOutCase2,                                                       // Output buffer
        256,                                                                     // inSamples
        1,                                                                       // inChannels
        AUDIOLIB_CALC_STRIDE(256 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(256 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT32,                                                        // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        2,                                                                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
    {
        STATIC,                                                                   // Test pattern
        staticRefIn0Case3,                                                        // Input buffer
        staticRefIn1Case3,                                                        // Input gain
        staticRefOutCase3,                                                        // Output buffer
        4096,                                                                     // inSamples
        1,                                                                        // inChannels
        AUDIOLIB_CALC_STRIDE(4096 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(4096 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT32,                                                         // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                // Output data location
        1,                                                                        // number of reps.
        3,                                                                        // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
    {
        STATIC,                                                                   // Test pattern
        staticRefIn0Case4,                                                        // Input buffer
        staticRefIn1Case4,                                                        // Input gain
        staticRefOutCase4,                                                        // Output buffer
        1024,                                                                     // inSamples
        1,                                                                        // inChannels
        AUDIOLIB_CALC_STRIDE(1024 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(1024 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT32,                                                         // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                // Output data location
        1,                                                                        // number of reps.
        4,                                                                        // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
    {
        STATIC,                                                                   // Test pattern
        staticRefIn0Case5,                                                        // Input buffer
        staticRefIn1Case5,                                                        // Input gain
        staticRefOutCase5,                                                        // Output buffer
        2048,                                                                     // inSamples
        1,                                                                        // inChannels
        AUDIOLIB_CALC_STRIDE(2048 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(2048 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT32,                                                         // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                // Output data location
        1,                                                                        // number of reps.
        5,                                                                        // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
    {
        STATIC,                                                                  // Test pattern
        staticRefIn0Case6,                                                       // Input buffer
        staticRefIn1Case6,                                                       // Input gain
        staticRefOutCase6,                                                       // Output buffer
        128,                                                                     // inSamples
        128,                                                                     // inChannels
        AUDIOLIB_CALC_STRIDE(128 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(128 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT32,                                                        // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        6,                                                                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
    {
        STATIC,                                                                 // Test pattern
        staticRefIn0Case7,                                                      // Input buffer
        staticRefIn1Case7,                                                      // Input gain
        staticRefOutCase7,                                                      // Output buffer
        64,                                                                     // inSamples
        1,                                                                      // inChannels
        AUDIOLIB_CALC_STRIDE(64 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(64 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT32,                                                       // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                              // Output data location
        1,                                                                      // number of reps.
        7,                                                                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
    {
        STATIC,                                                                  // Test pattern
        staticRefIn0Case8,                                                       // Input buffer
        staticRefIn1Case8,                                                       // Input gain
        staticRefOutCase8,                                                       // Output buffer
        128,                                                                     // inSamples
        1,                                                                       // inChannels
        AUDIOLIB_CALC_STRIDE(128 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(128 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT32,                                                        // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        8,                                                                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
    {
        STATIC,                                                                   // Test pattern
        staticRefIn0Case9,                                                        // Input buffer
        staticRefIn1Case9,                                                        // Input gain
        staticRefOutCase9,                                                        // Output buffer
        1024,                                                                     // inSamples
        16,                                                                       // inChannels
        AUDIOLIB_CALC_STRIDE(1024 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(1024 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT32,                                                         // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                // Output data location
        1,                                                                        // number of reps.
        9,                                                                        // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
    {
        STATIC,                                                                // Test pattern
        staticRefIn0Case10,                                                    // Input buffer
        staticRefIn1Case10,                                                    // Input gain
        staticRefOutCase10,                                                    // Output buffer
        3,                                                                     // inSamples
        3,                                                                     // inChannels
        AUDIOLIB_CALC_STRIDE(3 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(3 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT32,                                                      // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                             // Output data location
        1,                                                                     // number of reps.
        10,                                                                    // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
    {
        STATIC,                                                                 // Test pattern
        staticRefIn0Case11,                                                     // Input buffer
        staticRefIn1Case11,                                                     // Input gain
        staticRefOutCase11,                                                     // Output buffer
        31,                                                                     // inSamples
        31,                                                                     // inChannels
        AUDIOLIB_CALC_STRIDE(31 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(31 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT32,                                                       // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                              // Output data location
        1,                                                                      // number of reps.
        11,                                                                     // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
    {
        STATIC,                                                                 // Test pattern
        staticRefIn0Case12,                                                     // Input buffer
        staticRefIn1Case12,                                                     // Input gain
        staticRefOutCase12,                                                     // Output buffer
        51,                                                                     // inSamples
        1,                                                                      // inChannels
        AUDIOLIB_CALC_STRIDE(51 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(51 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT32,                                                       // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                              // Output data location
        1,                                                                      // number of reps.
        12,                                                                     // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13))
    {
        STATIC,                                                                // Test pattern
        staticRefIn0Case13,                                                    // Input buffer
        staticRefIn1Case13,                                                    // Input gain
        staticRefOutCase13,                                                    // Output buffer
        4,                                                                     // inSamples
        1,                                                                     // inChannels
        AUDIOLIB_CALC_STRIDE(4 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(4 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT32,                                                      // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                             // Output data location
        1,                                                                     // number of reps.
        13,                                                                    // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 14))
    {
        STATIC,                                                                  // Test pattern
        staticRefIn0Case14,                                                      // Input buffer
        staticRefIn1Case14,                                                      // Input gain
        staticRefOutCase14,                                                      // Output buffer
        128,                                                                     // inSamples
        128,                                                                     // inChannels
        AUDIOLIB_CALC_STRIDE(128 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(128 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT32,                                                        // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        14,                                                                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 15))
    {
        STATIC,                                                                 // Test pattern
        staticRefIn0Case15,                                                     // Input buffer
        staticRefIn1Case15,                                                     // Input gain
        staticRefOutCase15,                                                     // Output buffer
        64,                                                                     // inSamples
        64,                                                                     // inChannels
        AUDIOLIB_CALC_STRIDE(64 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(64 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT32,                                                       // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                              // Output data location
        1,                                                                      // number of reps.
        15,                                                                     // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 16))
    {
        STATIC,                                                                 // Test pattern
        staticRefIn0Case16,                                                     // Input buffer
        staticRefIn1Case16,                                                     // Input gain
        staticRefOutCase16,                                                     // Output buffer
        55,                                                                     // inSamples
        1,                                                                      // inChannels
        AUDIOLIB_CALC_STRIDE(55 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(55 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT32,                                                       // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                              // Output data location
        1,                                                                      // number of reps.
        16,                                                                     // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 17))
    {
        STATIC,                                                                 // Test pattern
        staticRefIn0Case17,                                                     // Input buffer
        staticRefIn1Case17,                                                     // Input gain
        staticRefOutCase17,                                                     // Output buffer
        32,                                                                     // inSamples
        1,                                                                      // inChannels
        AUDIOLIB_CALC_STRIDE(32 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(32 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT32,                                                       // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                              // Output data location
        1,                                                                      // number of reps.
        17,                                                                     // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 18))
    {
        STATIC,                                                                // Test pattern
        staticRefIn0Case18,                                                    // Input buffer
        staticRefIn1Case18,                                                    // Input gain
        staticRefOutCase18,                                                    // Output buffer
        1,                                                                     // inSamples
        1,                                                                     // inChannels
        AUDIOLIB_CALC_STRIDE(1 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(1 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT32,                                                      // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                             // Output data location
        1,                                                                     // number of reps.
        18,                                                                    // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 19))
    {
        STATIC,                                                                // Test pattern
        staticRefIn0Case19,                                                    // Input buffer
        staticRefIn1Case19,                                                    // Input gain
        staticRefOutCase19,                                                    // Output buffer
        1,                                                                     // inSamples
        3,                                                                     // inChannels
        AUDIOLIB_CALC_STRIDE(1 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(1 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT32,                                                      // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                             // Output data location
        1,                                                                     // number of reps.
        19,                                                                    // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 20))
    {
        STATIC,                                                                // Test pattern
        staticRefIn0Case20,                                                    // Input buffer
        staticRefIn1Case20,                                                    // Input gain
        staticRefOutCase20,                                                    // Output buffer
        1,                                                                     // inSamples
        37,                                                                    // inChannels
        AUDIOLIB_CALC_STRIDE(1 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(1 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT32,                                                      // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                             // Output data location
        1,                                                                     // number of reps.
        20,                                                                    // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 21))
    {
        STATIC,                                                                  // Test pattern
        staticRefIn0Case21,                                                      // Input buffer
        staticRefIn1Case21,                                                      // Input gain
        staticRefOutCase21,                                                      // Output buffer
        16,                                                                      // inSamples
        1,                                                                       // inChannels
        AUDIOLIB_CALC_STRIDE(16 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(16 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT64,                                                        // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        21,                                                                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 22))
    {
        STATIC,                                                                   // Test pattern
        staticRefIn0Case22,                                                       // Input buffer
        staticRefIn1Case22,                                                       // Input gain
        staticRefOutCase22,                                                       // Output buffer
        256,                                                                      // inSamples
        1,                                                                        // inChannels
        AUDIOLIB_CALC_STRIDE(256 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(256 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT64,                                                         // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                // Output data location
        1,                                                                        // number of reps.
        22,                                                                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 23))
    {
        STATIC,                                                                   // Test pattern
        staticRefIn0Case23,                                                       // Input buffer
        staticRefIn1Case23,                                                       // Input gain
        staticRefOutCase23,                                                       // Output buffer
        128,                                                                      // inSamples
        1,                                                                        // inChannels
        AUDIOLIB_CALC_STRIDE(128 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(128 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT64,                                                         // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                // Output data location
        1,                                                                        // number of reps.
        23,                                                                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 24))
    {
        STATIC,                                                                  // Test pattern
        staticRefIn0Case24,                                                      // Input buffer
        staticRefIn1Case24,                                                      // Input gain
        staticRefOutCase24,                                                      // Output buffer
        64,                                                                      // inSamples
        1,                                                                       // inChannels
        AUDIOLIB_CALC_STRIDE(64 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(64 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT64,                                                        // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        24,                                                                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 25))
    {
        STATIC,                                                                  // Test pattern
        staticRefIn0Case25,                                                      // Input buffer
        staticRefIn1Case25,                                                      // Input gain
        staticRefOutCase25,                                                      // Output buffer
        64,                                                                      // inSamples
        64,                                                                      // inChannels
        AUDIOLIB_CALC_STRIDE(64 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(64 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT64,                                                        // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        25,                                                                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 26))
    {
        STATIC,                                                                    // Test pattern
        staticRefIn0Case26,                                                        // Input buffer
        staticRefIn1Case26,                                                        // Input gain
        staticRefOutCase26,                                                        // Output buffer
        1024,                                                                      // inSamples
        16,                                                                        // inChannels
        AUDIOLIB_CALC_STRIDE(1024 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(1024 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT64,                                                          // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                 // Output data location
        1,                                                                         // number of reps.
        26,                                                                        // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 27))
    {
        STATIC,                                                                 // Test pattern
        staticRefIn0Case27,                                                     // Input buffer
        staticRefIn1Case27,                                                     // Input gain
        staticRefOutCase27,                                                     // Output buffer
        3,                                                                      // inSamples
        3,                                                                      // inChannels
        AUDIOLIB_CALC_STRIDE(3 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(3 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT64,                                                       // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                              // Output data location
        1,                                                                      // number of reps.
        27,                                                                     // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 28))
    {
        STATIC,                                                                  // Test pattern
        staticRefIn0Case28,                                                      // Input buffer
        staticRefIn1Case28,                                                      // Input gain
        staticRefOutCase28,                                                      // Output buffer
        31,                                                                      // inSamples
        1,                                                                       // inChannels
        AUDIOLIB_CALC_STRIDE(31 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(31 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT64,                                                        // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        28,                                                                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 29))
    {
        STATIC,                                                                  // Test pattern
        staticRefIn0Case29,                                                      // Input buffer
        staticRefIn1Case29,                                                      // Input gain
        staticRefOutCase29,                                                      // Output buffer
        51,                                                                      // inSamples
        1,                                                                       // inChannels
        AUDIOLIB_CALC_STRIDE(51 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(51 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT64,                                                        // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        29,                                                                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 30))
    {
        STATIC,                                                                 // Test pattern
        staticRefIn0Case30,                                                     // Input buffer
        staticRefIn1Case30,                                                     // Input gain
        staticRefOutCase30,                                                     // Output buffer
        4,                                                                      // inSamples
        4,                                                                      // inChannels
        AUDIOLIB_CALC_STRIDE(4 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(4 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT64,                                                       // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                              // Output data location
        1,                                                                      // number of reps.
        30,                                                                     // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 31))
    {
        STATIC,                                                                   // Test pattern
        staticRefIn0Case31,                                                       // Input buffer
        staticRefIn1Case31,                                                       // Input gain
        staticRefOutCase31,                                                       // Output buffer
        128,                                                                      // inSamples
        128,                                                                      // inChannels
        AUDIOLIB_CALC_STRIDE(128 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(128 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT64,                                                         // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                // Output data location
        1,                                                                        // number of reps.
        31,                                                                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 32))
    {
        STATIC,                                                                  // Test pattern
        staticRefIn0Case32,                                                      // Input buffer
        staticRefIn1Case32,                                                      // Input gain
        staticRefOutCase32,                                                      // Output buffer
        55,                                                                      // inSamples
        1,                                                                       // inChannels
        AUDIOLIB_CALC_STRIDE(55 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(55 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT64,                                                        // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        32,                                                                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 33))
    {
        STATIC,                                                                  // Test pattern
        staticRefIn0Case33,                                                      // Input buffer
        staticRefIn1Case33,                                                      // Input gain
        staticRefOutCase33,                                                      // Output buffer
        32,                                                                      // inSamples
        32,                                                                      // inChannels
        AUDIOLIB_CALC_STRIDE(32 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(32 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT64,                                                        // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        33,                                                                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 34))
    {
        STATIC,                                                                 // Test pattern
        staticRefIn0Case34,                                                     // Input buffer
        staticRefIn1Case34,                                                     // Input gain
        staticRefOutCase34,                                                     // Output buffer
        1,                                                                      // inSamples
        1,                                                                      // inChannels
        AUDIOLIB_CALC_STRIDE(1 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(1 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT64,                                                       // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                              // Output data location
        1,                                                                      // number of reps.
        34,                                                                     // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 35))
    {
        STATIC,                                                                 // Test pattern
        staticRefIn0Case35,                                                     // Input buffer
        staticRefIn1Case35,                                                     // Input gain
        staticRefOutCase35,                                                     // Output buffer
        1,                                                                      // inSamples
        5,                                                                      // inChannels
        AUDIOLIB_CALC_STRIDE(1 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(1 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT64,                                                       // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                              // Output data location
        1,                                                                      // number of reps.
        35,                                                                     // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 36))
    {
        STATIC,                                                                 // Test pattern
        staticRefIn0Case36,                                                     // Input buffer
        staticRefIn1Case36,                                                     // Input gain
        staticRefOutCase36,                                                     // Output buffer
        1,                                                                      // inSamples
        37,                                                                     // inChannels
        AUDIOLIB_CALC_STRIDE(1 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(1 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT64,                                                       // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                              // Output data location
        1,                                                                      // number of reps.
        36,                                                                     // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 37))
    {
        STATIC,                                                                 // Test pattern
        staticRefIn0Case37,                                                     // Input buffer
        staticRefIn1Case37,                                                     // Input gain
        staticRefOutCase37,                                                     // Output buffer
        15,                                                                     // inSamples
        1,                                                                      // inChannels
        AUDIOLIB_CALC_STRIDE(15 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(15 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT32,                                                       // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                              // Output data location
        1,                                                                      // number of reps.
        37,                                                                     // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 38))
    {
        STATIC,                                                                 // Test pattern
        staticRefIn0Case38,                                                     // Input buffer
        staticRefIn1Case38,                                                     // Input gain
        staticRefOutCase38,                                                     // Output buffer
        32,                                                                     // inSamples
        1,                                                                      // inChannels
        AUDIOLIB_CALC_STRIDE(32 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(32 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT32,                                                       // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                              // Output data location
        1,                                                                      // number of reps.
        38,                                                                     // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 39))
    {
        STATIC,                                                                    // Test pattern
        staticRefIn0Case39,                                                        // Input buffer
        staticRefIn1Case39,                                                        // Input gain
        staticRefOutCase39,                                                        // Output buffer
        1024,                                                                      // inSamples
        1,                                                                         // inChannels
        AUDIOLIB_CALC_STRIDE(1024 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(1024 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT64,                                                          // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                 // Output data location
        1,                                                                         // number of reps.
        39,                                                                        // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 40))
    {
        STATIC,                                                                    // Test pattern
        staticRefIn0Case40,                                                        // Input buffer
        staticRefIn1Case40,                                                        // Input gain
        staticRefOutCase40,                                                        // Output buffer
        2048,                                                                      // inSamples
        1,                                                                         // inChannels
        AUDIOLIB_CALC_STRIDE(2048 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(2048 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT64,                                                          // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                 // Output data location
        1,                                                                         // number of reps.
        40,                                                                        // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 41))
    {
        STATIC,                                                                    // Test pattern
        staticRefIn0Case41,                                                        // Input buffer
        staticRefIn1Case41,                                                        // Input gain
        staticRefOutCase41,                                                        // Output buffer
        4096,                                                                      // inSamples
        1,                                                                         // inChannels
        AUDIOLIB_CALC_STRIDE(4096 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(4096 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT64,                                                          // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                 // Output data location
        1,                                                                         // number of reps.
        41,                                                                        // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 42))
    {
        STATIC,                                                                  // Test pattern
        staticRefIn0Case42,                                                      // Input buffer
        staticRefIn1Case42,                                                      // Input gain
        staticRefOutCase42,                                                      // Output buffer
        64,                                                                      // inSamples
        32,                                                                      // inChannels
        AUDIOLIB_CALC_STRIDE(64 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(64 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT64,                                                        // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        42,                                                                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 43))
    {
        STATIC,                                                                 // Test pattern
        staticRefIn0Case43,                                                     // Input buffer
        staticRefIn1Case43,                                                     // Input gain
        staticRefOutCase43,                                                     // Output buffer
        64,                                                                     // inSamples
        32,                                                                     // inChannels
        AUDIOLIB_CALC_STRIDE(64 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(64 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT32,                                                       // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                              // Output data location
        1,                                                                      // number of reps.
        43,                                                                     // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 44))
    {
        STATIC,                                                                 // Test pattern
        staticRefIn0Case44,                                                     // Input buffer
        staticRefIn1Case44,                                                     // Input gain
        staticRefOutCase44,                                                     // Output buffer
        32,                                                                     // inSamples
        32,                                                                     // inChannels
        AUDIOLIB_CALC_STRIDE(32 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(32 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT32,                                                       // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                              // Output data location
        1,                                                                      // number of reps.
        44,                                                                     // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 45))
    {
        STATIC,                                                                    // Test pattern
        staticRefIn0Case45,                                                        // Input buffer
        staticRefIn1Case45,                                                        // Input gain
        staticRefOutCase45,                                                        // Output buffer
        16384,                                                                     // inSamples
        1,                                                                         // inChannels
        AUDIOLIB_CALC_STRIDE(16384 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(16384 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT32,                                                          // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                 // Output data location
        1,                                                                         // number of reps.
        45,                                                                        // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 46))
    {
        STATIC,                                                                     // Test pattern
        staticRefIn0Case46,                                                         // Input buffer
        staticRefIn1Case46,                                                         // Input gain
        staticRefOutCase46,                                                         // Output buffer
        16384,                                                                      // inSamples
        1,                                                                          // inChannels
        AUDIOLIB_CALC_STRIDE(16384 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(16384 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT64,                                                           // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                  // Output data location
        1,                                                                          // number of reps.
        46,                                                                         // test ID
    },
#endif

};

/*
 *  Sends the test parameter structure and number of tests
 */
void AUDIOLIB_gain_getTestParams(AUDIOLIB_gain_testParams_t** params, int32_t* numTests)
{
   *params   = testParams;
   *numTests = sizeof(testParams) / sizeof(AUDIOLIB_gain_testParams_t);
}
