// Copyright (C) 2026 Texas Instruments Incorporated
//
// SPDX-License-Identifier: Apache-2.0

#include "AUDIOLIB_tableInterpolate_idat.h"
/*This file is autogenerated*/
/*Please do not edit*/

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
#include "test_data/staticRefCase1.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
#include "test_data/staticRefCase2.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
#include "test_data/staticRefCase3.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
#include "test_data/staticRefCase4.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
#include "test_data/staticRefCase5.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
#include "test_data/staticRefCase6.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
#include "test_data/staticRefCase7.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
#include "test_data/staticRefCase9.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
#include "test_data/staticRefCase10.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
#include "test_data/staticRefCase11.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
#include "test_data/staticRefCase12.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13))
#include "test_data/staticRefCase13.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 14))
#include "test_data/staticRefCase14.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 15))
#include "test_data/staticRefCase15.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 16))
#include "test_data/staticRefCase16.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 17))
#include "test_data/staticRefCase17.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 18))
#include "test_data/staticRefCase18.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 19))
#include "test_data/staticRefCase19.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 20))
#include "test_data/staticRefCase20.h"
#endif

static AUDIOLIB_tableInterpolate_testParams_t testParams[] = {
#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
    {
        STATIC,                    // Test Pattern
        staticRefIn0Case1,         // in0
        staticRefIn1Case1,         // in1
        staticRefOutCase1,         // out
        AUDIOLIB_FLOAT32,          // Sample Data Type
        16,                        // Samples per channel
        16,                        // Number of Channels
        3,                         // minVal
        3,                         // maxVal
        256,                       // tableInterpolateSize
        AUDIOLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                         // number of reps.
        1,                         // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
    {
        STATIC,                    // Test Pattern
        staticRefIn0Case2,         // in0
        staticRefIn1Case2,         // in1
        staticRefOutCase2,         // out
        AUDIOLIB_FLOAT32,          // Sample Data Type
        1024,                      // Samples per channel
        16,                        // Number of Channels
        0,                         // minVal
        16,                        // maxVal
        256,                       // tableInterpolateSize
        AUDIOLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                         // number of reps.
        2,                         // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
    {
        STATIC,                    // Test Pattern
        staticRefIn0Case3,         // in0
        staticRefIn1Case3,         // in1
        staticRefOutCase3,         // out
        AUDIOLIB_FLOAT32,          // Sample Data Type
        1024,                      // Samples per channel
        256,                       // Number of Channels
        0,                         // minVal
        1024,                      // maxVal
        256,                       // tableInterpolateSize
        AUDIOLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                         // number of reps.
        3,                         // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
    {
        STATIC,                    // Test Pattern
        staticRefIn0Case4,         // in0
        staticRefIn1Case4,         // in1
        staticRefOutCase4,         // out
        AUDIOLIB_FLOAT32,          // Sample Data Type
        1024,                      // Samples per channel
        256,                       // Number of Channels
        -1,                        // minVal
        1024,                      // maxVal
        256,                       // tableInterpolateSize
        AUDIOLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                         // number of reps.
        4,                         // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
    {
        STATIC,                    // Test Pattern
        staticRefIn0Case5,         // in0
        staticRefIn1Case5,         // in1
        staticRefOutCase5,         // out
        AUDIOLIB_FLOAT32,          // Sample Data Type
        1024,                      // Samples per channel
        256,                       // Number of Channels
        -1,                        // minVal
        -1,                        // maxVal
        256,                       // tableInterpolateSize
        AUDIOLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                         // number of reps.
        5,                         // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
    {
        STATIC,                    // Test Pattern
        staticRefIn0Case6,         // in0
        staticRefIn1Case6,         // in1
        staticRefOutCase6,         // out
        AUDIOLIB_FLOAT32,          // Sample Data Type
        512,                       // Samples per channel
        32,                        // Number of Channels
        0,                         // minVal
        16,                        // maxVal
        256,                       // tableInterpolateSize
        AUDIOLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                         // number of reps.
        6,                         // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
    {
        STATIC,                    // Test Pattern
        staticRefIn0Case7,         // in0
        staticRefIn1Case7,         // in1
        staticRefOutCase7,         // out
        AUDIOLIB_FLOAT32,          // Sample Data Type
        512,                       // Samples per channel
        256,                       // Number of Channels
        0,                         // minVal
        256,                       // maxVal
        256,                       // tableInterpolateSize
        AUDIOLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                         // number of reps.
        7,                         // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
    {
        STATIC,                    // Test Pattern
        staticRefIn0Case9,         // in0
        staticRefIn1Case9,         // in1
        staticRefOutCase9,         // out
        AUDIOLIB_FLOAT32,          // Sample Data Type
        1,                         // Samples per channel
        1,                         // Number of Channels
        0,                         // minVal
        1,                         // maxVal
        256,                       // tableInterpolateSize
        AUDIOLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                         // number of reps.
        9,                         // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
    {
        STATIC,                    // Test Pattern
        staticRefIn0Case10,        // in0
        staticRefIn1Case10,        // in1
        staticRefOutCase10,        // out
        AUDIOLIB_FLOAT32,          // Sample Data Type
        16,                        // Samples per channel
        129,                       // Number of Channels
        0,                         // minVal
        1.3,                       // maxVal
        256,                       // tableInterpolateSize
        AUDIOLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                         // number of reps.
        10,                        // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
    {
        STATIC,                    // Test Pattern
        staticRefIn0Case11,        // in0
        staticRefIn1Case11,        // in1
        staticRefOutCase11,        // out
        AUDIOLIB_FLOAT32,          // Sample Data Type
        32,                        // Samples per channel
        16,                        // Number of Channels
        0.5,                       // minVal
        1.3,                       // maxVal
        256,                       // tableInterpolateSize
        AUDIOLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                         // number of reps.
        11,                        // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
    {
        STATIC,                    // Test Pattern
        staticRefIn0Case12,        // in0
        staticRefIn1Case12,        // in1
        staticRefOutCase12,        // out
        AUDIOLIB_FLOAT32,          // Sample Data Type
        1000,                      // Samples per channel
        64,                        // Number of Channels
        -0.5,                      // minVal
        8.4,                       // maxVal
        256,                       // tableInterpolateSize
        AUDIOLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                         // number of reps.
        12,                        // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13))
    {
        STATIC,                    // Test Pattern
        staticRefIn0Case13,        // in0
        staticRefIn1Case13,        // in1
        staticRefOutCase13,        // out
        AUDIOLIB_FLOAT32,          // Sample Data Type
        64,                        // Samples per channel
        16,                        // Number of Channels
        0.7,                       // minVal
        -5.4,                      // maxVal
        256,                       // tableInterpolateSize
        AUDIOLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                         // number of reps.
        13,                        // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 14))
    {
        STATIC,                    // Test Pattern
        staticRefIn0Case14,        // in0
        staticRefIn1Case14,        // in1
        staticRefOutCase14,        // out
        AUDIOLIB_FLOAT32,          // Sample Data Type
        1025,                      // Samples per channel
        16,                        // Number of Channels
        -4.5,                      // minVal
        -1.3,                      // maxVal
        256,                       // tableInterpolateSize
        AUDIOLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                         // number of reps.
        14,                        // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 15))
    {
        STATIC,                    // Test Pattern
        staticRefIn0Case15,        // in0
        staticRefIn1Case15,        // in1
        staticRefOutCase15,        // out
        AUDIOLIB_FLOAT32,          // Sample Data Type
        2048,                      // Samples per channel
        32,                        // Number of Channels
        -4.5,                      // minVal
        -1.3,                      // maxVal
        256,                       // tableInterpolateSize
        AUDIOLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                         // number of reps.
        15,                        // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 16))
    {
        STATIC,                    // Test Pattern
        staticRefIn0Case16,        // in0
        staticRefIn1Case16,        // in1
        staticRefOutCase16,        // out
        AUDIOLIB_FLOAT32,          // Sample Data Type
        128,                       // Samples per channel
        129,                       // Number of Channels
        0,                         // minVal
        128,                       // maxVal
        256,                       // tableInterpolateSize
        AUDIOLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                         // number of reps.
        16,                        // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 17))
    {
        STATIC,                    // Test Pattern
        staticRefIn0Case17,        // in0
        staticRefIn1Case17,        // in1
        staticRefOutCase17,        // out
        AUDIOLIB_FLOAT32,          // Sample Data Type
        32,                        // Samples per channel
        16,                        // Number of Channels
        0.5,                       // minVal
        32,                        // maxVal
        256,                       // tableInterpolateSize
        AUDIOLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                         // number of reps.
        17,                        // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 18))
    {
        STATIC,                    // Test Pattern
        staticRefIn0Case18,        // in0
        staticRefIn1Case18,        // in1
        staticRefOutCase18,        // out
        AUDIOLIB_FLOAT32,          // Sample Data Type
        1000,                      // Samples per channel
        64,                        // Number of Channels
        -128,                      // minVal
        128,                       // maxVal
        256,                       // tableInterpolateSize
        AUDIOLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                         // number of reps.
        18,                        // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 19))
    {
        STATIC,                    // Test Pattern
        staticRefIn0Case19,        // in0
        staticRefIn1Case19,        // in1
        staticRefOutCase19,        // out
        AUDIOLIB_FLOAT32,          // Sample Data Type
        64,                        // Samples per channel
        16,                        // Number of Channels
        0.7,                       // minVal
        -5.4,                      // maxVal
        256,                       // tableInterpolateSize
        AUDIOLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                         // number of reps.
        19,                        // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 20))
    {
        STATIC,                    // Test Pattern
        staticRefIn0Case20,        // in0
        staticRefIn1Case20,        // in1
        staticRefOutCase20,        // out
        AUDIOLIB_FLOAT32,          // Sample Data Type
        64,                        // Samples per channel
        257,                       // Number of Channels
        0.7,                       // minVal
        -5.4,                      // maxVal
        256,                       // tableInterpolateSize
        AUDIOLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                         // number of reps.
        20,                        // test ID
    },
#endif

};

/*
 *  Sends the test parameter structure and number of tests
 */
void AUDIOLIB_tableInterpolate_getTestParams(AUDIOLIB_tableInterpolate_testParams_t** params, int32_t* numTests)
{
   *params   = testParams;
   *numTests = sizeof(testParams) / sizeof(AUDIOLIB_tableInterpolate_testParams_t);
}
