# Copyright (C) 2026 Texas Instruments Incorporated
#
# SPDX-License-Identifier: Apache-2.0

from __future__ import print_function
from subprocess import call
from sys import platform

import sys
import numpy as np
import csv

sys.path.append("../common")
# from AUDIOLIB_idat_gen.common import AUDIOLIB_utils
import AUDIOLIB_utils
import file_io
import os
from delayNChannel import AUDIOLIB_delayNChannel


def gen_testCaseParams(testParamsFile, currPrm):
    """Generate and write test case parameters to idat file

    Args:
        param1 (file object): Input file object to idat.c file
        param2 (dict object): Dict object with test case parameter

    """
    testId = currPrm["ID"]
    dType = currPrm["dType"]
    mode = currPrm["mode"]
    interleave = currPrm["interleave"]
    numChannels = currPrm["numChannels"]
    numSamples = currPrm["numSamples"]
    strideIn = currPrm["strideInElements"]
    strideOut = currPrm["strideOutElements"]
    testType = currPrm["testType"]
    demoCase = currPrm["demoCase"]
    outputDataLocation = currPrm["outputDataLocation"]
    numReps = currPrm["numReps"]
    numExecReps = currPrm["numExecReps"]
    C7100 = currPrm["C7100"]

    if testType == "STATIC":
        inputBuff = "staticRefInCase" + testId
        delaySizeBuff = "staticDelaySizeCase" + testId
        outputBuff = "staticRefOutCase" + testId
        delayBuff = "staticUpdatedDelayCase" + testId
    else:
        inputBuff = "NULL"
        delaySizeBuff = "NULL"
        outputBuff = "NULL"
        delayBuff = "NULL"
    if C7100 == "FALSE":
        testParamsFile.write("#if !defined(__C7100__)\n")

    if demoCase == "true":
        testParamsFile.write(
            "#if (defined(ALL_TEST_CASES) || (TEST_CASE == %d) || defined(DEMO_CASE))\n"
            % (int(testId))
        )
    else:
        testParamsFile.write(
            "#if (defined(ALL_TEST_CASES) || (TEST_CASE == %d))\n" % (int(testId))
        )

    idatFile.write("{\n")
    idatFile.write("%s, // Test pattern \n" % ((testType)))
    idatFile.write("%s, // precision \n" % ((AUDIOLIB_utils.resolve_dType(dType))))
    idatFile.write("%s, // mode \n" % ((mode)))
    idatFile.write("%s, // Input buffer\n" % ((inputBuff)))
    idatFile.write("%s, // DelaySize buffer \n" % ((delaySizeBuff)))
    idatFile.write("%s, // Output buffer \n" % ((outputBuff)))
    idatFile.write("%s, // updatedDelay buffer \n" % ((delayBuff)))
    idatFile.write("%s, // Interleave \n" % ((interleave)))
    idatFile.write("%s, // numChannels \n" % ((numChannels)))
    idatFile.write("%s, // numSamples \n" % ((numSamples)))
    idatFile.write(
        "%s * sizeof(%s), // stride of input buffer \n" % ((strideIn), (dType))
    )
    idatFile.write(
        "%s * sizeof(%s), // stride of output buffer \n" % ((strideOut), (dType))
    )
    idatFile.write("%s, // Output data location \n" % (outputDataLocation))
    idatFile.write("%d, // number of reps. \n" % (int(numReps)))
    idatFile.write("%d, // Number of execution repetitions \n" % (int(numExecReps)))
    idatFile.write("%d, // test ID\n" % int(testId))

    idatFile.write("},\n")
    idatFile.write("#endif\n")

    if C7100 == "FALSE":
        testParamsFile.write("#endif // if !defined(__C7100__)\n")

    idatFile.write("\n\n")


def gen_idat_file(idatFile, testCases):
    """Generate the idat file

    Args:
        param1 (file object): Input file object to idat.c file
        param2 (dict object): Dict object with test case parameter

    """

    fIn = open("../common/ti_lice_header_idat.txt", "r")
    lines = fIn.readlines()
    fIn.close()
    idatFile.writelines(lines)
    includeString = '#include "AUDIOLIB_delayNChannel_idat.h"'
    idatFile.writelines(includeString)
    idatFile.write("\n")
    idatFile.write("/*This file is autogenerated*/\n")
    idatFile.write("/*Please do not edit*/\n")
    idatFile.write("\n\n")
    # generate ifdefs for header files
    for testCase in testCases:
        if testCase["testType"] == "STATIC":
            AUDIOLIB_utils.gen_ifdefs(idatFile, testCase)

    # generate parameters for test cases
    idatFile.write("static AUDIOLIB_delayNChannel_testParams_t testParams[] =  ")
    idatFile.write("{\n")

    for testCase in testCases:
        gen_testCaseParams(idatFile, testCase)

    idatFile.write("};\n\n")
    fIn = open("test_param_function.txt", "r")
    lines = fIn.readlines()

    idatFile.writelines(lines)


def process_test_case(testCase):
    """Convert str to int for necessary parameters

    Args:
        Param1(:obj: dict) : Dictionary object with test case parameters

    Returns:
        Obj: Dictionary object with necessary parameters converted to int

    """

    testCase["testId"] = int(testCase["ID"])
    testCase["mode"] = int(testCase["mode"])
    testCase["interleave"] = int(testCase["interleave"])
    testCase["numChannels"] = int(testCase["numChannels"])
    testCase["numSamples"] = int(testCase["numSamples"])
    testCase["strideOut"] = int(testCase["strideOutElements"])
    testCase["maxDelay"] = int(testCase["maxDelay"])
    testCase["numExecReps"] = int(testCase["numExecReps"])
    testCase["strideIn"] = int(testCase["strideInElements"])
    return testCase


def gen_test_case_header_file(testCase):
    """Generate test case and write out input, filter, and output tensor
    into a header file usable in C/C++ code.

    Args:
        testCase (dict): A dict object with all the test case parameters

    Returns:
        [int, int]: Minimum and maximum value in output feature tensor
    """

    ##############################
    # Get test parameter of case #
    ##############################
    mode = testCase["mode"]
    testId = testCase["ID"]
    dType = testCase["dType"]
    interleave = testCase["interleave"]
    numChannels = testCase["numChannels"]
    numSamples = testCase["numSamples"]
    maxDelay = testCase["maxDelay"]
    numExecReps = testCase["numExecReps"]

    # Generate delay size - keeping the same logic as before
    minDelaySize = 1
    maxDelaySize = maxDelay
    delaySize = np.random.randint(
        low=minDelaySize, high=maxDelaySize, size=(numChannels)
    ).astype("uint32")
    if maxDelay not in delaySize:
        delaySize[numChannels - 1] = maxDelay
    np.random.shuffle(delaySize)

    # Create an instance of AUDIOLIB_delayNChannel with the delay size
    delayNChannel = AUDIOLIB_delayNChannel(
        dType=dType,
        mode=mode,
        interleave=interleave,
        numChannels=numChannels,
        numSamples=numSamples,
        numExecReps=numExecReps,
        delaySize=delaySize,
    )

    # Generate input data - keeping the same logic as before
    if dType == "int8_t" or dType == "uint8_t":
        bits = 8
    elif dType == "int16_t" or dType == "uint16_t":
        bits = 16
    elif dType == "int32_t" or dType == "uint32_t":
        bits = 32
    else:
        bits = 32

    # unsigned integer
    if dType[0] == "u":
        minVal = 0
        maxVal = (2**bits) - 1
    else:
        minVal = -(2 ** (bits - 1))
        maxVal = 2 ** (bits - 1)

    # Create input buffer based on interleave and data type
    if interleave == 1:
        if dType == "float":
            inputBuff = np.random.uniform(
                low=minVal, high=maxVal, size=(numExecReps * numSamples, numChannels)
            ).astype("float32")
        elif dType == "double":
            inputBuff = np.random.uniform(
                low=minVal, high=maxVal, size=(numExecReps * numSamples, numChannels)
            ).astype("double")
        else:
            raise ValueError(f"Unsupported data type: {dType}")
    else:
        if dType == "float":
            inputBuff = np.random.randint(
                low=minVal, high=maxVal, size=(numChannels, numExecReps * numSamples)
            ).astype("float32")
        elif dType == "double":
            inputBuff = np.random.randint(
                low=minVal, high=maxVal, size=(numChannels, numExecReps * numSamples)
            ).astype("double")
        else:
            raise ValueError(f"Unsupported data type: {dType}")

    # Save original input buffer for header file
    inputBuffTemp = inputBuff.copy()

    # Execute the algorithm using the class
    outBuff, delayBuff, delayBuffSize = delayNChannel.exec(inputBuff)

    headerFileName = "staticRefCase" + str(testId) + ".h"
    file_io.write_header_file(
        inputBuffTemp,
        delaySize,
        outBuff,
        delayBuff,
        testCase,
        headerFileName,
        delayBuffSize,
    )
    return [np.min(outBuff), np.max(outBuff)]


# CSV file with paratmeters for all test cases
testCasesCsvFile = "../AUDIOLIB_delayNChannel/test_cases_list.csv"
testIdList = []  # list of test IDs that we want to generate test data
testIdList += range(0, 100)
# testIdList = [18]

myArgs = AUDIOLIB_utils.getCmdLineArgs()


def gen_test_case(testCase):
    if testCase["numExecReps"] < 6:
        print(
            "Skipping test case generation for test ID",
            testCase["ID"],
            "as numExecReps < 6",
        )
        return

    if testCase["testType"] == "STATIC":
        [minY, maxY] = gen_test_case_header_file(testCase)
        print(
            "Test case generation completed for test ID",
            testCase["ID"],
            "w/ min:",
            minY,
            "and max",
            maxY,
        )
    else:
        print(
            "Skipping test case generation for test ID",
            testCase["ID"],
            "as tesType is RANDOM",
        )


#############################################################################
# Open CSV file with test cases and generate header file with test data for #
# test cases of interest; based on testIdList                               #
#############################################################################

with open(testCasesCsvFile, encoding="utf-8-sig") as csv_file:
    testCaseReader = csv.DictReader(csv_file)
    testCases = list(testCaseReader)

    for testCase in testCases:
        testCase = process_test_case(testCase)

    for testCase in testCases:
        if myArgs.allCases == True:
            gen_test_case(testCase)
        elif int(testCase["ID"]) in testIdList:
            gen_test_case(testCase)


idatFileName = "../../AUDIOLIB_delayNChannel/AUDIOLIB_delayNChannel_idat.c"

##########################################################################
# Generate idat.cpp file by parsing all the test cases in the CSV file # #
##########################################################################


with open(idatFileName, "w") as idatFile:
    gen_idat_file(idatFile, testCases)


if platform == "linux" or platform == "linux2":
    call(["clang-format", "-style=file", "-i", idatFileName])
    call(["indent", "-nut", "-i3", "-c55", "-l200", idatFileName])
    call(["rm", idatFileName + "~"])  # remove backup file


print("Idat file generation completed")
