# Copyright (C) 2026 Texas Instruments Incorporated
#
# SPDX-License-Identifier: Apache-2.0

from __future__ import print_function
from subprocess import call
from sys import platform

import sys
import numpy as np
import csv

sys.path.append("../common")
# from AUDIOLIB_idat_gen.common import AUDIOLIB_utils
import AUDIOLIB_utils
import ast
import file_io
import os
import input_aggregator as ia


def gen_testCaseParams(testParamsFile, currPrm):
    """Generate and write test case parameters to idat file

    Args:
        param1 (file object): Input file object to idat.c file
        param2 (dict object): Dict object with test case parameter

    """

    testId = currPrm["ID"]
    dType = currPrm["dType"]
    totalInChannels = currPrm["totalInChannels"]  # Using the calculated total
    inSamples = currPrm["inSamples"]
    isInputInterleave = currPrm["isInputInterleave"]
    isOutputInterleave = currPrm["isOutputInterleave"]
    strideIn0 = currPrm["strideInElements"]
    strideOut = currPrm["strideOutElements"]
    testType = currPrm["testType"]
    demoCase = currPrm["demoCase"]
    outputDataLocation = currPrm["outputDataLocation"]
    numReps = currPrm["numReps"]
    C7100 = currPrm["C7100"]

    # Parse inChannels to get the number of input groups and channel counts
    inChannelsList = ast.literal_eval(currPrm["inChannels"])
    numInputs = len(inChannelsList)

    if testType == "STATIC":
        # Dynamically generate input buffer names based on the number of input groups
        pInputs = f"staticRefInCase{testId}"
        out = "staticRefOutCase" + testId
        # Generate inChannels array name
        inChannelsArrayName = f"inChannelsCase{testId}"

    else:
        input_buffers = ["NULL"] * numInputs
        out = "NULL"
        inChannelsArrayName = "NULL"

    if C7100 == "FALSE":
        testParamsFile.write("#if !defined(__C7100__)\n")

    if demoCase == "true":
        testParamsFile.write(
            "#if (defined(ALL_TEST_CASES) || (TEST_CASE == %d) || defined(DEMO_CASE))\n"
            % (int(testId))
        )
    else:
        testParamsFile.write(
            "#if (defined(ALL_TEST_CASES) || (TEST_CASE == %d))\n" % (int(testId))
        )

    idatFile.write("{\n")
    idatFile.write("%s, // Test pattern \n" % ((testType)))
    idatFile.write(
        f"    (void**){pInputs}, // pInputs (pointer to array of input pointers) \n"
    )
    idatFile.write("%s, // Output buffer \n" % ((out)))
    idatFile.write("%s, // inSamples \n" % ((inSamples)))
    idatFile.write("%s, // totalInChannels \n" % ((totalInChannels)))
    idatFile.write("%s, // Pointer to array of channel counts \n" % inChannelsArrayName)
    idatFile.write("%s, // isInputInterleave \n" % ((isInputInterleave)))
    idatFile.write("%s, // isOutputInterleave \n" % ((isOutputInterleave)))
    idatFile.write("%d, // numInputs \n" % numInputs)
    idatFile.write(
        "AUDIOLIB_CALC_STRIDE(%s * sizeof(%s), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0 \n"
        % ((strideIn0), (dType))
    )
    idatFile.write(
        "AUDIOLIB_CALC_STRIDE(%s * sizeof(%s), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut \n"
        % ((strideOut), (dType))
    )
    idatFile.write("%s, // precision \n" % ((AUDIOLIB_utils.resolve_dType(dType))))
    idatFile.write("%s, // Output data location \n" % (outputDataLocation))
    idatFile.write("%d, // number of reps. \n" % (int(numReps)))
    idatFile.write("%d, // test ID \n" % int(testId))
    idatFile.write("},\n")
    idatFile.write("#endif\n")

    if C7100 == "FALSE":
        testParamsFile.write("#endif // if !defined(__C7100__)\n")

    idatFile.write("\n\n")


def gen_idat_file(idatFile, testCases):
    """Generate the idat file

    Args:
        param1 (file object): Input file object to idat.c file
        param2 (dict object): Dict object with test case parameter

    """

    fIn = open("../common/ti_lice_header_idat.txt", "r")
    lines = fIn.readlines()
    fIn.close()
    idatFile.writelines(lines)
    includeString = '#include "AUDIOLIB_inputAggregator_idat.h"'
    idatFile.writelines(includeString)
    idatFile.write("\n")
    idatFile.write("/*This file is autogenerated*/\n")
    idatFile.write("/*Please do not edit*/\n")
    idatFile.write("\n\n")
    # generate ifdefs for header files
    for testCase in testCases:
        if testCase["testType"] == "STATIC":
            AUDIOLIB_utils.gen_ifdefs(idatFile, testCase)

    idatFile.write(
        "\n/* ====================================================================== */\n"
    )
    idatFile.write(
        "/* Static Input Pointer and Channel Count Arrays                        */\n"
    )
    idatFile.write(
        "/* ====================================================================== */\n\n"
    )
    for testCase in testCases:
        if testCase["testType"] == "STATIC":
            testId = testCase["ID"]
            inChannelsList = ast.literal_eval(testCase["inChannels"])
            numInputs = len(inChannelsList)

            idatFile.write(
                f"#if (defined(ALL_TEST_CASES) || (TEST_CASE == {testId}))\n"
            )
            # Create the static array of pointers to the input buffers
            idatFile.write(f"static void *staticRefInCase{testId}[{numInputs}] = {{\n")
            for i in range(numInputs):
                idatFile.write(f"    (void *)staticRefInput{i}Case{testId},\n")
            idatFile.write("};\n")
            idatFile.write("#endif\n\n")

    # generate parameters for test cases
    idatFile.write("static AUDIOLIB_inputAggregator_testParams_t testParams[] =  ")
    idatFile.write("{\n")

    for testCase in testCases:
        gen_testCaseParams(idatFile, testCase)

    idatFile.write("};\n\n")
    fIn = open("test_param_function.txt", "r")
    lines = fIn.readlines()

    idatFile.writelines(lines)


def process_test_case(testCase):
    """
    Convert str to numbers for necessary parameters and processes the inChannels list.
    """
    # print(f"Processing test case ID {testCase['ID']}: strideOutElements = '{testCase['strideOutElements']}'")
    try:
        testCase["testId"] = int(testCase["ID"])
        testCase["inSamples"] = int(testCase["inSamples"])
        testCase["isInputInterleave"] = int(testCase["isInputInterleave"])
        testCase["isOutputInterleave"] = int(testCase["isOutputInterleave"])
        testCase["strideInElements"] = int(testCase["strideInElements"])
        testCase["strideOutElements"] = int(testCase["strideOutElements"])
    except ValueError as e:
        print(f"Error converting parameters for test case ID {testCase['ID']}: {e}")
        raise

    try:
        inChannelsList = ast.literal_eval(testCase["inChannels"])
        if not isinstance(inChannelsList, list):
            raise ValueError("inChannels must be a list")
        testCase["totalInChannels"] = sum(inChannelsList)
    except (ValueError, SyntaxError):
        try:
            num_channels = int(testCase["inChannels"])
            testCase["inChannels"] = f"[{num_channels}]"
            testCase["totalInChannels"] = num_channels
        except ValueError:
            raise ValueError(
                f"Invalid inChannels format for test case ID {testCase['ID']}: {testCase['inChannels']}"
            )

    return testCase


def gen_test_case_header_file(testCase, inChannelsArray=None):
    """
    Generates test data for the InputAggregator.
    Uses the input_aggregator module for core aggregation logic.
    """
    testId = testCase["ID"]
    dType = testCase["dType"]
    inSamples = testCase["inSamples"]
    isInputInterleave = bool(testCase["isInputInterleave"])
    isOutputInterleave = bool(testCase["isOutputInterleave"])
    inChannelsList = ast.literal_eval(testCase["inChannels"])
    [minVal, maxVal] = [-10, 10]

    # 1. Generate individual input arrays using the input_aggregator module
    individual_inputs = ia.generate_inputs(
        in_channels_list=inChannelsList,
        num_samples=inSamples,
        dtype=dType,
        is_input_interleave=isInputInterleave,
        min_val=minVal,
        max_val=maxVal,
    )

    # 2. Aggregate inputs using the input_aggregator module
    final_merged_output = ia.input_aggregator(
        individual_inputs=individual_inputs,
        is_input_interleave=isInputInterleave,
        is_output_interleave=isOutputInterleave,
    )

    # 3. Write the individual inputs and the final merged output to the header file
    headerFileName = f"staticRefCase{testId}.h"
    file_io.write_header_file(
        individual_inputs,
        final_merged_output,
        testCase,
        headerFileName,
        inChannelsArray,
    )

    return [np.min(final_merged_output), np.max(final_merged_output)]


# CSV file with paratmeters for all test cases
testCasesCsvFile = "../AUDIOLIB_inputAggregator/test_cases_list.csv"
testIdList = []  # list of test IDs that we want to generate test data
testIdList += range(0, 60)

myArgs = AUDIOLIB_utils.getCmdLineArgs()


def gen_test_case(testCase):
    if testCase["testType"] == "STATIC":
        inChannelsList = ast.literal_eval(testCase["inChannels"])
        inChannelsArray = ", ".join(str(ch) for ch in inChannelsList)
        [minY, maxY] = gen_test_case_header_file(testCase, inChannelsArray)
        print(
            "Test case generation completed for test ID",
            testCase["ID"],
            "w/ min:",
            minY,
            "and max",
            maxY,
        )
    else:
        print(
            "Skipping test case generation for test ID",
            testCase["ID"],
            "as tesType is RANDOM",
        )


#############################################################################
# Open CSV file with test cases and generate header file with test data for #
# test cases of interest; based on testIdList                               #
#############################################################################

with open(testCasesCsvFile, encoding="utf-8-sig") as csv_file:
    testCaseReader = csv.DictReader(csv_file)
    testCases = list(testCaseReader)

    for testCase in testCases:
        # print(f"Raw CSV row for ID {testCase['ID']}: {testCase}")
        testCase = process_test_case(testCase)

    for testCase in testCases:
        if myArgs.allCases == True:
            gen_test_case(testCase)
        elif int(testCase["ID"]) in testIdList:
            gen_test_case(testCase)


idatFileName = "../../AUDIOLIB_inputAggregator/AUDIOLIB_inputAggregator_idat.c"


##########################################################################
# Generate idat.cpp file by parsing all the test cases in the CSV file # #
##########################################################################


with open(idatFileName, "w") as idatFile:
    gen_idat_file(idatFile, testCases)


if platform == "linux" or platform == "linux2":
    call(["clang-format", "-style=file", "-i", idatFileName])
    call(["indent", "-nut", "-i3", "-c55", "-l200", idatFileName])
    call(["rm", idatFileName + "~"])  # remove backup file


print("Idat file generation completed")
