// Copyright (C) 2026 Texas Instruments Incorporated
//
// SPDX-License-Identifier: Apache-2.0

#include "AUDIOLIB_balance_idat.h"
/*This file is autogenerated*/
/*Please do not edit*/

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
#include "test_data/staticRefCase1.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
#include "test_data/staticRefCase2.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
#include "test_data/staticRefCase3.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
#include "test_data/staticRefCase4.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
#include "test_data/staticRefCase5.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
#include "test_data/staticRefCase6.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
#include "test_data/staticRefCase7.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
#include "test_data/staticRefCase8.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
#include "test_data/staticRefCase9.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
#include "test_data/staticRefCase10.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
#include "test_data/staticRefCase11.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
#include "test_data/staticRefCase12.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13))
#include "test_data/staticRefCase13.h"
#endif

static AUDIOLIB_balance_testParams_t testParams[] = {
#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
    {
        STATIC,                                                                             // Test Pattern
        staticRefInLeftCase1,                                                               // staticInLeft
        staticRefOutLeftCase1,                                                              // staticOutLeft
        staticRefInRightCase1,                                                              // staticInRight
        staticRefOutRightCase1,                                                             // staticOutRight
        AUDIOLIB_FLOAT32,                                                                   // Sample Data Type
        128,                                                                                // Samples per channel
        20,                                                                                 // Number of Channels
        -1.0,                                                                               // Balance
        48000,                                                                              // Sampling Rate
        200.0,                                                                              // Smoothing Time
        AUDIOLIB_CALC_STRIDE(128 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideInElements
        AUDIOLIB_CALC_STRIDE(128 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOutElements
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                          // Output data location
        1,                                                                                  // number of reps.
        1,                                                                                  // test ID
        4,                                                                                  // numExecReps
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
    {
        STATIC,                                                                             // Test Pattern
        staticRefInLeftCase2,                                                               // staticInLeft
        staticRefOutLeftCase2,                                                              // staticOutLeft
        staticRefInRightCase2,                                                              // staticInRight
        staticRefOutRightCase2,                                                             // staticOutRight
        AUDIOLIB_FLOAT32,                                                                   // Sample Data Type
        256,                                                                                // Samples per channel
        10,                                                                                 // Number of Channels
        -1.0,                                                                               // Balance
        48000,                                                                              // Sampling Rate
        100.0,                                                                              // Smoothing Time
        AUDIOLIB_CALC_STRIDE(256 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideInElements
        AUDIOLIB_CALC_STRIDE(256 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOutElements
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                          // Output data location
        1,                                                                                  // number of reps.
        2,                                                                                  // test ID
        4,                                                                                  // numExecReps
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
    {
        STATIC,                                                                             // Test Pattern
        staticRefInLeftCase3,                                                               // staticInLeft
        staticRefOutLeftCase3,                                                              // staticOutLeft
        staticRefInRightCase3,                                                              // staticInRight
        staticRefOutRightCase3,                                                             // staticOutRight
        AUDIOLIB_FLOAT32,                                                                   // Sample Data Type
        512,                                                                                // Samples per channel
        5,                                                                                  // Number of Channels
        0.7,                                                                                // Balance
        48000,                                                                              // Sampling Rate
        500.0,                                                                              // Smoothing Time
        AUDIOLIB_CALC_STRIDE(512 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideInElements
        AUDIOLIB_CALC_STRIDE(512 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOutElements
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                          // Output data location
        1,                                                                                  // number of reps.
        3,                                                                                  // test ID
        4,                                                                                  // numExecReps
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
    {
        STATIC,                                                                             // Test Pattern
        staticRefInLeftCase4,                                                               // staticInLeft
        staticRefOutLeftCase4,                                                              // staticOutLeft
        staticRefInRightCase4,                                                              // staticInRight
        staticRefOutRightCase4,                                                             // staticOutRight
        AUDIOLIB_FLOAT32,                                                                   // Sample Data Type
        512,                                                                                // Samples per channel
        4,                                                                                  // Number of Channels
        0.7,                                                                                // Balance
        48000,                                                                              // Sampling Rate
        2.5,                                                                                // Smoothing Time
        AUDIOLIB_CALC_STRIDE(512 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideInElements
        AUDIOLIB_CALC_STRIDE(512 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOutElements
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                          // Output data location
        1,                                                                                  // number of reps.
        4,                                                                                  // test ID
        4,                                                                                  // numExecReps
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
    {
        STATIC,                                                                              // Test Pattern
        staticRefInLeftCase5,                                                                // staticInLeft
        staticRefOutLeftCase5,                                                               // staticOutLeft
        staticRefInRightCase5,                                                               // staticInRight
        staticRefOutRightCase5,                                                              // staticOutRight
        AUDIOLIB_FLOAT32,                                                                    // Sample Data Type
        1024,                                                                                // Samples per channel
        1,                                                                                   // Number of Channels
        0.0,                                                                                 // Balance
        48000,                                                                               // Sampling Rate
        600.0,                                                                               // Smoothing Time
        AUDIOLIB_CALC_STRIDE(1024 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideInElements
        AUDIOLIB_CALC_STRIDE(1024 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOutElements
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                           // Output data location
        1,                                                                                   // number of reps.
        5,                                                                                   // test ID
        5,                                                                                   // numExecReps
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
    {
        STATIC,                                                                              // Test Pattern
        staticRefInLeftCase6,                                                                // staticInLeft
        staticRefOutLeftCase6,                                                               // staticOutLeft
        staticRefInRightCase6,                                                               // staticInRight
        staticRefOutRightCase6,                                                              // staticOutRight
        AUDIOLIB_FLOAT32,                                                                    // Sample Data Type
        2048,                                                                                // Samples per channel
        2,                                                                                   // Number of Channels
        -0.8,                                                                                // Balance
        48000,                                                                               // Sampling Rate
        4.5,                                                                                 // Smoothing Time
        AUDIOLIB_CALC_STRIDE(2048 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideInElements
        AUDIOLIB_CALC_STRIDE(2048 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOutElements
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                           // Output data location
        1,                                                                                   // number of reps.
        6,                                                                                   // test ID
        3,                                                                                   // numExecReps
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
    {
        STATIC,                                                                             // Test Pattern
        staticRefInLeftCase7,                                                               // staticInLeft
        staticRefOutLeftCase7,                                                              // staticOutLeft
        staticRefInRightCase7,                                                              // staticInRight
        staticRefOutRightCase7,                                                             // staticOutRight
        AUDIOLIB_FLOAT32,                                                                   // Sample Data Type
        128,                                                                                // Samples per channel
        1,                                                                                  // Number of Channels
        0.0,                                                                                // Balance
        48000,                                                                              // Sampling Rate
        1.0,                                                                                // Smoothing Time
        AUDIOLIB_CALC_STRIDE(128 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideInElements
        AUDIOLIB_CALC_STRIDE(128 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOutElements
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                          // Output data location
        1,                                                                                  // number of reps.
        7,                                                                                  // test ID
        5,                                                                                  // numExecReps
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
    {
        STATIC,                                                                            // Test Pattern
        staticRefInLeftCase8,                                                              // staticInLeft
        staticRefOutLeftCase8,                                                             // staticOutLeft
        staticRefInRightCase8,                                                             // staticInRight
        staticRefOutRightCase8,                                                            // staticOutRight
        AUDIOLIB_FLOAT32,                                                                  // Sample Data Type
        64,                                                                                // Samples per channel
        64,                                                                                // Number of Channels
        -0.5,                                                                              // Balance
        48000,                                                                             // Sampling Rate
        5.5,                                                                               // Smoothing Time
        AUDIOLIB_CALC_STRIDE(64 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideInElements
        AUDIOLIB_CALC_STRIDE(64 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOutElements
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                         // Output data location
        1,                                                                                 // number of reps.
        8,                                                                                 // test ID
        3,                                                                                 // numExecReps
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
    {
        STATIC,                                                                            // Test Pattern
        staticRefInLeftCase9,                                                              // staticInLeft
        staticRefOutLeftCase9,                                                             // staticOutLeft
        staticRefInRightCase9,                                                             // staticInRight
        staticRefOutRightCase9,                                                            // staticOutRight
        AUDIOLIB_FLOAT32,                                                                  // Sample Data Type
        64,                                                                                // Samples per channel
        64,                                                                                // Number of Channels
        0.0,                                                                               // Balance
        48000,                                                                             // Sampling Rate
        0.0,                                                                               // Smoothing Time
        AUDIOLIB_CALC_STRIDE(64 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideInElements
        AUDIOLIB_CALC_STRIDE(64 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOutElements
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                         // Output data location
        1,                                                                                 // number of reps.
        9,                                                                                 // test ID
        3,                                                                                 // numExecReps
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
    {
        STATIC,                                                                             // Test Pattern
        staticRefInLeftCase10,                                                              // staticInLeft
        staticRefOutLeftCase10,                                                             // staticOutLeft
        staticRefInRightCase10,                                                             // staticInRight
        staticRefOutRightCase10,                                                            // staticOutRight
        AUDIOLIB_FLOAT32,                                                                   // Sample Data Type
        128,                                                                                // Samples per channel
        16,                                                                                 // Number of Channels
        0.0,                                                                                // Balance
        48000,                                                                              // Sampling Rate
        0.0,                                                                                // Smoothing Time
        AUDIOLIB_CALC_STRIDE(128 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideInElements
        AUDIOLIB_CALC_STRIDE(128 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOutElements
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                          // Output data location
        1,                                                                                  // number of reps.
        10,                                                                                 // test ID
        5,                                                                                  // numExecReps
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
    {
        STATIC,                                                                             // Test Pattern
        staticRefInLeftCase11,                                                              // staticInLeft
        staticRefOutLeftCase11,                                                             // staticOutLeft
        staticRefInRightCase11,                                                             // staticInRight
        staticRefOutRightCase11,                                                            // staticOutRight
        AUDIOLIB_FLOAT32,                                                                   // Sample Data Type
        128,                                                                                // Samples per channel
        32,                                                                                 // Number of Channels
        0.0,                                                                                // Balance
        48000,                                                                              // Sampling Rate
        0.0,                                                                                // Smoothing Time
        AUDIOLIB_CALC_STRIDE(128 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideInElements
        AUDIOLIB_CALC_STRIDE(128 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOutElements
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                          // Output data location
        1,                                                                                  // number of reps.
        11,                                                                                 // test ID
        3,                                                                                  // numExecReps
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
    {
        STATIC,                                                                             // Test Pattern
        staticRefInLeftCase12,                                                              // staticInLeft
        staticRefOutLeftCase12,                                                             // staticOutLeft
        staticRefInRightCase12,                                                             // staticInRight
        staticRefOutRightCase12,                                                            // staticOutRight
        AUDIOLIB_FLOAT32,                                                                   // Sample Data Type
        256,                                                                                // Samples per channel
        10,                                                                                 // Number of Channels
        -1.0,                                                                               // Balance
        48000,                                                                              // Sampling Rate
        0.0,                                                                                // Smoothing Time
        AUDIOLIB_CALC_STRIDE(256 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideInElements
        AUDIOLIB_CALC_STRIDE(256 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOutElements
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                          // Output data location
        1,                                                                                  // number of reps.
        12,                                                                                 // test ID
        4,                                                                                  // numExecReps
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13))
    {
        STATIC,                                                                             // Test Pattern
        staticRefInLeftCase13,                                                              // staticInLeft
        staticRefOutLeftCase13,                                                             // staticOutLeft
        staticRefInRightCase13,                                                             // staticInRight
        staticRefOutRightCase13,                                                            // staticOutRight
        AUDIOLIB_FLOAT32,                                                                   // Sample Data Type
        512,                                                                                // Samples per channel
        5,                                                                                  // Number of Channels
        0.5,                                                                                // Balance
        48000,                                                                              // Sampling Rate
        0.0,                                                                                // Smoothing Time
        AUDIOLIB_CALC_STRIDE(512 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideInElements
        AUDIOLIB_CALC_STRIDE(512 * sizeof(AUDIOLIB_FLOAT32), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOutElements
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                          // Output data location
        1,                                                                                  // number of reps.
        13,                                                                                 // test ID
        4,                                                                                  // numExecReps
    },
#endif

};

/*
 *  Sends the test parameter structure and number of tests
 */
void AUDIOLIB_balance_getTestParams(AUDIOLIB_balance_testParams_t** params, int32_t* numTests)
{
   *params   = testParams;
   *numTests = sizeof(testParams) / sizeof(AUDIOLIB_balance_testParams_t);
}
