# Copyright (C) 2026 Texas Instruments Incorporated
#
# SPDX-License-Identifier: Apache-2.0


from __future__ import print_function
from subprocess import call
from sys import platform

import sys
import os
import csv
import math
import numpy as np
import argparse

sys.path.append("../common")
import AUDIOLIB_utils
import file_io


from split import AUDIOLIB_split


def gen_testCaseParams(idatFile, currPrm):

    testId = currPrm["ID"]
    dType = currPrm["dType"]
    totalInputChannels = int(currPrm["totalInputChannels"])
    inSamples = currPrm["samples"]
    testType = currPrm["testType"]
    demoCase = currPrm["demoCase"]
    numOutputs = int(currPrm["numOutputs"])
    numReps = currPrm["numReps"]
    outputDataLocation = currPrm["outputDataLocation"]
    strideInElements = currPrm["strideInElements"]
    strideOutElements = currPrm["strideOutElements"]

    C7100 = currPrm["C7100"]

    if testType == "STATIC":
        in0 = "staticRefInCase" + testId
        out0 = [
            "staticRefOut" + str(idx) + "Case" + testId for idx in range(numOutputs)
        ]
    else:
        in0 = "NULL"
        out0 = ["NULL" for _ in range(numOutputs)]

    if C7100 == "FALSE":
        idatFile.write("#if !defined(__C7100__)\n")

    if demoCase == "true":
        idatFile.write(
            "#if (defined(ALL_TEST_CASES) || (TEST_CASE == %d) || defined(DEMO_CASE))\n"
            % (int(testId))
        )
    else:
        idatFile.write(
            "#if (defined(ALL_TEST_CASES) || (TEST_CASE == %d))\n" % (int(testId))
        )

    idatFile.write("{\n")
    idatFile.write("%s, // Test pattern \n" % ((testType)))
    idatFile.write("%s, // Input buffer\n" % ((in0)))

    # Format output buffer as pointer to static array
    if testType == "STATIC":
        out0_formatted = "(void**)staticOutPtrsCase" + testId
    else:
        out0_formatted = "NULL"
    idatFile.write("%s, // Output buffer \n" % (out0_formatted))

    idatFile.write(
        "%s, // inSamples (S = %d samples per channel)\n"
        % ((inSamples), int(inSamples))
    )
    idatFile.write(
        "%s, // totalInputChannels (C_total = %d channels from input)\n"
        % (totalInputChannels, totalInputChannels)
    )
    idatFile.write("%s, // numOutputs \n" % ((numOutputs)))
    idatFile.write(
        "AUDIOLIB_CALC_STRIDE(%s * sizeof(%s), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn \n"
        % ((strideInElements), (dType))
    )
    idatFile.write(
        "AUDIOLIB_CALC_STRIDE(%s * sizeof(%s), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut \n"
        % ((strideOutElements), (dType))
    )
    idatFile.write("%s, // precision \n" % ((AUDIOLIB_utils.resolve_dType(dType))))
    idatFile.write("%s, // Output data location \n" % (outputDataLocation))
    idatFile.write("%d, // number of reps. \n" % (int(numReps)))
    idatFile.write("%d, // test ID\n" % int(testId))
    isInterleave = int(currPrm.get("isInterleave", 1))
    idatFile.write(
        "%d, // isInputInterleave (1: interleaved, 0: deinterleaved)\n" % isInterleave
    )
    idatFile.write("},\n")
    idatFile.write("#endif\n")

    if C7100 == "FALSE":
        idatFile.write("#endif // if !defined(__C7100__)\n")

    idatFile.write("\n\n")


def gen_idat_file(idatFile, testCases):
    """Generate the idat file

    Args:
        param1 (file object): Input file object to idat.c file
        param2 (dict object): Dict object with test case parameter

    """

    fIn = open("../common/ti_lice_header_idat.txt", "r")
    lines = fIn.readlines()
    fIn.close()
    idatFile.writelines(lines)
    includeString = '#include "AUDIOLIB_split_idat.h"'
    idatFile.writelines(includeString)
    idatFile.write("\n")
    idatFile.write("/*This file is autogenerated*/\n")
    idatFile.write("/*Please do not edit*/\n")
    idatFile.write("\n\n")
    # generate ifdefs for header files
    for testCase in testCases:
        if testCase["testType"] == "STATIC":
            AUDIOLIB_utils.gen_ifdefs(idatFile, testCase)

    # generate static output pointer arrays and outChannels arrays
    for testCase in testCases:
        if testCase["testType"] == "STATIC":
            testId = testCase["ID"]
            numOutputs = int(testCase["numOutputs"])
            channelsPerOutput = int(testCase["totalInputChannels"]) // numOutputs
            demoCase = testCase["demoCase"]

            # Write conditional #ifdef guard matching the test case (same as header includes)
            if demoCase == "true":
                idatFile.write(
                    "#if (defined(ALL_TEST_CASES) || (TEST_CASE == %d) || defined(DEMO_CASE))\n"
                    % (int(testId))
                )
            else:
                idatFile.write(
                    "#if (defined(ALL_TEST_CASES) || (TEST_CASE == %d))\n"
                    % (int(testId))
                )

            # Output pointers array - references to each output's static data
            out_ptrs = ", ".join(
                [f"(void*)staticRefOut{idx}Case{testId}" for idx in range(numOutputs)]
            )
            idatFile.write(
                f"__attribute__((unused)) static void *staticOutPtrsCase{testId}[] = {{\n"
            )
            idatFile.write(f"    {out_ptrs}\n")
            idatFile.write("};\n\n")

            # Output channels array - each output gets channelsPerOutput channels
            channels_list = ", ".join([str(channelsPerOutput)] * numOutputs)
            idatFile.write(
                f"__attribute__((unused)) static int32_t outChannelsCase{testId}[] = {{\n"
            )
            idatFile.write(f"    {channels_list}\n")
            idatFile.write("};\n\n")

            idatFile.write("#endif\n\n")

    # generate parameters for test cases
    idatFile.write("static AUDIOLIB_split_testParams_t testParams[] =  ")
    idatFile.write("{\n")

    for testCase in testCases:
        gen_testCaseParams(idatFile, testCase)

    idatFile.write("};\n\n")
    fIn = open("test_param_function.txt", "r")
    lines = fIn.readlines()

    idatFile.writelines(lines)


def process_test_case(testCase):
    """Convert str to int for necessary parameters and calculate derived values

    Args:
        Param1(:obj: dict) : Dictionary object with test case parameters

    Returns:
        Obj: Dictionary object with necessary parameters converted to int

    """

    testCase["testId"] = int(testCase["ID"])
    # testCase["channelsPerOutput"] = int(testCase["channelsPerOutput"])  # Ch per output
    testCase["totalInputChannels"] = int(
        testCase["totalInputChannels"]
    )  # Total input channels
    testCase["inSamples"] = int(testCase["samples"])
    testCase["numOutputs"] = int(testCase["numOutputs"])
    testCase["strideIn0"] = int(testCase["strideInElements"])
    testCase["strideOut"] = int(testCase["strideOutElements"])
    return testCase


def gen_test_case_header_file(testCase):
    """Generate test case and write out input, filter, and output tensor
    into a header file usable in C/C++ code.

    Split Algorithm: Takes 1 input with totalInputChannels and splits into
    N outputs, each with channelsPerOutput channels. All outputs have same
    number of samples.

    Args:
        param1 (:obj: dict): A dict object with all the test case parameters

    Returns:
        [int int]: Minimum and maximum value in output feature tensor

    """

    ##############################
    # Get test parameter of case #
    ##############################
    tempbuf = []
    testId = testCase["ID"]
    dType = testCase["dType"]
    # channelsPerOutput = testCase["channelsPerOutput"]  # Channels in each output
    inSamples = testCase["inSamples"]  # Samples (S)
    numOutputs = testCase["numOutputs"]  # Number of outputs (N)
    dataFormat = testCase.get("dataFormat", "INTERLEAVED")  # Default to INTERLEAVED

    # Total input channels to be split
    totalInChannels = testCase["totalInputChannels"]

    # Create an instance of AUDIOLIB_split
    isInputInterleave = int(testCase.get("isInterleave", 1))
    split_processor = AUDIOLIB_split(
        dType=dType,
        numChannels=totalInChannels,
        numSamples=inSamples,
        numOutputs=numOutputs,
        isInputInterleave=isInputInterleave,
    )

    # [minVal, maxVal] = AUDIOLIB_utils.minMaxVal(dType)
    [minVal, maxVal] = [-10, 10]

    # Generate aggregated input: (inSamples, totalChannels)
    # Single input buffer with total channels to be split across outputs
    aggregated_size = inSamples * totalInChannels

    if dType[0] == "i" or dType[0] == "u":
        in0_flat = np.random.randint(
            low=minVal, high=maxVal, size=aggregated_size
        ).astype("int")
        in0 = in0_flat.reshape((1, aggregated_size))
        out = split_processor.exec(in0)
    elif dType[0] == "f":
        in0_flat = np.random.uniform(
            low=minVal, high=maxVal, size=aggregated_size
        ).astype("float32")
        in0 = in0_flat.reshape((1, aggregated_size))
        out = split_processor.exec(in0)
    elif dType[0] == "d":
        in0_flat = np.random.uniform(
            low=minVal, high=maxVal, size=aggregated_size
        ).astype("double")
        in0 = in0_flat.reshape((1, aggregated_size))
        out = split_processor.exec(in0)

    headerFileName = "staticRefCase" + str(testId) + ".h"
    # For DEINTERLEAVED: reshape to (totalInChannels, inSamples) before file writing
    # For INTERLEAVED: reshape to (inSamples, totalInChannels)
    if dataFormat == "DEINTERLEAVED":
        in0_for_file = in0_flat.reshape((totalInChannels, inSamples))
    else:  # INTERLEAVED
        in0_for_file = in0_flat.reshape((inSamples, totalInChannels))

    file_io.write_header_file(
        in0_for_file, out, numOutputs, testCase, headerFileName, dataFormat
    )
    for i in range(numOutputs):
        tempbuf.append(np.min(out[i]))
        tempbuf.append(np.max(out[i]))
    # return [np.min(out), np.max(out)]
    return tempbuf


# Parse command line arguments
parser = argparse.ArgumentParser()
parser.add_argument(
    "-a", "--allCases", action="store_true", help="Generate all test cases"
)
myArgs = parser.parse_args()

# CSV file with paratmeters for all test cases
testCasesCsvFile = "../AUDIOLIB_split/test_cases_list.csv"
testIdList = []  # list of test IDs that we want to generate test data
testIdList += range(1, 51)  # Test cases 1-50 from CSV


def gen_test_case(testCase):
    if testCase["testType"] == "STATIC":
        # [minY, maxY] = gen_test_case_header_file(testCase)
        finalOut = gen_test_case_header_file(testCase)
        count = len(finalOut)
        for i in range(0, count, 2):
            print(
                "Test case generation completed for test ID",
                testCase["ID"],
                "w/ min:",
                finalOut[i],
                "and max",
                finalOut[i + 1],
            )
    else:
        print(
            "Skipping test case generation for test ID",
            testCase["ID"],
            "as tesType is RANDOM",
        )


#############################################################################
# Open CSV file with test cases and generate header file with test data for #
# test cases of interest; based on testIdList                               #
#############################################################################

with open(testCasesCsvFile, encoding="utf-8-sig") as csv_file:
    testCaseReader = csv.DictReader(csv_file)
    testCases = list(testCaseReader)

    for testCase in testCases:
        testCase = process_test_case(testCase)

    for testCase in testCases:
        if myArgs.allCases == True:
            gen_test_case(testCase)
        elif int(testCase["ID"]) in testIdList:
            gen_test_case(testCase)


idatFileName = "../../AUDIOLIB_split/AUDIOLIB_split_idat.c"


##########################################################################
# Generate idat.cpp file by parsing all the test cases in the CSV file # #
##########################################################################


with open(idatFileName, "w") as idatFile:
    gen_idat_file(idatFile, testCases)


if platform == "linux" or platform == "linux2":
    call(["clang-format", "-style=file", "-i", idatFileName])
    call(["indent", "-nut", "-i3", "-c55", "-l200", idatFileName])
    call(["rm", idatFileName + "~"])  # remove backup file


print("Idat file generation completed")
