// Copyright (C) 2026 Texas Instruments Incorporated
//
// SPDX-License-Identifier: Apache-2.0
#include "AUDIOLIB_concat_idat.h"
/*This file is autogenerated*/
/*Please do not edit*/

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
#include "test_data/staticRefCase1.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
#include "test_data/staticRefCase2.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
#include "test_data/staticRefCase3.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
#include "test_data/staticRefCase4.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
#include "test_data/staticRefCase5.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
#include "test_data/staticRefCase6.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
#include "test_data/staticRefCase7.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
#include "test_data/staticRefCase8.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
#include "test_data/staticRefCase9.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
#include "test_data/staticRefCase10.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
#include "test_data/staticRefCase11.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
#include "test_data/staticRefCase12.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13))
#include "test_data/staticRefCase13.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 14))
#include "test_data/staticRefCase14.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 15))
#include "test_data/staticRefCase15.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 16))
#include "test_data/staticRefCase16.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 17))
#include "test_data/staticRefCase17.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 18))
#include "test_data/staticRefCase18.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 19))
#include "test_data/staticRefCase19.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 20))
#include "test_data/staticRefCase20.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 21))
#include "test_data/staticRefCase21.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 22))
#include "test_data/staticRefCase22.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 23))
#include "test_data/staticRefCase23.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 24))
#include "test_data/staticRefCase24.h"
#endif

/* ====================================================================== */
/* Static Input Pointer and Channel Count Arrays                        */
/* ====================================================================== */

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
static void *staticRefInCase1[4] = {
   (void *) staticRefInput0Case1,
   (void *) staticRefInput1Case1,
   (void *) staticRefInput2Case1,
   (void *) staticRefInput3Case1,
};
static uint32_t inChannelsCase1[4] = { 1, 1, 1, 1 };
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
static void *staticRefInCase2[4] = {
   (void *) staticRefInput0Case2,
   (void *) staticRefInput1Case2,
   (void *) staticRefInput2Case2,
   (void *) staticRefInput3Case2,
};
static uint32_t inChannelsCase2[4] = { 1, 1, 1, 1 };
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
static void *staticRefInCase3[4] = {
   (void *) staticRefInput0Case3,
   (void *) staticRefInput1Case3,
   (void *) staticRefInput2Case3,
   (void *) staticRefInput3Case3,
};
static uint32_t inChannelsCase3[4] = { 1, 1, 1, 1 };
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
static void *staticRefInCase4[4] = {
   (void *) staticRefInput0Case4,
   (void *) staticRefInput1Case4,
   (void *) staticRefInput2Case4,
   (void *) staticRefInput3Case4,
};
static uint32_t inChannelsCase4[4] = { 1, 1, 1, 1 };
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
static void *staticRefInCase5[3] = {
   (void *) staticRefInput0Case5,
   (void *) staticRefInput1Case5,
   (void *) staticRefInput2Case5,
};
static uint32_t inChannelsCase5[3] = { 4, 4, 4 };
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
static void *staticRefInCase6[3] = {
   (void *) staticRefInput0Case6,
   (void *) staticRefInput1Case6,
   (void *) staticRefInput2Case6,
};
static uint32_t inChannelsCase6[3] = { 5, 5, 5 };
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
static void *staticRefInCase7[1] = {
   (void *) staticRefInput0Case7,
};
static uint32_t inChannelsCase7[1] = { 5 };
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
static void *staticRefInCase8[2] = {
   (void *) staticRefInput0Case8,
   (void *) staticRefInput1Case8,
};
static uint32_t inChannelsCase8[2] = { 8, 8 };
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
static void *staticRefInCase9[2] = {
   (void *) staticRefInput0Case9,
   (void *) staticRefInput1Case9,
};
static uint32_t inChannelsCase9[2] = { 4, 4 };
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
static void *staticRefInCase10[4] = {
   (void *) staticRefInput0Case10,
   (void *) staticRefInput1Case10,
   (void *) staticRefInput2Case10,
   (void *) staticRefInput3Case10,
};
static uint32_t inChannelsCase10[4] = { 3, 3, 3, 3 };
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
static void *staticRefInCase11[3] = {
   (void *) staticRefInput0Case11,
   (void *) staticRefInput1Case11,
   (void *) staticRefInput2Case11,
};
static uint32_t inChannelsCase11[3] = { 7, 7, 7 };
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
static void *staticRefInCase12[8] = {
   (void *) staticRefInput0Case12, (void *) staticRefInput1Case12, (void *) staticRefInput2Case12,
   (void *) staticRefInput3Case12, (void *) staticRefInput4Case12, (void *) staticRefInput5Case12,
   (void *) staticRefInput6Case12, (void *) staticRefInput7Case12,
};
static uint32_t inChannelsCase12[8] = { 4, 4, 4, 4, 4, 4, 4, 4 };
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13))
static void *staticRefInCase13[2] = {
   (void *) staticRefInput0Case13,
   (void *) staticRefInput1Case13,
};
static uint32_t inChannelsCase13[2] = { 4, 2 };
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 14))
static void *staticRefInCase14[3] = {
   (void *) staticRefInput0Case14,
   (void *) staticRefInput1Case14,
   (void *) staticRefInput2Case14,
};
static uint32_t inChannelsCase14[3] = { 4, 2, 3 };
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 15))
static void *staticRefInCase15[3] = {
   (void *) staticRefInput0Case15,
   (void *) staticRefInput1Case15,
   (void *) staticRefInput2Case15,
};
static uint32_t inChannelsCase15[3] = { 2, 1, 3 };
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 16))
static void *staticRefInCase16[2] = {
   (void *) staticRefInput0Case16,
   (void *) staticRefInput1Case16,
};
static uint32_t inChannelsCase16[2] = { 5, 3 };
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 17))
static void *staticRefInCase17[4] = {
   (void *) staticRefInput0Case17,
   (void *) staticRefInput1Case17,
   (void *) staticRefInput2Case17,
   (void *) staticRefInput3Case17,
};
static uint32_t inChannelsCase17[4] = { 1, 2, 1, 4 };
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 18))
static void *staticRefInCase18[2] = {
   (void *) staticRefInput0Case18,
   (void *) staticRefInput1Case18,
};
static uint32_t inChannelsCase18[2] = { 6, 2 };
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 19))
static void *staticRefInCase19[2] = {
   (void *) staticRefInput0Case19,
   (void *) staticRefInput1Case19,
};
static uint32_t inChannelsCase19[2] = { 7, 1 };
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 20))
static void *staticRefInCase20[4] = {
   (void *) staticRefInput0Case20,
   (void *) staticRefInput1Case20,
   (void *) staticRefInput2Case20,
   (void *) staticRefInput3Case20,
};
static uint32_t inChannelsCase20[4] = { 1, 2, 4, 5 };
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 21))
static void *staticRefInCase21[2] = {
   (void *) staticRefInput0Case21,
   (void *) staticRefInput1Case21,
};
static uint32_t inChannelsCase21[2] = { 20, 12 };
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 22))
static void *staticRefInCase22[3] = {
   (void *) staticRefInput0Case22,
   (void *) staticRefInput1Case22,
   (void *) staticRefInput2Case22,
};
static uint32_t inChannelsCase22[3] = { 24, 16, 20 };
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 23))
static void *staticRefInCase23[2] = {
   (void *) staticRefInput0Case23,
   (void *) staticRefInput1Case23,
};
static uint32_t inChannelsCase23[2] = { 10, 6 };
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 24))
static void *staticRefInCase24[4] = {
   (void *) staticRefInput0Case24,
   (void *) staticRefInput1Case24,
   (void *) staticRefInput2Case24,
   (void *) staticRefInput3Case24,
};
static uint32_t inChannelsCase24[4] = { 2, 6, 4, 8 };
#endif

static AUDIOLIB_concat_testParams_t testParams[] = {
#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
   {
    STATIC,                                           // Test pattern
    (void **) staticRefInCase1,                       // pInputs (pointer to array of input pointers)
    staticRefOutCase1,                                // Output buffer
    64,                                               // inSamples
    4,                                                // totalInChannels
    inChannelsCase1,                                  // Pointer to array of per-input channel counts
    0,                                                // isInterleave
    4,                                                // numInputs
    AUDIOLIB_CALC_STRIDE (64 * sizeof (float), AUDIOLIB_ALIGN_SHIFT_64BYTES),   // strideIn0
    AUDIOLIB_CALC_STRIDE (64 * sizeof (float), AUDIOLIB_ALIGN_SHIFT_64BYTES),   // strideOut
    AUDIOLIB_FLOAT32,                                 // precision
    AUDIOLIB_TEST_OUTPUT_MSMC,                        // Output data location
    1,                                                // number of reps.
    1,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
   {
    STATIC,                                           // Test pattern
    (void **) staticRefInCase2,                       // pInputs (pointer to array of input pointers)
    staticRefOutCase2,                                // Output buffer
    64,                                               // inSamples
    4,                                                // totalInChannels
    inChannelsCase2,                                  // Pointer to array of per-input channel counts
    1,                                                // isInterleave
    4,                                                // numInputs
    AUDIOLIB_CALC_STRIDE (64 * sizeof (float), AUDIOLIB_ALIGN_SHIFT_64BYTES),   // strideIn0
    AUDIOLIB_CALC_STRIDE (64 * sizeof (float), AUDIOLIB_ALIGN_SHIFT_64BYTES),   // strideOut
    AUDIOLIB_FLOAT32,                                 // precision
    AUDIOLIB_TEST_OUTPUT_MSMC,                        // Output data location
    1,                                                // number of reps.
    2,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
   {
    STATIC,                                           // Test pattern
    (void **) staticRefInCase3,                       // pInputs (pointer to array of input pointers)
    staticRefOutCase3,                                // Output buffer
    64,                                               // inSamples
    4,                                                // totalInChannels
    inChannelsCase3,                                  // Pointer to array of per-input channel counts
    0,                                                // isInterleave
    4,                                                // numInputs
    AUDIOLIB_CALC_STRIDE (64 * sizeof (double), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideIn0
    AUDIOLIB_CALC_STRIDE (64 * sizeof (double), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideOut
    AUDIOLIB_FLOAT64,                                 // precision
    AUDIOLIB_TEST_OUTPUT_MSMC,                        // Output data location
    1,                                                // number of reps.
    3,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
   {
    STATIC,                                           // Test pattern
    (void **) staticRefInCase4,                       // pInputs (pointer to array of input pointers)
    staticRefOutCase4,                                // Output buffer
    64,                                               // inSamples
    4,                                                // totalInChannels
    inChannelsCase4,                                  // Pointer to array of per-input channel counts
    1,                                                // isInterleave
    4,                                                // numInputs
    AUDIOLIB_CALC_STRIDE (64 * sizeof (double), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideIn0
    AUDIOLIB_CALC_STRIDE (64 * sizeof (double), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideOut
    AUDIOLIB_FLOAT64,                                 // precision
    AUDIOLIB_TEST_OUTPUT_MSMC,                        // Output data location
    1,                                                // number of reps.
    4,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
   {
    STATIC,                                           // Test pattern
    (void **) staticRefInCase5,                       // pInputs (pointer to array of input pointers)
    staticRefOutCase5,                                // Output buffer
    64,                                               // inSamples
    12,                                               // totalInChannels
    inChannelsCase5,                                  // Pointer to array of per-input channel counts
    0,                                                // isInterleave
    3,                                                // numInputs
    AUDIOLIB_CALC_STRIDE (64 * sizeof (double), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideIn0
    AUDIOLIB_CALC_STRIDE (64 * sizeof (double), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideOut
    AUDIOLIB_FLOAT64,                                 // precision
    AUDIOLIB_TEST_OUTPUT_MSMC,                        // Output data location
    1,                                                // number of reps.
    5,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
   {
    STATIC,                                           // Test pattern
    (void **) staticRefInCase6,                       // pInputs (pointer to array of input pointers)
    staticRefOutCase6,                                // Output buffer
    128,                                              // inSamples
    15,                                               // totalInChannels
    inChannelsCase6,                                  // Pointer to array of per-input channel counts
    1,                                                // isInterleave
    3,                                                // numInputs
    AUDIOLIB_CALC_STRIDE (128 * sizeof (double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
    AUDIOLIB_CALC_STRIDE (128 * sizeof (double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
    AUDIOLIB_FLOAT64,                                 // precision
    AUDIOLIB_TEST_OUTPUT_MSMC,                        // Output data location
    1,                                                // number of reps.
    6,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
   {
    STATIC,                                           // Test pattern
    (void **) staticRefInCase7,                       // pInputs (pointer to array of input pointers)
    staticRefOutCase7,                                // Output buffer
    9,                                                // inSamples
    5,                                                // totalInChannels
    inChannelsCase7,                                  // Pointer to array of per-input channel counts
    1,                                                // isInterleave
    1,                                                // numInputs
    AUDIOLIB_CALC_STRIDE (9 * sizeof (double), AUDIOLIB_ALIGN_SHIFT_64BYTES),   // strideIn0
    AUDIOLIB_CALC_STRIDE (9 * sizeof (double), AUDIOLIB_ALIGN_SHIFT_64BYTES),   // strideOut
    AUDIOLIB_FLOAT64,                                 // precision
    AUDIOLIB_TEST_OUTPUT_MSMC,                        // Output data location
    1,                                                // number of reps.
    7,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
   {
    STATIC,                                           // Test pattern
    (void **) staticRefInCase8,                       // pInputs (pointer to array of input pointers)
    staticRefOutCase8,                                // Output buffer
    256,                                              // inSamples
    16,                                               // totalInChannels
    inChannelsCase8,                                  // Pointer to array of per-input channel counts
    0,                                                // isInterleave
    2,                                                // numInputs
    AUDIOLIB_CALC_STRIDE (256 * sizeof (float), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideIn0
    AUDIOLIB_CALC_STRIDE (256 * sizeof (float), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideOut
    AUDIOLIB_FLOAT32,                                 // precision
    AUDIOLIB_TEST_OUTPUT_MSMC,                        // Output data location
    1,                                                // number of reps.
    8,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
   {
    STATIC,                                           // Test pattern
    (void **) staticRefInCase9,                       // pInputs (pointer to array of input pointers)
    staticRefOutCase9,                                // Output buffer
    512,                                              // inSamples
    8,                                                // totalInChannels
    inChannelsCase9,                                  // Pointer to array of per-input channel counts
    1,                                                // isInterleave
    2,                                                // numInputs
    AUDIOLIB_CALC_STRIDE (512 * sizeof (double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
    AUDIOLIB_CALC_STRIDE (512 * sizeof (double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
    AUDIOLIB_FLOAT64,                                 // precision
    AUDIOLIB_TEST_OUTPUT_MSMC,                        // Output data location
    1,                                                // number of reps.
    9,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
   {
    STATIC,                                           // Test pattern
    (void **) staticRefInCase10,                      // pInputs (pointer to array of input pointers)
    staticRefOutCase10,                               // Output buffer
    100,                                              // inSamples
    12,                                               // totalInChannels
    inChannelsCase10,                                 // Pointer to array of per-input channel counts
    0,                                                // isInterleave
    4,                                                // numInputs
    AUDIOLIB_CALC_STRIDE (100 * sizeof (float), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideIn0
    AUDIOLIB_CALC_STRIDE (100 * sizeof (float), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideOut
    AUDIOLIB_FLOAT32,                                 // precision
    AUDIOLIB_TEST_OUTPUT_MSMC,                        // Output data location
    1,                                                // number of reps.
    10,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
   {
    STATIC,                                           // Test pattern
    (void **) staticRefInCase11,                      // pInputs (pointer to array of input pointers)
    staticRefOutCase11,                               // Output buffer
    63,                                               // inSamples
    21,                                               // totalInChannels
    inChannelsCase11,                                 // Pointer to array of per-input channel counts
    1,                                                // isInterleave
    3,                                                // numInputs
    AUDIOLIB_CALC_STRIDE (63 * sizeof (double), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideIn0
    AUDIOLIB_CALC_STRIDE (63 * sizeof (double), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideOut
    AUDIOLIB_FLOAT64,                                 // precision
    AUDIOLIB_TEST_OUTPUT_MSMC,                        // Output data location
    1,                                                // number of reps.
    11,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
   {
    STATIC,                                           // Test pattern
    (void **) staticRefInCase12,                      // pInputs (pointer to array of input pointers)
    staticRefOutCase12,                               // Output buffer
    1024,                                             // inSamples
    32,                                               // totalInChannels
    inChannelsCase12,                                 // Pointer to array of per-input channel counts
    0,                                                // isInterleave
    8,                                                // numInputs
    AUDIOLIB_CALC_STRIDE (1024 * sizeof (float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
    AUDIOLIB_CALC_STRIDE (1024 * sizeof (float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
    AUDIOLIB_FLOAT32,                                 // precision
    AUDIOLIB_TEST_OUTPUT_MSMC,                        // Output data location
    1,                                                // number of reps.
    12,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13))
   {
    STATIC,                                           // Test pattern
    (void **) staticRefInCase13,                      // pInputs (pointer to array of input pointers)
    staticRefOutCase13,                               // Output buffer
    128,                                              // inSamples
    6,                                                // totalInChannels
    inChannelsCase13,                                 // Pointer to array of per-input channel counts
    0,                                                // isInterleave
    2,                                                // numInputs
    AUDIOLIB_CALC_STRIDE (128 * sizeof (float), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideIn0
    AUDIOLIB_CALC_STRIDE (128 * sizeof (float), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideOut
    AUDIOLIB_FLOAT32,                                 // precision
    AUDIOLIB_TEST_OUTPUT_MSMC,                        // Output data location
    1,                                                // number of reps.
    13,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 14))
   {
    STATIC,                                           // Test pattern
    (void **) staticRefInCase14,                      // pInputs (pointer to array of input pointers)
    staticRefOutCase14,                               // Output buffer
    128,                                              // inSamples
    9,                                                // totalInChannels
    inChannelsCase14,                                 // Pointer to array of per-input channel counts
    1,                                                // isInterleave
    3,                                                // numInputs
    AUDIOLIB_CALC_STRIDE (128 * sizeof (float), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideIn0
    AUDIOLIB_CALC_STRIDE (128 * sizeof (float), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideOut
    AUDIOLIB_FLOAT32,                                 // precision
    AUDIOLIB_TEST_OUTPUT_MSMC,                        // Output data location
    1,                                                // number of reps.
    14,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 15))
   {
    STATIC,                                           // Test pattern
    (void **) staticRefInCase15,                      // pInputs (pointer to array of input pointers)
    staticRefOutCase15,                               // Output buffer
    64,                                               // inSamples
    6,                                                // totalInChannels
    inChannelsCase15,                                 // Pointer to array of per-input channel counts
    0,                                                // isInterleave
    3,                                                // numInputs
    AUDIOLIB_CALC_STRIDE (64 * sizeof (double), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideIn0
    AUDIOLIB_CALC_STRIDE (64 * sizeof (double), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideOut
    AUDIOLIB_FLOAT64,                                 // precision
    AUDIOLIB_TEST_OUTPUT_MSMC,                        // Output data location
    1,                                                // number of reps.
    15,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 16))
   {
    STATIC,                                           // Test pattern
    (void **) staticRefInCase16,                      // pInputs (pointer to array of input pointers)
    staticRefOutCase16,                               // Output buffer
    128,                                              // inSamples
    8,                                                // totalInChannels
    inChannelsCase16,                                 // Pointer to array of per-input channel counts
    1,                                                // isInterleave
    2,                                                // numInputs
    AUDIOLIB_CALC_STRIDE (128 * sizeof (double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
    AUDIOLIB_CALC_STRIDE (128 * sizeof (double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
    AUDIOLIB_FLOAT64,                                 // precision
    AUDIOLIB_TEST_OUTPUT_MSMC,                        // Output data location
    1,                                                // number of reps.
    16,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 17))
   {
    STATIC,                                           // Test pattern
    (void **) staticRefInCase17,                      // pInputs (pointer to array of input pointers)
    staticRefOutCase17,                               // Output buffer
    100,                                              // inSamples
    8,                                                // totalInChannels
    inChannelsCase17,                                 // Pointer to array of per-input channel counts
    0,                                                // isInterleave
    4,                                                // numInputs
    AUDIOLIB_CALC_STRIDE (100 * sizeof (float), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideIn0
    AUDIOLIB_CALC_STRIDE (100 * sizeof (float), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideOut
    AUDIOLIB_FLOAT32,                                 // precision
    AUDIOLIB_TEST_OUTPUT_MSMC,                        // Output data location
    1,                                                // number of reps.
    17,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 18))
   {
    STATIC,                                           // Test pattern
    (void **) staticRefInCase18,                      // pInputs (pointer to array of input pointers)
    staticRefOutCase18,                               // Output buffer
    256,                                              // inSamples
    8,                                                // totalInChannels
    inChannelsCase18,                                 // Pointer to array of per-input channel counts
    1,                                                // isInterleave
    2,                                                // numInputs
    AUDIOLIB_CALC_STRIDE (256 * sizeof (double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
    AUDIOLIB_CALC_STRIDE (256 * sizeof (double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
    AUDIOLIB_FLOAT64,                                 // precision
    AUDIOLIB_TEST_OUTPUT_MSMC,                        // Output data location
    1,                                                // number of reps.
    18,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 19))
   {
    STATIC,                                           // Test pattern
    (void **) staticRefInCase19,                      // pInputs (pointer to array of input pointers)
    staticRefOutCase19,                               // Output buffer
    128,                                              // inSamples
    8,                                                // totalInChannels
    inChannelsCase19,                                 // Pointer to array of per-input channel counts
    1,                                                // isInterleave
    2,                                                // numInputs
    AUDIOLIB_CALC_STRIDE (128 * sizeof (float), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideIn0
    AUDIOLIB_CALC_STRIDE (128 * sizeof (float), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideOut
    AUDIOLIB_FLOAT32,                                 // precision
    AUDIOLIB_TEST_OUTPUT_MSMC,                        // Output data location
    1,                                                // number of reps.
    19,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 20))
   {
    STATIC,                                           // Test pattern
    (void **) staticRefInCase20,                      // pInputs (pointer to array of input pointers)
    staticRefOutCase20,                               // Output buffer
    100,                                              // inSamples
    12,                                               // totalInChannels
    inChannelsCase20,                                 // Pointer to array of per-input channel counts
    1,                                                // isInterleave
    4,                                                // numInputs
    AUDIOLIB_CALC_STRIDE (100 * sizeof (float), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideIn0
    AUDIOLIB_CALC_STRIDE (100 * sizeof (float), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideOut
    AUDIOLIB_FLOAT32,                                 // precision
    AUDIOLIB_TEST_OUTPUT_MSMC,                        // Output data location
    1,                                                // number of reps.
    20,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 21))
   {
    STATIC,                                           // Test pattern
    (void **) staticRefInCase21,                      // pInputs (pointer to array of input pointers)
    staticRefOutCase21,                               // Output buffer
    64,                                               // inSamples
    32,                                               // totalInChannels
    inChannelsCase21,                                 // Pointer to array of per-input channel counts
    1,                                                // isInterleave
    2,                                                // numInputs
    AUDIOLIB_CALC_STRIDE (64 * sizeof (float), AUDIOLIB_ALIGN_SHIFT_64BYTES),   // strideIn0
    AUDIOLIB_CALC_STRIDE (64 * sizeof (float), AUDIOLIB_ALIGN_SHIFT_64BYTES),   // strideOut
    AUDIOLIB_FLOAT32,                                 // precision
    AUDIOLIB_TEST_OUTPUT_MSMC,                        // Output data location
    1,                                                // number of reps.
    21,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 22))
   {
    STATIC,                                           // Test pattern
    (void **) staticRefInCase22,                      // pInputs (pointer to array of input pointers)
    staticRefOutCase22,                               // Output buffer
    128,                                              // inSamples
    60,                                               // totalInChannels
    inChannelsCase22,                                 // Pointer to array of per-input channel counts
    1,                                                // isInterleave
    3,                                                // numInputs
    AUDIOLIB_CALC_STRIDE (128 * sizeof (float), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideIn0
    AUDIOLIB_CALC_STRIDE (128 * sizeof (float), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideOut
    AUDIOLIB_FLOAT32,                                 // precision
    AUDIOLIB_TEST_OUTPUT_MSMC,                        // Output data location
    1,                                                // number of reps.
    22,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 23))
   {
    STATIC,                                           // Test pattern
    (void **) staticRefInCase23,                      // pInputs (pointer to array of input pointers)
    staticRefOutCase23,                               // Output buffer
    128,                                              // inSamples
    16,                                               // totalInChannels
    inChannelsCase23,                                 // Pointer to array of per-input channel counts
    1,                                                // isInterleave
    2,                                                // numInputs
    AUDIOLIB_CALC_STRIDE (128 * sizeof (double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
    AUDIOLIB_CALC_STRIDE (128 * sizeof (double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
    AUDIOLIB_FLOAT64,                                 // precision
    AUDIOLIB_TEST_OUTPUT_MSMC,                        // Output data location
    1,                                                // number of reps.
    23,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 24))
   {
    STATIC,                                           // Test pattern
    (void **) staticRefInCase24,                      // pInputs (pointer to array of input pointers)
    staticRefOutCase24,                               // Output buffer
    64,                                               // inSamples
    20,                                               // totalInChannels
    inChannelsCase24,                                 // Pointer to array of per-input channel counts
    1,                                                // isInterleave
    4,                                                // numInputs
    AUDIOLIB_CALC_STRIDE (64 * sizeof (double), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideIn0
    AUDIOLIB_CALC_STRIDE (64 * sizeof (double), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideOut
    AUDIOLIB_FLOAT64,                                 // precision
    AUDIOLIB_TEST_OUTPUT_MSMC,                        // Output data location
    1,                                                // number of reps.
    24,                                               // test ID
    },
#endif

};

/*
 *  Sends the test parameter structure and number of tests
 */
void
AUDIOLIB_concat_getTestParams (AUDIOLIB_concat_testParams_t ** params, int32_t * numTests)
{
   *params = testParams;
   *numTests = sizeof (testParams) / sizeof (AUDIOLIB_concat_testParams_t);
}
