// Copyright (C) 2026 Texas Instruments Incorporated
//
// SPDX-License-Identifier: Apache-2.0

#include "AUDIOLIB_concat_idat.h"
/*This file is autogenerated*/
/*Please do not edit*/

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
#include "test_data/staticRefCase1.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
#include "test_data/staticRefCase2.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
#include "test_data/staticRefCase3.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
#include "test_data/staticRefCase4.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
#include "test_data/staticRefCase5.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
#include "test_data/staticRefCase6.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
#include "test_data/staticRefCase7.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
#include "test_data/staticRefCase8.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
#include "test_data/staticRefCase9.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
#include "test_data/staticRefCase10.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
#include "test_data/staticRefCase11.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
#include "test_data/staticRefCase12.h"
#endif

/* ====================================================================== */
/* Static Input Pointer and Channel Count Arrays                        */
/* ====================================================================== */

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
static void *staticRefInCase1[4] = {
    (void *) staticRefInput0Case1,
    (void *) staticRefInput1Case1,
    (void *) staticRefInput2Case1,
    (void *) staticRefInput3Case1,
};
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
static void *staticRefInCase2[4] = {
    (void *) staticRefInput0Case2,
    (void *) staticRefInput1Case2,
    (void *) staticRefInput2Case2,
    (void *) staticRefInput3Case2,
};
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
static void *staticRefInCase3[4] = {
    (void *) staticRefInput0Case3,
    (void *) staticRefInput1Case3,
    (void *) staticRefInput2Case3,
    (void *) staticRefInput3Case3,
};
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
static void *staticRefInCase4[4] = {
    (void *) staticRefInput0Case4,
    (void *) staticRefInput1Case4,
    (void *) staticRefInput2Case4,
    (void *) staticRefInput3Case4,
};
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
static void *staticRefInCase5[3] = {
    (void *) staticRefInput0Case5,
    (void *) staticRefInput1Case5,
    (void *) staticRefInput2Case5,
};
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
static void *staticRefInCase6[3] = {
    (void *) staticRefInput0Case6,
    (void *) staticRefInput1Case6,
    (void *) staticRefInput2Case6,
};
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
static void *staticRefInCase7[1] = {
    (void *) staticRefInput0Case7,
};
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
static void *staticRefInCase8[2] = {
    (void *) staticRefInput0Case8,
    (void *) staticRefInput1Case8,
};
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
static void *staticRefInCase9[2] = {
    (void *) staticRefInput0Case9,
    (void *) staticRefInput1Case9,
};
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
static void *staticRefInCase10[4] = {
    (void *) staticRefInput0Case10,
    (void *) staticRefInput1Case10,
    (void *) staticRefInput2Case10,
    (void *) staticRefInput3Case10,
};
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
static void *staticRefInCase11[3] = {
    (void *) staticRefInput0Case11,
    (void *) staticRefInput1Case11,
    (void *) staticRefInput2Case11,
};
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
static void *staticRefInCase12[8] = {
    (void *) staticRefInput0Case12, (void *) staticRefInput1Case12, (void *) staticRefInput2Case12,
    (void *) staticRefInput3Case12, (void *) staticRefInput4Case12, (void *) staticRefInput5Case12,
    (void *) staticRefInput6Case12, (void *) staticRefInput7Case12,
};
#endif

static AUDIOLIB_concat_testParams_t testParams[] = {
#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
    {
        STATIC,                     // Test pattern
        (void **) staticRefInCase1, // pInputs (pointer to array of input pointers)
        staticRefOutCase1,          // Output buffer
        64,                         // inSamples
        1,                          // inChannels
        0,                          // isInterleave
        4,                          // numInputs
        AUDIOLIB_CALC_STRIDE(64 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(64 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT32,                                                       // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                              // Output data location
        1,                                                                      // number of reps.
        1,                                                                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
    {
        STATIC,                     // Test pattern
        (void **) staticRefInCase2, // pInputs (pointer to array of input pointers)
        staticRefOutCase2,          // Output buffer
        64,                         // inSamples
        1,                          // inChannels
        1,                          // isInterleave
        4,                          // numInputs
        AUDIOLIB_CALC_STRIDE(64 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(64 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT32,                                                       // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                              // Output data location
        1,                                                                      // number of reps.
        2,                                                                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
    {
        STATIC,                     // Test pattern
        (void **) staticRefInCase3, // pInputs (pointer to array of input pointers)
        staticRefOutCase3,          // Output buffer
        64,                         // inSamples
        1,                          // inChannels
        0,                          // isInterleave
        4,                          // numInputs
        AUDIOLIB_CALC_STRIDE(64 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(64 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT64,                                                        // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        3,                                                                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
    {
        STATIC,                     // Test pattern
        (void **) staticRefInCase4, // pInputs (pointer to array of input pointers)
        staticRefOutCase4,          // Output buffer
        64,                         // inSamples
        1,                          // inChannels
        1,                          // isInterleave
        4,                          // numInputs
        AUDIOLIB_CALC_STRIDE(64 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(64 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT64,                                                        // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        4,                                                                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
    {
        STATIC,                     // Test pattern
        (void **) staticRefInCase5, // pInputs (pointer to array of input pointers)
        staticRefOutCase5,          // Output buffer
        64,                         // inSamples
        4,                          // inChannels
        0,                          // isInterleave
        3,                          // numInputs
        AUDIOLIB_CALC_STRIDE(64 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(64 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT64,                                                        // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        5,                                                                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
    {
        STATIC,                     // Test pattern
        (void **) staticRefInCase6, // pInputs (pointer to array of input pointers)
        staticRefOutCase6,          // Output buffer
        128,                        // inSamples
        5,                          // inChannels
        1,                          // isInterleave
        3,                          // numInputs
        AUDIOLIB_CALC_STRIDE(128 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(128 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT64,                                                         // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                // Output data location
        1,                                                                        // number of reps.
        6,                                                                        // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
    {
        STATIC,                     // Test pattern
        (void **) staticRefInCase7, // pInputs (pointer to array of input pointers)
        staticRefOutCase7,          // Output buffer
        9,                          // inSamples
        5,                          // inChannels
        1,                          // isInterleave
        1,                          // numInputs
        AUDIOLIB_CALC_STRIDE(9 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(9 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT64,                                                       // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                              // Output data location
        1,                                                                      // number of reps.
        7,                                                                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
    {
        STATIC,                     // Test pattern
        (void **) staticRefInCase8, // pInputs (pointer to array of input pointers)
        staticRefOutCase8,          // Output buffer
        256,                        // inSamples
        8,                          // inChannels
        0,                          // isInterleave
        2,                          // numInputs
        AUDIOLIB_CALC_STRIDE(256 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(256 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT32,                                                        // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        8,                                                                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
    {
        STATIC,                     // Test pattern
        (void **) staticRefInCase9, // pInputs (pointer to array of input pointers)
        staticRefOutCase9,          // Output buffer
        512,                        // inSamples
        4,                          // inChannels
        1,                          // isInterleave
        2,                          // numInputs
        AUDIOLIB_CALC_STRIDE(512 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(512 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT64,                                                         // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                // Output data location
        1,                                                                        // number of reps.
        9,                                                                        // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
    {
        STATIC,                      // Test pattern
        (void **) staticRefInCase10, // pInputs (pointer to array of input pointers)
        staticRefOutCase10,          // Output buffer
        100,                         // inSamples
        3,                           // inChannels
        0,                           // isInterleave
        4,                           // numInputs
        AUDIOLIB_CALC_STRIDE(100 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(100 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT32,                                                        // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        10,                                                                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
    {
        STATIC,                      // Test pattern
        (void **) staticRefInCase11, // pInputs (pointer to array of input pointers)
        staticRefOutCase11,          // Output buffer
        63,                          // inSamples
        7,                           // inChannels
        1,                           // isInterleave
        3,                           // numInputs
        AUDIOLIB_CALC_STRIDE(63 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(63 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT64,                                                        // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        11,                                                                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
    {
        STATIC,                      // Test pattern
        (void **) staticRefInCase12, // pInputs (pointer to array of input pointers)
        staticRefOutCase12,          // Output buffer
        1024,                        // inSamples
        4,                           // inChannels
        0,                           // isInterleave
        8,                           // numInputs
        AUDIOLIB_CALC_STRIDE(1024 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(1024 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        AUDIOLIB_FLOAT32,                                                         // precision
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                // Output data location
        1,                                                                        // number of reps.
        12,                                                                       // test ID
    },
#endif

};

/*
 *  Sends the test parameter structure and number of tests
 */
void AUDIOLIB_concat_getTestParams(AUDIOLIB_concat_testParams_t **params, int32_t *numTests)
{
   *params   = testParams;
   *numTests = sizeof(testParams) / sizeof(AUDIOLIB_concat_testParams_t);
}
