# Copyright (C) 2026 Texas Instruments Incorporated
#
# SPDX-License-Identifier: Apache-2.0

from __future__ import print_function
from subprocess import call
from sys import platform

import sys
import numpy as np
import math
import csv
import os
from process import generate_white_noise

sys.path.append("../common")
import AUDIOLIB_utils
import file_io


# ===============================================================
# Test case file generation utilities
# ===============================================================
def gen_testCaseParams(testParamsFile, currPrm):
    testId = currPrm["ID"]
    dType = currPrm["dType"]
    if dType == "AUDIOLIB_FLOAT32":
        dType = "float"
    else:
        dType = "double"

    numSamples = currPrm["numSamples"]
    seed = currPrm["seed"]
    range_val = currPrm["range"]
    samplingRate = currPrm["samplingRate"]
    testType = currPrm["testType"]
    demoCase = currPrm["demoCase"]
    outputDataLocation = currPrm["outputDataLocation"]
    numReps = currPrm["numReps"]
    C7100 = currPrm["C7100"]
    numExecReps = currPrm["numExecReps"]

    if testType in ["STATIC"]:
        out = "staticRefOutCase" + testId
    else:
        out = "NULL"

    if C7100 == "FALSE":
        testParamsFile.write("#if !defined(__C7100__)\n")

    if demoCase == "true":
        testParamsFile.write(
            "#if (defined(ALL_TEST_CASES) || (TEST_CASE == %d) || defined(DEMO_CASE))\n"
            % (int(testId))
        )
    else:
        testParamsFile.write(
            "#if (defined(ALL_TEST_CASES) || (TEST_CASE == %d))\n" % (int(testId))
        )

    testParamsFile.write("{\n")
    testParamsFile.write("%s, // Test pattern \n" % (testType))
    testParamsFile.write("%s, // Output buffer \n" % (out))
    testParamsFile.write("%s, // numSamples \n" % (numSamples))
    testParamsFile.write("%s, // seed \n" % (seed))
    testParamsFile.write("%s, // range \n" % (range_val))
    testParamsFile.write("%s, // precision \n" % (AUDIOLIB_utils.resolve_dType(dType)))
    testParamsFile.write("%s, // Output data location \n" % (outputDataLocation))
    testParamsFile.write("%d, // number of reps. \n" % (int(numReps)))
    testParamsFile.write("%d, // test ID\n" % int(testId))
    testParamsFile.write("%d, // numExecReps (frames)\n" % int(numExecReps))
    testParamsFile.write("},\n")
    testParamsFile.write("#endif\n")

    if C7100 == "FALSE":
        testParamsFile.write("#endif // if !defined(__C7100__)\n")

    testParamsFile.write("\n\n")


def gen_idat_file(idatFile, testCases):
    try:
        with open("../common/ti_lice_header_idat.txt", "r") as fIn:
            lines = fIn.readlines()
            idatFile.writelines(lines)
    except FileNotFoundError:
        print(
            "Warning: ../common/ti_lice_header_idat.txt not found. Skipping license header."
        )

    includeString = '#include "AUDIOLIB_whiteNoiseGenerator_idat.h"'
    idatFile.writelines(includeString)
    idatFile.write("\n/* This file is autogenerated */\n/* Please do not edit */\n\n")

    # generate ifdefs for header files
    for testCase in testCases:
        if testCase["testType"] in ["STATIC"]:
            AUDIOLIB_utils.gen_ifdefs(idatFile, testCase)

    idatFile.write(
        "static AUDIOLIB_whiteNoiseGenerator_testParams_t testParams[] =  {\n"
    )

    for testCase in testCases:
        gen_testCaseParams(idatFile, testCase)

    idatFile.write("};\n\n")

    try:
        with open("test_param_function.txt", "r") as fIn:
            lines = fIn.readlines()
            idatFile.writelines(lines)
    except FileNotFoundError:
        print(
            "Warning: test_param_function.txt not found. Skipping test parameter function."
        )


def process_test_case(testCase):
    testCase["testId"] = int(testCase["ID"])
    testCase["seed"] = int(testCase["seed"])
    testCase["range"] = float(testCase["range"])
    testCase["numSamples"] = int(testCase["numSamples"])
    testCase["samplingRate"] = int(testCase["samplingRate"])
    testCase["numReps"] = int(testCase["numReps"])
    testCase["numExecReps"] = int(testCase.get("numExecReps", 1))  # NEW: frame count
    return testCase


def gen_test_case_header_file(testCase):
    testId = testCase["testId"]
    dType = testCase["dType"]
    numSamples = testCase["numSamples"]
    seed = testCase["seed"]
    range_val = testCase["range"]
    plotSignals = testCase["plotSignals"]
    numExecReps = testCase["numExecReps"]

    target_dtype = np.float32 if dType == "AUDIOLIB_FLOAT32" else np.float64

    out = generate_white_noise(numSamples, numExecReps, seed, range_val, target_dtype)
    totalSamples = numSamples * numExecReps

    if plotSignals == "TRUE":
        file_io.plot_Signals(out, totalSamples, testId)
        waveFileName = f"Testcase_{testId}.wav"
        file_io.write_wave_file(out, testCase, waveFileName)

    headerFileName = "staticRefCase" + str(testId) + ".h"
    file_io.write_header_file(out, testCase, headerFileName)

    return [np.min(out), np.max(out)]


# ===============================================================
# Main script flow
# ===============================================================

testCasesCsvFile = "../AUDIOLIB_whiteNoiseGenerator/test_cases_list.csv"
testIdList = []
testIdList += range(0, 60)

myArgs = AUDIOLIB_utils.getCmdLineArgs()

try:
    with open(testCasesCsvFile, encoding="utf-8-sig") as csv_file:
        testCaseReader = csv.DictReader(csv_file)
        testCases = list(testCaseReader)

        for testCase in testCases:
            testCase = process_test_case(testCase)

        for testCase in testCases:
            if myArgs.allCases or int(testCase["ID"]) in testIdList:
                [minY, maxY] = gen_test_case_header_file(testCase)
                print(f"Test case {testCase['ID']} completed: min={minY}, max={maxY}")
except FileNotFoundError:
    print(f"Error: Test case CSV file not found at {testCasesCsvFile}")
    sys.exit(1)


idatFileName = "../../AUDIOLIB_whiteNoiseGenerator/AUDIOLIB_whiteNoiseGenerator_idat.c"
os.makedirs(os.path.dirname(idatFileName), exist_ok=True)

with open(idatFileName, "w") as idatFile:
    gen_idat_file(idatFile, testCases)

if platform == "linux" or platform == "linux2":
    try:
        call(["clang-format", "-style=file", "-i", idatFileName])
        call(["indent", "-nut", "-i3", "-c55", "-l200", idatFileName])
        call(["rm", idatFileName + "~"])
    except OSError:
        print("Warning: Formatting commands (clang-format, indent) failed.")

print("Idat file generation completed")
