# Copyright (C) 2026 Texas Instruments Incorporated
#
# SPDX-License-Identifier: Apache-2.0

# audiolib_channelMappings.py
# Channel enum mappings for AUDIOLIB balance fader
AUDIOLIB_CHANNEL_MAP = {
    "AUDIOLIB_CHANNEL_FRONT_LEFT": 0,
    "AUDIOLIB_CHANNEL_FRONT_LEFT_TREBBLE": 1,
    "AUDIOLIB_CHANNEL_FRONT_LEFT_MID": 2,
    "AUDIOLIB_CHANNEL_FRONT_LEFT_WOOFER": 3,
    "AUDIOLIB_CHANNEL_FRONT_RIGHT": 4,
    "AUDIOLIB_CHANNEL_FRONT_RIGHT_TREBBLE": 5,
    "AUDIOLIB_CHANNEL_FRONT_RIGHT_MID": 6,
    "AUDIOLIB_CHANNEL_FRONT_RIGHT_WOOFER": 7,
    "AUDIOLIB_CHANNEL_FRONT_CENTER": 8,
    "AUDIOLIB_CHANNEL_LOW_FREQUENCY_EFFECTS": 9,
    "AUDIOLIB_CHANNEL_SIDE_LEFT": 10,
    "AUDIOLIB_CHANNEL_SIDE_RIGHT": 11,
    "AUDIOLIB_CHANNEL_REAR_LEFT": 12,
    "AUDIOLIB_CHANNEL_REAR_RIGHT": 13,
    "AUDIOLIB_CHANNEL_TOP_FRONT_LEFT": 14,
    "AUDIOLIB_CHANNEL_TOP_FRONT_RIGHT": 15,
    "AUDIOLIB_CHANNEL_TOP_MIDDLE_LEFT": 16,
    "AUDIOLIB_CHANNEL_TOP_MIDDLE_RIGHT": 17,
    "AUDIOLIB_CHANNEL_TOP_REAR_LEFT": 18,
    "AUDIOLIB_CHANNEL_TOP_REAR_RIGHT": 19,
    "AUDIOLIB_CHANNEL_OVERHEAD": 20,
}

# LFE balance mode mappings
AUDIOLIB_LFE_BALANCE_MODE_MAP = {
    "AUDIOLIB_LFE_BALANCE_UNAFFECTED": 0,
    "AUDIOLIB_LFE_BALANCE_PARTIAL": 1,
    "AUDIOLIB_LFE_BALANCE_FULL": 2,
}

# LFE fader mode mappings
AUDIOLIB_LFE_FADER_MODE_MAP = {
    "AUDIOLIB_LFE_FADER_UNAFFECTED": 0,
    "AUDIOLIB_LFE_FADER_AVERAGE": 1,
    "AUDIOLIB_LFE_FADER_POSITION_BASED": 2,
    "AUDIOLIB_LFE_FADER_FULL": 3,
}
