# Copyright (C) 2026 Texas Instruments Incorporated
#
# SPDX-License-Identifier: Apache-2.0

from __future__ import print_function
from subprocess import call
from sys import platform

import sys
import numpy as np
import csv

sys.path.append("../common")
# from AUDIOLIB_idat_gen.common import AUDIOLIB_utils
import AUDIOLIB_utils
import file_io
import os
from typeConversion import AUDIOLIB_typeConversion

# sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'common')))


def gen_testCaseParams(testParamsFile, currPrm):
    """Generate and write test case parameters to idat file

    Args:
        param1 (file object): Input file object to idat.c file
        param2 (dict object): Dict object with test case parameter

    """

    testId = currPrm["ID"]
    inChannels = currPrm["inChannels"]
    inSamples = currPrm["inSamples"]
    inDtype = currPrm["inDType"]
    outDtype = currPrm["outDType"]
    strideIn0 = currPrm["strideInElements"]
    strideOut = currPrm["strideOutElements"]
    testType = currPrm["testType"]
    demoCase = currPrm["demoCase"]
    outputDataLocation = currPrm["outputDataLocation"]
    numReps = currPrm["numReps"]
    enableStrideIn = currPrm["enableStrideIn"]
    C7100 = currPrm["C7100"]
    testQ31 = currPrm["TEST_Q31"]

    if testType == "STATIC":
        in0 = "staticRefIn0Case" + testId
        out = "staticRefOutCase" + testId
    else:
        in0 = "NULL"
        in1 = "NULL"
        out = "NULL"

    if C7100 == "FALSE":
        testParamsFile.write("#if !defined(__C7100__)\n")

    if demoCase == "true":
        testParamsFile.write(
            "#if (defined(ALL_TEST_CASES) || (TEST_CASE == %d) || defined(DEMO_CASE))\n"
            % (int(testId))
        )
    else:
        testParamsFile.write(
            "#if (defined(ALL_TEST_CASES) || (TEST_CASE == %d))\n" % (int(testId))
        )

    idatFile.write("{\n")
    idatFile.write("%s, // Test pattern \n" % ((testType)))
    idatFile.write("%s, // Input buffer\n" % ((in0)))
    idatFile.write("%s, // Output buffer \n" % ((out)))
    idatFile.write("%s, // inDtype \n" % ((AUDIOLIB_utils.resolve_dType(inDtype))))
    idatFile.write("%s, // outDtype \n" % ((AUDIOLIB_utils.resolve_dType(outDtype))))
    idatFile.write("%s, // inSamples \n" % ((inSamples)))
    idatFile.write("%s, // inChannels \n" % ((inChannels)))
    if enableStrideIn == "FALSE":
        idatFile.write("%s * sizeof(%s), // strideIn0 \n" % ((strideIn0, inDtype)))
        idatFile.write("%s * sizeof(%s), // strideOut \n" % ((strideOut, outDtype)))
    else:
        idatFile.write(
            "AUDIOLIB_CALC_STRIDE(%s * sizeof(%s), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0 \n"
            % ((strideIn0), (inDtype))
        )
        idatFile.write(
            "AUDIOLIB_CALC_STRIDE(%s * sizeof(%s), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut \n"
            % ((strideOut), (outDtype))
        )
    idatFile.write("%s, // testQ31 \n" % ((testQ31)))
    idatFile.write("%s, // Output data location \n" % (outputDataLocation))
    idatFile.write("%d, // number of reps. \n" % (int(numReps)))
    idatFile.write("%d, // test ID\n" % int(testId))
    idatFile.write("},\n")
    idatFile.write("#endif\n")

    if C7100 == "FALSE":
        testParamsFile.write("#endif // if !defined(__C7100__)\n")

    idatFile.write("\n\n")


def gen_idat_file(idatFile, testCases):
    """Generate the idat file

    Args:
        param1 (file object): Input file object to idat.c file
        param2 (dict object): Dict object with test case parameter

    """

    fIn = open("../common/ti_lice_header_idat.txt", "r")
    lines = fIn.readlines()
    fIn.close()
    idatFile.writelines(lines)
    includeString = '#include "AUDIOLIB_typeConversion_idat.h"'
    idatFile.writelines(includeString)
    idatFile.write("\n")
    idatFile.write("/*This file is autogenerated*/\n")
    idatFile.write("/*Please do not edit*/\n")
    idatFile.write("\n\n")
    # generate ifdefs for header files
    for testCase in testCases:
        if testCase["testType"] == "STATIC":
            AUDIOLIB_utils.gen_ifdefs(idatFile, testCase)

    # generate parameters for test cases
    idatFile.write("static AUDIOLIB_typeConversion_testParams_t testParams[] =  ")
    idatFile.write("{\n")

    for testCase in testCases:
        gen_testCaseParams(idatFile, testCase)

    idatFile.write("};\n\n")
    fIn = open("test_param_function.txt", "r")
    lines = fIn.readlines()

    idatFile.writelines(lines)


def process_test_case(testCase):
    """Convert str to int for necessary parameters

    Args:
        Param1(:obj: dict) : Dictionary object with test case parameters

    Returns:
        Obj: Dictionary object with necessary parameters converted to int

    """

    # print(testCase.keys())
    testCase["testId"] = int(testCase["ID"])
    testCase["inChannels"] = int(testCase["inChannels"])
    testCase["inSamples"] = int(testCase["inSamples"])
    testCase["strideIn0"] = int(testCase["strideInElements"])
    testCase["strideOut"] = int(testCase["strideOutElements"])
    testCase["testQ31"] = int(testCase["TEST_Q31"])

    return testCase


def gen_test_case_header_file(testCase):
    """Generate test case and write out input, filter, and output tensor
    into a header file usable in C/C++ code.

    Args:
        param1 (:obj: dict): A dict object with all the test case
        parameters

    Returns:
        [int int]: Minimum and maximum value in output feature tensor

    """

    ##############################
    # Get test parameter of case #
    ##############################

    testId = testCase["ID"]
    inChannels = testCase["inChannels"]
    inSamples = testCase["inSamples"]
    inDtype = testCase["inDType"]
    outDtype = testCase["outDType"]
    testQ31 = testCase["testQ31"]

    # Create an instance of AUDIOLIB_typeConversion
    typeConversion_processor = AUDIOLIB_typeConversion(
        inDtype=inDtype,
        outDtype=outDtype,
        testQ31=testQ31,
        inChannels=inChannels,
        inSamples=inSamples,
    )

    # Generate appropriate input data based on input data type
    if inDtype == "int16_t":
        [minVal, maxVal] = [-32768, 32767]
        in0 = np.random.uniform(
            low=minVal, high=maxVal, size=(inChannels, inSamples)
        ).astype("int16")
    elif inDtype == "int32_t" and testQ31 == 0:
        [minVal, maxVal] = [-8388608, +8388607]
        in0 = np.random.uniform(
            low=minVal, high=maxVal, size=(inChannels, inSamples)
        ).astype("int32")
    elif inDtype == "int32_t" and testQ31 == 1:
        [minVal, maxVal] = [-2147483648, +2147483647]
        in0 = np.random.uniform(
            low=minVal, high=maxVal, size=(inChannels, inSamples)
        ).astype("int32")
    elif inDtype == "float":
        in0 = np.random.uniform(
            low=-1.0, high=1.1, size=(inChannels, inSamples)
        ).astype(np.float32)
    elif inDtype == "double":
        in0 = np.random.uniform(
            low=-1.0, high=1.1, size=(inChannels, inSamples)
        ).astype(np.double)
    else:
        raise ValueError(f"Unsupported input data type: {inDtype}")

    # Execute the type conversion algorithm using the class
    out = typeConversion_processor.exec(in0)

    headerFileName = "staticRefCase" + str(testId) + ".h"
    file_io.write_header_file(in0, out, testCase, headerFileName)

    return [np.min(out), np.max(out)]


# CSV file with paratmeters for all test cases
testCasesCsvFile = "../AUDIOLIB_typeConversion/test_cases_list.csv"
testIdList = []  # list of test IDs that we want to generate test data
testIdList += range(0, 60)

myArgs = AUDIOLIB_utils.getCmdLineArgs()


def gen_test_case(testCase):
    if testCase["testType"] == "STATIC":
        [minY, maxY] = gen_test_case_header_file(testCase)
        print(
            "Test case generation completed for test ID",
            testCase["ID"],
            "w/ min:",
            minY,
            "and max",
            maxY,
        )
    else:
        print(
            "Skipping test case generation for test ID",
            testCase["ID"],
            "as tesType is RANDOM",
        )


#############################################################################
# Open CSV file with test cases and generate header file with test data for #
# test cases of interest; based on testIdList                               #
#############################################################################

with open(testCasesCsvFile, encoding="utf-8-sig") as csv_file:
    testCaseReader = csv.DictReader(csv_file)
    testCases = list(testCaseReader)

    for testCase in testCases:
        testCase = process_test_case(testCase)

    for testCase in testCases:
        if myArgs.allCases == True:
            gen_test_case(testCase)
        elif int(testCase["ID"]) in testIdList:
            gen_test_case(testCase)


idatFileName = "../../AUDIOLIB_typeConversion/AUDIOLIB_typeConversion_idat.c"


##########################################################################
# Generate idat.cpp file by parsing all the test cases in the CSV file # #
##########################################################################


with open(idatFileName, "w") as idatFile:
    gen_idat_file(idatFile, testCases)


if platform == "linux" or platform == "linux2":
    call(["clang-format", "-style=file", "-i", idatFileName])
    call(["indent", "-nut", "-i3", "-c55", "-l200", idatFileName])
    call(["rm", idatFileName + "~"])  # remove backup file


print("Idat file generation completed")
