// Copyright (C) 2026 Texas Instruments Incorporated
//
// SPDX-License-Identifier: Apache-2.0

#include "AUDIOLIB_typeConversion_idat.h"
/*This file is autogenerated*/
/*Please do not edit*/

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
#include "test_data/staticRefCase1.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
#include "test_data/staticRefCase2.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
#include "test_data/staticRefCase3.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
#include "test_data/staticRefCase4.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
#include "test_data/staticRefCase5.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
#include "test_data/staticRefCase6.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
#include "test_data/staticRefCase7.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
#include "test_data/staticRefCase8.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
#include "test_data/staticRefCase9.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
#include "test_data/staticRefCase10.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
#include "test_data/staticRefCase11.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
#include "test_data/staticRefCase12.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13))
#include "test_data/staticRefCase13.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 14))
#include "test_data/staticRefCase14.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 15))
#include "test_data/staticRefCase15.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 16))
#include "test_data/staticRefCase16.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 17))
#include "test_data/staticRefCase17.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 18))
#include "test_data/staticRefCase18.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 19))
#include "test_data/staticRefCase19.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 20))
#include "test_data/staticRefCase20.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 21))
#include "test_data/staticRefCase21.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 22))
#include "test_data/staticRefCase22.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 23))
#include "test_data/staticRefCase23.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 24))
#include "test_data/staticRefCase24.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 25))
#include "test_data/staticRefCase25.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 26))
#include "test_data/staticRefCase26.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 27))
#include "test_data/staticRefCase27.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 28))
#include "test_data/staticRefCase28.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 29))
#include "test_data/staticRefCase29.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 30))
#include "test_data/staticRefCase30.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 31))
#include "test_data/staticRefCase31.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 32))
#include "test_data/staticRefCase32.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 33))
#include "test_data/staticRefCase33.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 34))
#include "test_data/staticRefCase34.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 35))
#include "test_data/staticRefCase35.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 36))
#include "test_data/staticRefCase36.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 37))
#include "test_data/staticRefCase37.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 38))
#include "test_data/staticRefCase38.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 39))
#include "test_data/staticRefCase39.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 40))
#include "test_data/staticRefCase40.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 41))
#include "test_data/staticRefCase41.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 42))
#include "test_data/staticRefCase42.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 43))
#include "test_data/staticRefCase43.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 44))
#include "test_data/staticRefCase44.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 45))
#include "test_data/staticRefCase45.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 46))
#include "test_data/staticRefCase46.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 47))
#include "test_data/staticRefCase47.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 48))
#include "test_data/staticRefCase48.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 49))
#include "test_data/staticRefCase49.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 50))
#include "test_data/staticRefCase50.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 51))
#include "test_data/staticRefCase51.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 52))
#include "test_data/staticRefCase52.h"
#endif

static AUDIOLIB_typeConversion_testParams_t testParams[] = {
#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
    {
        STATIC,                                                                     // Test pattern
        staticRefIn0Case1,                                                          // Input buffer
        staticRefOutCase1,                                                          // Output buffer
        AUDIOLIB_FLOAT32,                                                           // inDtype
        AUDIOLIB_INT16,                                                             // outDtype
        1035,                                                                       // inSamples
        3,                                                                          // inChannels
        AUDIOLIB_CALC_STRIDE(1035 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES),   // strideIn0
        AUDIOLIB_CALC_STRIDE(1035 * sizeof(int16_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        0,                                                                          // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                  // Output data location
        10,                                                                         // number of reps.
        1,                                                                          // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
    {
        STATIC,                                                                     // Test pattern
        staticRefIn0Case2,                                                          // Input buffer
        staticRefOutCase2,                                                          // Output buffer
        AUDIOLIB_FLOAT32,                                                           // inDtype
        AUDIOLIB_INT16,                                                             // outDtype
        2048,                                                                       // inSamples
        1,                                                                          // inChannels
        AUDIOLIB_CALC_STRIDE(2048 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES),   // strideIn0
        AUDIOLIB_CALC_STRIDE(2048 * sizeof(int16_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        0,                                                                          // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                  // Output data location
        10,                                                                         // number of reps.
        2,                                                                          // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
    {
        STATIC,                                                                  // Test pattern
        staticRefIn0Case3,                                                       // Input buffer
        staticRefOutCase3,                                                       // Output buffer
        AUDIOLIB_FLOAT32,                                                        // inDtype
        AUDIOLIB_INT16,                                                          // outDtype
        1,                                                                       // inSamples
        1,                                                                       // inChannels
        AUDIOLIB_CALC_STRIDE(1 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES),   // strideIn0
        AUDIOLIB_CALC_STRIDE(1 * sizeof(int16_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        0,                                                                       // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        3,                                                                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
    {
        STATIC,                                                                  // Test pattern
        staticRefIn0Case4,                                                       // Input buffer
        staticRefOutCase4,                                                       // Output buffer
        AUDIOLIB_FLOAT32,                                                        // inDtype
        AUDIOLIB_INT16,                                                          // outDtype
        9,                                                                       // inSamples
        3,                                                                       // inChannels
        AUDIOLIB_CALC_STRIDE(9 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES),   // strideIn0
        AUDIOLIB_CALC_STRIDE(9 * sizeof(int16_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        0,                                                                       // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        4,                                                                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
    {
        STATIC,                                                                   // Test pattern
        staticRefIn0Case5,                                                        // Input buffer
        staticRefOutCase5,                                                        // Output buffer
        AUDIOLIB_FLOAT32,                                                         // inDtype
        AUDIOLIB_INT16,                                                           // outDtype
        64,                                                                       // inSamples
        64,                                                                       // inChannels
        AUDIOLIB_CALC_STRIDE(64 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES),   // strideIn0
        AUDIOLIB_CALC_STRIDE(64 * sizeof(int16_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        0,                                                                        // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                // Output data location
        1,                                                                        // number of reps.
        5,                                                                        // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
    {
        STATIC,                                                                     // Test pattern
        staticRefIn0Case6,                                                          // Input buffer
        staticRefOutCase6,                                                          // Output buffer
        AUDIOLIB_FLOAT64,                                                           // inDtype
        AUDIOLIB_INT16,                                                             // outDtype
        1024,                                                                       // inSamples
        3,                                                                          // inChannels
        AUDIOLIB_CALC_STRIDE(1035 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideIn0
        AUDIOLIB_CALC_STRIDE(1035 * sizeof(int16_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        0,                                                                          // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                  // Output data location
        1,                                                                          // number of reps.
        6,                                                                          // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
    {
        STATIC,                                                                     // Test pattern
        staticRefIn0Case7,                                                          // Input buffer
        staticRefOutCase7,                                                          // Output buffer
        AUDIOLIB_FLOAT64,                                                           // inDtype
        AUDIOLIB_INT16,                                                             // outDtype
        2048,                                                                       // inSamples
        1,                                                                          // inChannels
        AUDIOLIB_CALC_STRIDE(2048 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideIn0
        AUDIOLIB_CALC_STRIDE(2048 * sizeof(int16_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        0,                                                                          // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                  // Output data location
        1,                                                                          // number of reps.
        7,                                                                          // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
    {
        STATIC,                                                                  // Test pattern
        staticRefIn0Case8,                                                       // Input buffer
        staticRefOutCase8,                                                       // Output buffer
        AUDIOLIB_FLOAT64,                                                        // inDtype
        AUDIOLIB_INT16,                                                          // outDtype
        1,                                                                       // inSamples
        1,                                                                       // inChannels
        AUDIOLIB_CALC_STRIDE(1 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideIn0
        AUDIOLIB_CALC_STRIDE(1 * sizeof(int16_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        0,                                                                       // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        8,                                                                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
    {
        STATIC,                                                                  // Test pattern
        staticRefIn0Case9,                                                       // Input buffer
        staticRefOutCase9,                                                       // Output buffer
        AUDIOLIB_FLOAT64,                                                        // inDtype
        AUDIOLIB_INT16,                                                          // outDtype
        9,                                                                       // inSamples
        3,                                                                       // inChannels
        AUDIOLIB_CALC_STRIDE(9 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideIn0
        AUDIOLIB_CALC_STRIDE(9 * sizeof(int16_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        0,                                                                       // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        9,                                                                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
    {
        STATIC,                                                                   // Test pattern
        staticRefIn0Case10,                                                       // Input buffer
        staticRefOutCase10,                                                       // Output buffer
        AUDIOLIB_FLOAT64,                                                         // inDtype
        AUDIOLIB_INT16,                                                           // outDtype
        64,                                                                       // inSamples
        64,                                                                       // inChannels
        AUDIOLIB_CALC_STRIDE(64 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideIn0
        AUDIOLIB_CALC_STRIDE(64 * sizeof(int16_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        0,                                                                        // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                // Output data location
        1,                                                                        // number of reps.
        10,                                                                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
    {
        STATIC,                                                                     // Test pattern
        staticRefIn0Case11,                                                         // Input buffer
        staticRefOutCase11,                                                         // Output buffer
        AUDIOLIB_FLOAT32,                                                           // inDtype
        AUDIOLIB_INT32,                                                             // outDtype
        900,                                                                        // inSamples
        3,                                                                          // inChannels
        AUDIOLIB_CALC_STRIDE(1035 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES),   // strideIn0
        AUDIOLIB_CALC_STRIDE(1035 * sizeof(int32_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        0,                                                                          // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                  // Output data location
        1,                                                                          // number of reps.
        11,                                                                         // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
    {
        STATIC,                                                                     // Test pattern
        staticRefIn0Case12,                                                         // Input buffer
        staticRefOutCase12,                                                         // Output buffer
        AUDIOLIB_FLOAT32,                                                           // inDtype
        AUDIOLIB_INT32,                                                             // outDtype
        2048,                                                                       // inSamples
        1,                                                                          // inChannels
        AUDIOLIB_CALC_STRIDE(2048 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES),   // strideIn0
        AUDIOLIB_CALC_STRIDE(2048 * sizeof(int32_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        0,                                                                          // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                  // Output data location
        1,                                                                          // number of reps.
        12,                                                                         // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13))
    {
        STATIC,                                                                  // Test pattern
        staticRefIn0Case13,                                                      // Input buffer
        staticRefOutCase13,                                                      // Output buffer
        AUDIOLIB_FLOAT32,                                                        // inDtype
        AUDIOLIB_INT32,                                                          // outDtype
        1,                                                                       // inSamples
        1,                                                                       // inChannels
        AUDIOLIB_CALC_STRIDE(1 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES),   // strideIn0
        AUDIOLIB_CALC_STRIDE(1 * sizeof(int32_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        0,                                                                       // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        13,                                                                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 14))
    {
        STATIC,                                                                   // Test pattern
        staticRefIn0Case14,                                                       // Input buffer
        staticRefOutCase14,                                                       // Output buffer
        AUDIOLIB_FLOAT32,                                                         // inDtype
        AUDIOLIB_INT32,                                                           // outDtype
        12,                                                                       // inSamples
        3,                                                                        // inChannels
        AUDIOLIB_CALC_STRIDE(12 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES),   // strideIn0
        AUDIOLIB_CALC_STRIDE(12 * sizeof(int32_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        0,                                                                        // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                // Output data location
        1,                                                                        // number of reps.
        14,                                                                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 15))
    {
        STATIC,                                                                   // Test pattern
        staticRefIn0Case15,                                                       // Input buffer
        staticRefOutCase15,                                                       // Output buffer
        AUDIOLIB_FLOAT32,                                                         // inDtype
        AUDIOLIB_INT32,                                                           // outDtype
        64,                                                                       // inSamples
        64,                                                                       // inChannels
        AUDIOLIB_CALC_STRIDE(64 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES),   // strideIn0
        AUDIOLIB_CALC_STRIDE(64 * sizeof(int32_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        0,                                                                        // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                // Output data location
        1,                                                                        // number of reps.
        15,                                                                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 16))
    {
        STATIC,                                                                     // Test pattern
        staticRefIn0Case16,                                                         // Input buffer
        staticRefOutCase16,                                                         // Output buffer
        AUDIOLIB_FLOAT64,                                                           // inDtype
        AUDIOLIB_INT32,                                                             // outDtype
        1013,                                                                       // inSamples
        3,                                                                          // inChannels
        AUDIOLIB_CALC_STRIDE(1035 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideIn0
        AUDIOLIB_CALC_STRIDE(1035 * sizeof(int32_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        0,                                                                          // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                  // Output data location
        1,                                                                          // number of reps.
        16,                                                                         // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 17))
    {
        STATIC,                                                                     // Test pattern
        staticRefIn0Case17,                                                         // Input buffer
        staticRefOutCase17,                                                         // Output buffer
        AUDIOLIB_FLOAT64,                                                           // inDtype
        AUDIOLIB_INT32,                                                             // outDtype
        2048,                                                                       // inSamples
        1,                                                                          // inChannels
        AUDIOLIB_CALC_STRIDE(2048 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideIn0
        AUDIOLIB_CALC_STRIDE(2048 * sizeof(int32_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        0,                                                                          // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                  // Output data location
        1,                                                                          // number of reps.
        17,                                                                         // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 18))
    {
        STATIC,                                                                  // Test pattern
        staticRefIn0Case18,                                                      // Input buffer
        staticRefOutCase18,                                                      // Output buffer
        AUDIOLIB_FLOAT64,                                                        // inDtype
        AUDIOLIB_INT32,                                                          // outDtype
        2,                                                                       // inSamples
        1,                                                                       // inChannels
        AUDIOLIB_CALC_STRIDE(2 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideIn0
        AUDIOLIB_CALC_STRIDE(2 * sizeof(int32_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        0,                                                                       // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        18,                                                                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 19))
    {
        STATIC,                                                                  // Test pattern
        staticRefIn0Case19,                                                      // Input buffer
        staticRefOutCase19,                                                      // Output buffer
        AUDIOLIB_FLOAT64,                                                        // inDtype
        AUDIOLIB_INT32,                                                          // outDtype
        9,                                                                       // inSamples
        7,                                                                       // inChannels
        AUDIOLIB_CALC_STRIDE(9 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideIn0
        AUDIOLIB_CALC_STRIDE(9 * sizeof(int32_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        0,                                                                       // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        19,                                                                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 20))
    {
        STATIC,                                                                   // Test pattern
        staticRefIn0Case20,                                                       // Input buffer
        staticRefOutCase20,                                                       // Output buffer
        AUDIOLIB_FLOAT64,                                                         // inDtype
        AUDIOLIB_INT32,                                                           // outDtype
        64,                                                                       // inSamples
        64,                                                                       // inChannels
        AUDIOLIB_CALC_STRIDE(64 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideIn0
        AUDIOLIB_CALC_STRIDE(64 * sizeof(int32_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        0,                                                                        // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                // Output data location
        1,                                                                        // number of reps.
        20,                                                                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 21))
    {
        STATIC,                                                                     // Test pattern
        staticRefIn0Case21,                                                         // Input buffer
        staticRefOutCase21,                                                         // Output buffer
        AUDIOLIB_INT16,                                                             // inDtype
        AUDIOLIB_FLOAT32,                                                           // outDtype
        1035,                                                                       // inSamples
        5,                                                                          // inChannels
        AUDIOLIB_CALC_STRIDE(1035 * sizeof(int16_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(1035 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES),   // strideOut
        0,                                                                          // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                  // Output data location
        1,                                                                          // number of reps.
        21,                                                                         // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 22))
    {
        STATIC,                                                                     // Test pattern
        staticRefIn0Case22,                                                         // Input buffer
        staticRefOutCase22,                                                         // Output buffer
        AUDIOLIB_INT16,                                                             // inDtype
        AUDIOLIB_FLOAT32,                                                           // outDtype
        1024,                                                                       // inSamples
        2,                                                                          // inChannels
        AUDIOLIB_CALC_STRIDE(2048 * sizeof(int16_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(2048 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES),   // strideOut
        0,                                                                          // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                  // Output data location
        1,                                                                          // number of reps.
        22,                                                                         // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 23))
    {
        STATIC,                                                                  // Test pattern
        staticRefIn0Case23,                                                      // Input buffer
        staticRefOutCase23,                                                      // Output buffer
        AUDIOLIB_INT16,                                                          // inDtype
        AUDIOLIB_FLOAT32,                                                        // outDtype
        3,                                                                       // inSamples
        1,                                                                       // inChannels
        AUDIOLIB_CALC_STRIDE(3 * sizeof(int16_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(3 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES),   // strideOut
        0,                                                                       // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        23,                                                                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 24))
    {
        STATIC,                                                                   // Test pattern
        staticRefIn0Case24,                                                       // Input buffer
        staticRefOutCase24,                                                       // Output buffer
        AUDIOLIB_INT16,                                                           // inDtype
        AUDIOLIB_FLOAT32,                                                         // outDtype
        16,                                                                       // inSamples
        3,                                                                        // inChannels
        AUDIOLIB_CALC_STRIDE(16 * sizeof(int16_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(16 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES),   // strideOut
        0,                                                                        // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                // Output data location
        1,                                                                        // number of reps.
        24,                                                                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 25))
    {
        STATIC,                                                                    // Test pattern
        staticRefIn0Case25,                                                        // Input buffer
        staticRefOutCase25,                                                        // Output buffer
        AUDIOLIB_INT16,                                                            // inDtype
        AUDIOLIB_FLOAT32,                                                          // outDtype
        128,                                                                       // inSamples
        64,                                                                        // inChannels
        AUDIOLIB_CALC_STRIDE(128 * sizeof(int16_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(128 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES),   // strideOut
        0,                                                                         // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                 // Output data location
        1,                                                                         // number of reps.
        25,                                                                        // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 26))
    {
        STATIC,                                                                     // Test pattern
        staticRefIn0Case26,                                                         // Input buffer
        staticRefOutCase26,                                                         // Output buffer
        AUDIOLIB_INT16,                                                             // inDtype
        AUDIOLIB_FLOAT64,                                                           // outDtype
        1000,                                                                       // inSamples
        5,                                                                          // inChannels
        AUDIOLIB_CALC_STRIDE(1000 * sizeof(int16_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(1000 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideOut
        0,                                                                          // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                  // Output data location
        1,                                                                          // number of reps.
        26,                                                                         // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 27))
    {
        STATIC,                                                                     // Test pattern
        staticRefIn0Case27,                                                         // Input buffer
        staticRefOutCase27,                                                         // Output buffer
        AUDIOLIB_INT16,                                                             // inDtype
        AUDIOLIB_FLOAT64,                                                           // outDtype
        1024,                                                                       // inSamples
        2,                                                                          // inChannels
        AUDIOLIB_CALC_STRIDE(2048 * sizeof(int16_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(2048 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideOut
        0,                                                                          // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                  // Output data location
        1,                                                                          // number of reps.
        27,                                                                         // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 28))
    {
        STATIC,                                                                  // Test pattern
        staticRefIn0Case28,                                                      // Input buffer
        staticRefOutCase28,                                                      // Output buffer
        AUDIOLIB_INT16,                                                          // inDtype
        AUDIOLIB_FLOAT64,                                                        // outDtype
        5,                                                                       // inSamples
        1,                                                                       // inChannels
        AUDIOLIB_CALC_STRIDE(5 * sizeof(int16_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(5 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideOut
        0,                                                                       // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        28,                                                                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 29))
    {
        STATIC,                                                                   // Test pattern
        staticRefIn0Case29,                                                       // Input buffer
        staticRefOutCase29,                                                       // Output buffer
        AUDIOLIB_INT16,                                                           // inDtype
        AUDIOLIB_FLOAT64,                                                         // outDtype
        16,                                                                       // inSamples
        3,                                                                        // inChannels
        AUDIOLIB_CALC_STRIDE(16 * sizeof(int16_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(16 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideOut
        0,                                                                        // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                // Output data location
        1,                                                                        // number of reps.
        29,                                                                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 30))
    {
        STATIC,                                                                    // Test pattern
        staticRefIn0Case30,                                                        // Input buffer
        staticRefOutCase30,                                                        // Output buffer
        AUDIOLIB_INT16,                                                            // inDtype
        AUDIOLIB_FLOAT64,                                                          // outDtype
        128,                                                                       // inSamples
        16,                                                                        // inChannels
        AUDIOLIB_CALC_STRIDE(128 * sizeof(int16_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(128 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideOut
        0,                                                                         // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                 // Output data location
        1,                                                                         // number of reps.
        30,                                                                        // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 31))
    {
        STATIC,                                                                     // Test pattern
        staticRefIn0Case31,                                                         // Input buffer
        staticRefOutCase31,                                                         // Output buffer
        AUDIOLIB_INT32,                                                             // inDtype
        AUDIOLIB_FLOAT32,                                                           // outDtype
        1035,                                                                       // inSamples
        5,                                                                          // inChannels
        AUDIOLIB_CALC_STRIDE(1035 * sizeof(int32_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(1035 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES),   // strideOut
        0,                                                                          // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                  // Output data location
        1,                                                                          // number of reps.
        31,                                                                         // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 32))
    {
        STATIC,                                                                     // Test pattern
        staticRefIn0Case32,                                                         // Input buffer
        staticRefOutCase32,                                                         // Output buffer
        AUDIOLIB_INT32,                                                             // inDtype
        AUDIOLIB_FLOAT32,                                                           // outDtype
        1024,                                                                       // inSamples
        2,                                                                          // inChannels
        AUDIOLIB_CALC_STRIDE(2048 * sizeof(int32_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(2048 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES),   // strideOut
        0,                                                                          // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                  // Output data location
        1,                                                                          // number of reps.
        32,                                                                         // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 33))
    {
        STATIC,                                                                  // Test pattern
        staticRefIn0Case33,                                                      // Input buffer
        staticRefOutCase33,                                                      // Output buffer
        AUDIOLIB_INT32,                                                          // inDtype
        AUDIOLIB_FLOAT32,                                                        // outDtype
        3,                                                                       // inSamples
        1,                                                                       // inChannels
        AUDIOLIB_CALC_STRIDE(3 * sizeof(int32_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(3 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES),   // strideOut
        0,                                                                       // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        33,                                                                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 34))
    {
        STATIC,                                                                   // Test pattern
        staticRefIn0Case34,                                                       // Input buffer
        staticRefOutCase34,                                                       // Output buffer
        AUDIOLIB_INT32,                                                           // inDtype
        AUDIOLIB_FLOAT32,                                                         // outDtype
        16,                                                                       // inSamples
        3,                                                                        // inChannels
        AUDIOLIB_CALC_STRIDE(16 * sizeof(int32_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(16 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES),   // strideOut
        0,                                                                        // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                // Output data location
        1,                                                                        // number of reps.
        34,                                                                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 35))
    {
        STATIC,                                                                    // Test pattern
        staticRefIn0Case35,                                                        // Input buffer
        staticRefOutCase35,                                                        // Output buffer
        AUDIOLIB_INT32,                                                            // inDtype
        AUDIOLIB_FLOAT32,                                                          // outDtype
        128,                                                                       // inSamples
        64,                                                                        // inChannels
        AUDIOLIB_CALC_STRIDE(128 * sizeof(int32_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(128 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES),   // strideOut
        0,                                                                         // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                 // Output data location
        1,                                                                         // number of reps.
        35,                                                                        // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 36))
    {
        STATIC,                                                                     // Test pattern
        staticRefIn0Case36,                                                         // Input buffer
        staticRefOutCase36,                                                         // Output buffer
        AUDIOLIB_INT32,                                                             // inDtype
        AUDIOLIB_FLOAT64,                                                           // outDtype
        1000,                                                                       // inSamples
        5,                                                                          // inChannels
        AUDIOLIB_CALC_STRIDE(1000 * sizeof(int32_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(1000 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideOut
        0,                                                                          // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                  // Output data location
        1,                                                                          // number of reps.
        36,                                                                         // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 37))
    {
        STATIC,                                                                     // Test pattern
        staticRefIn0Case37,                                                         // Input buffer
        staticRefOutCase37,                                                         // Output buffer
        AUDIOLIB_INT32,                                                             // inDtype
        AUDIOLIB_FLOAT64,                                                           // outDtype
        1024,                                                                       // inSamples
        2,                                                                          // inChannels
        AUDIOLIB_CALC_STRIDE(2048 * sizeof(int32_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(2048 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideOut
        0,                                                                          // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                  // Output data location
        1,                                                                          // number of reps.
        37,                                                                         // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 38))
    {
        STATIC,                                                                  // Test pattern
        staticRefIn0Case38,                                                      // Input buffer
        staticRefOutCase38,                                                      // Output buffer
        AUDIOLIB_INT32,                                                          // inDtype
        AUDIOLIB_FLOAT64,                                                        // outDtype
        5,                                                                       // inSamples
        1,                                                                       // inChannels
        AUDIOLIB_CALC_STRIDE(5 * sizeof(int32_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(5 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideOut
        0,                                                                       // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                       // number of reps.
        38,                                                                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 39))
    {
        STATIC,                                                                   // Test pattern
        staticRefIn0Case39,                                                       // Input buffer
        staticRefOutCase39,                                                       // Output buffer
        AUDIOLIB_INT32,                                                           // inDtype
        AUDIOLIB_FLOAT64,                                                         // outDtype
        16,                                                                       // inSamples
        3,                                                                        // inChannels
        AUDIOLIB_CALC_STRIDE(16 * sizeof(int32_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(16 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideOut
        0,                                                                        // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                // Output data location
        1,                                                                        // number of reps.
        39,                                                                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 40))
    {
        STATIC,                                                                    // Test pattern
        staticRefIn0Case40,                                                        // Input buffer
        staticRefOutCase40,                                                        // Output buffer
        AUDIOLIB_INT32,                                                            // inDtype
        AUDIOLIB_FLOAT64,                                                          // outDtype
        128,                                                                       // inSamples
        16,                                                                        // inChannels
        AUDIOLIB_CALC_STRIDE(128 * sizeof(int32_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(128 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideOut
        0,                                                                         // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                 // Output data location
        1,                                                                         // number of reps.
        40,                                                                        // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 41))
    {
        STATIC,                                                                     // Test pattern
        staticRefIn0Case41,                                                         // Input buffer
        staticRefOutCase41,                                                         // Output buffer
        AUDIOLIB_INT32,                                                             // inDtype
        AUDIOLIB_FLOAT32,                                                           // outDtype
        1035,                                                                       // inSamples
        5,                                                                          // inChannels
        AUDIOLIB_CALC_STRIDE(1035 * sizeof(int32_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(1035 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES),   // strideOut
        1,                                                                          // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                  // Output data location
        1,                                                                          // number of reps.
        41,                                                                         // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 42))
    {
        STATIC,                                                                     // Test pattern
        staticRefIn0Case42,                                                         // Input buffer
        staticRefOutCase42,                                                         // Output buffer
        AUDIOLIB_INT32,                                                             // inDtype
        AUDIOLIB_FLOAT32,                                                           // outDtype
        1024,                                                                       // inSamples
        2,                                                                          // inChannels
        AUDIOLIB_CALC_STRIDE(2048 * sizeof(int32_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(2048 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES),   // strideOut
        1,                                                                          // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                  // Output data location
        1,                                                                          // number of reps.
        42,                                                                         // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 43))
    {
        STATIC,                                                                    // Test pattern
        staticRefIn0Case43,                                                        // Input buffer
        staticRefOutCase43,                                                        // Output buffer
        AUDIOLIB_INT32,                                                            // inDtype
        AUDIOLIB_FLOAT32,                                                          // outDtype
        128,                                                                       // inSamples
        64,                                                                        // inChannels
        AUDIOLIB_CALC_STRIDE(128 * sizeof(int32_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(128 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES),   // strideOut
        1,                                                                         // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                 // Output data location
        1,                                                                         // number of reps.
        43,                                                                        // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 44))
    {
        STATIC,                                                                     // Test pattern
        staticRefIn0Case44,                                                         // Input buffer
        staticRefOutCase44,                                                         // Output buffer
        AUDIOLIB_INT32,                                                             // inDtype
        AUDIOLIB_FLOAT64,                                                           // outDtype
        1000,                                                                       // inSamples
        5,                                                                          // inChannels
        AUDIOLIB_CALC_STRIDE(1000 * sizeof(int32_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(1000 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideOut
        1,                                                                          // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                  // Output data location
        1,                                                                          // number of reps.
        44,                                                                         // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 45))
    {
        STATIC,                                                                     // Test pattern
        staticRefIn0Case45,                                                         // Input buffer
        staticRefOutCase45,                                                         // Output buffer
        AUDIOLIB_INT32,                                                             // inDtype
        AUDIOLIB_FLOAT64,                                                           // outDtype
        1024,                                                                       // inSamples
        2,                                                                          // inChannels
        AUDIOLIB_CALC_STRIDE(2048 * sizeof(int32_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(2048 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideOut
        1,                                                                          // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                  // Output data location
        1,                                                                          // number of reps.
        45,                                                                         // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 46))
    {
        STATIC,                                                                    // Test pattern
        staticRefIn0Case46,                                                        // Input buffer
        staticRefOutCase46,                                                        // Output buffer
        AUDIOLIB_INT32,                                                            // inDtype
        AUDIOLIB_FLOAT64,                                                          // outDtype
        128,                                                                       // inSamples
        16,                                                                        // inChannels
        AUDIOLIB_CALC_STRIDE(128 * sizeof(int32_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        AUDIOLIB_CALC_STRIDE(128 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideOut
        1,                                                                         // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                 // Output data location
        1,                                                                         // number of reps.
        46,                                                                        // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 47))
    {
        STATIC,                                                                     // Test pattern
        staticRefIn0Case47,                                                         // Input buffer
        staticRefOutCase47,                                                         // Output buffer
        AUDIOLIB_FLOAT32,                                                           // inDtype
        AUDIOLIB_INT32,                                                             // outDtype
        900,                                                                        // inSamples
        3,                                                                          // inChannels
        AUDIOLIB_CALC_STRIDE(1035 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES),   // strideIn0
        AUDIOLIB_CALC_STRIDE(1035 * sizeof(int32_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        1,                                                                          // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                  // Output data location
        1,                                                                          // number of reps.
        47,                                                                         // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 48))
    {
        STATIC,                                                                     // Test pattern
        staticRefIn0Case48,                                                         // Input buffer
        staticRefOutCase48,                                                         // Output buffer
        AUDIOLIB_FLOAT32,                                                           // inDtype
        AUDIOLIB_INT32,                                                             // outDtype
        2048,                                                                       // inSamples
        1,                                                                          // inChannels
        AUDIOLIB_CALC_STRIDE(2048 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES),   // strideIn0
        AUDIOLIB_CALC_STRIDE(2048 * sizeof(int32_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        1,                                                                          // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                  // Output data location
        1,                                                                          // number of reps.
        48,                                                                         // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 49))
    {
        STATIC,                                                                   // Test pattern
        staticRefIn0Case49,                                                       // Input buffer
        staticRefOutCase49,                                                       // Output buffer
        AUDIOLIB_FLOAT32,                                                         // inDtype
        AUDIOLIB_INT32,                                                           // outDtype
        64,                                                                       // inSamples
        64,                                                                       // inChannels
        AUDIOLIB_CALC_STRIDE(64 * sizeof(float), AUDIOLIB_ALIGN_SHIFT_64BYTES),   // strideIn0
        AUDIOLIB_CALC_STRIDE(64 * sizeof(int32_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        1,                                                                        // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                // Output data location
        1,                                                                        // number of reps.
        49,                                                                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 50))
    {
        STATIC,                                                                     // Test pattern
        staticRefIn0Case50,                                                         // Input buffer
        staticRefOutCase50,                                                         // Output buffer
        AUDIOLIB_FLOAT64,                                                           // inDtype
        AUDIOLIB_INT32,                                                             // outDtype
        1013,                                                                       // inSamples
        3,                                                                          // inChannels
        AUDIOLIB_CALC_STRIDE(1035 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideIn0
        AUDIOLIB_CALC_STRIDE(1035 * sizeof(int32_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        1,                                                                          // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                  // Output data location
        1,                                                                          // number of reps.
        50,                                                                         // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 51))
    {
        STATIC,                                                                     // Test pattern
        staticRefIn0Case51,                                                         // Input buffer
        staticRefOutCase51,                                                         // Output buffer
        AUDIOLIB_FLOAT64,                                                           // inDtype
        AUDIOLIB_INT32,                                                             // outDtype
        2048,                                                                       // inSamples
        1,                                                                          // inChannels
        AUDIOLIB_CALC_STRIDE(2048 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideIn0
        AUDIOLIB_CALC_STRIDE(2048 * sizeof(int32_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        1,                                                                          // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                  // Output data location
        1,                                                                          // number of reps.
        51,                                                                         // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 52))
    {
        STATIC,                                                                   // Test pattern
        staticRefIn0Case52,                                                       // Input buffer
        staticRefOutCase52,                                                       // Output buffer
        AUDIOLIB_FLOAT64,                                                         // inDtype
        AUDIOLIB_INT32,                                                           // outDtype
        64,                                                                       // inSamples
        64,                                                                       // inChannels
        AUDIOLIB_CALC_STRIDE(64 * sizeof(double), AUDIOLIB_ALIGN_SHIFT_64BYTES),  // strideIn0
        AUDIOLIB_CALC_STRIDE(64 * sizeof(int32_t), AUDIOLIB_ALIGN_SHIFT_64BYTES), // strideOut
        1,                                                                        // testQ31
        AUDIOLIB_TEST_OUTPUT_MSMC,                                                // Output data location
        1,                                                                        // number of reps.
        52,                                                                       // test ID
    },
#endif

};

/*
 *  Sends the test parameter structure and number of tests
 */
void AUDIOLIB_typeConversion_getTestParams(AUDIOLIB_typeConversion_testParams_t** params, int32_t* numTests)
{
   *params   = testParams;
   *numTests = sizeof(testParams) / sizeof(AUDIOLIB_typeConversion_testParams_t);
}
